### ISSUE TITLE
Segfault running gcore tests, possibly HDF4Image related

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#1019]
## Expected behavior and actual behavior.

Running the `gcore` tests on the master branch reliably produces a segfault during `misc_5`:

```
  TEST: misc_4 ... success
  TEST: misc_5 ... Segmentation fault (core dumped)
```

## Steps to reproduce the problem.

* boot the trusty vagrant vm that's pacakged with GDAL
* `cd ~/gnumake-build-gcc4.8/ && ./resync.sh && make && sudo make install`
* `cd /vagrant/autotest/ && ./run_all.py gcore`

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

master @ 465cf57df07c6f14a2970ba72885dd8ded4584cd

## gdb backtrace

first couple pages of gdb backtrace:
```
#0  PyObject_Malloc (nbytes=nbytes@entry=71) at ../Objects/obmalloc.c:808
#1  0x00000000004c5d42 in string_concat (bb='/foo', a=0x7fffdb51c930) at ../Objects/stringobject.c:1066
#2  PyString_Concat (w='/foo', pv=0x7fffffffd208) at ../Objects/stringobject.c:3870
#3  string_concatenate (v=<optimized out>, v@entry='tmp/tmp/tmp_HDF4Image_1_UInt32', w=w@entry='/foo',
    f=f@entry=Frame 0x7ffff7f32238, for file /usr/lib/python2.7/posixpath.py, line 80, in join (a='tmp/tmp/tmp_HDF4Image_1_UInt32', p=('foo',), path='tmp/tmp/tmp_HDF4Image_1_UInt32', b='foo'), next_instr=next_instr@entry=0x7ffff7fc0892 "}\002") at ../Python/ceval.c:4855
#4  0x00000000004cab63 in PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7ffff7f32238, for file /usr/lib/python2.7/posixpath.py, line 80, in join (a='tmp/tmp/tmp_HDF4Image_1_UInt32', p=('foo',), path='tmp/tmp/tmp_HDF4Image_1_UInt32', b='foo'), throwflag=throwflag@entry=0) at ../Python/ceval.c:1548
#5  0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7ffff7f91430, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>,
    kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3252
#6  0x00000000004c9419 in fast_function (nk=<optimized out>, na=2, n=2, pp_stack=0x7fffffffd5a0, func=<function at remote 0x7ffff7f26ed8>) at ../Python/ceval.c:4116
#7  call_function (oparg=<optimized out>, pp_stack=0x7fffffffd5a0) at ../Python/ceval.c:4041
#8  PyEval_EvalFrameEx (
    f=f@entry=Frame 0xfc6c90, for file /usr/lib/python2.7/shutil.py, line 241, in rmtree (path='tmp/tmp/tmp_HDF4Image_1_UInt32', ignore_errors=False, onerror=<function at remote 0x7fffdb519cf8>, names=['foo'], name='foo'), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#9  0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7fffe0128ab0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>,
    kwcount=0, defs=0x7fffe012ead0, defcount=2, closure=0x0) at ../Python/ceval.c:3252
#10 0x00000000004c8314 in fast_function (nk=<optimized out>, na=1, n=<optimized out>, pp_stack=0x7fffffffd7c0, func=<function at remote 0x7fffe00b4398>) at ../Python/ceval.c:4116
#11 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd7c0) at ../Python/ceval.c:4041
#12 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x100c3f0, for file ./misc.py, line 190, in misc_5_internal (drv=<Driver(this=<SwigPyObject at remote 0x7fffdb522c60>) at remote 0x7fffdb51d910>, datatype=4, nBands=1, dirname='tmp/tmp/tmp_HDF4Image_1_UInt32', filename='tmp/tmp/tmp_HDF4Image_1_UInt32/foo', ds=None), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#13 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=3, pp_stack=0x7fffffffd940, func=<function at remote 0x7fffdb525050>) at ../Python/ceval.c:4106
#14 call_function (oparg=<optimized out>, pp_stack=0x7fffffffd940) at ../Python/ceval.c:4041
#15 PyEval_EvalFrameEx (
    f=f@entry=Frame 0xfe7920, for file ./misc.py, line 252, in misc_5 (ret='success', i=43, drv=<Driver(this=<SwigPyObject at remote 0x7fffdb522c60>) at remote 0x7fffdb51d910>, md={'DMD_CREATIONOPTIONLIST': "<CreationOptionList>   <Option name='RANK' type='int' description='Rank of output SDS'/></CreationOptionList>", 'DMD_HELPTOPIC': 'frmt_hdf4.html', 'DMD_CREATIONDATATYPES': 'Byte Int16 UInt16 Int32 UInt32 Float32 Float64', 'DCAP_OPEN': 'YES', 'DCAP_RASTER': 'YES', 'DCAP_CREATE': 'YES', 'DMD_LONGNAME': 'HDF4 Dataset'}, datatype=4, nBands=1), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#16 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=0, pp_stack=0x7fffffffdac0, func=<function at remote 0x7fffdb5250c8>) at ../Python/ceval.c:4106
#17 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdac0) at ../Python/ceval.c:4041
#18 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffe1fa2420, for file pymod/gdaltest_python2.py, line 43, in run_func (func=<function at remote 0x7fffdb5250c8>),
    throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#19 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffdc40, func=<function at remote 0x7fffe24937d0>) at ../Python/ceval.c:4106
#20 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdc40) at ../Python/ceval.c:4041
#21 PyEval_EvalFrameEx (
    f=f@entry=Frame 0xb6ecf0, for file pymod/gdaltest.py, line 138, in run_tests (test_list=[<function at remote 0x7fffdb519d70>, <function at remote 0x7fffdb519de8>, <function at remote 0x7fffdb519e60>, <function at remote 0x7fffdb519ed8>, <function at remote 0x7fffdb5250c8>, <function at remote 0x7fffdb5252a8>, <function at remote 0x7fffdb525320>, <function at remote 0x7fffdb525398>, <function at remote 0x7fffdb525410>, <function at remote 0x7fffdb525488>, <function at remote 0x7fffdb525500>, <function at remote 0x7fffdb525578>, <function at remote 0x7fffdb5255f0>, <function at remote 0x7fffdb525668>], before_vsimem=None, git_status_before='', set_time=False, had_errors_this_script=0, test_item=<function at remote 0x7fffdb5250c8>, func=<function at remote 0x7fffdb5250c8>, name='misc_5', outline='  TEST: misc_5 ... ', result='success'), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#22 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffddc0, func=<function at remote 0x7fffe1f95848>) at ../Python/ceval.c:4106
#23 call_function (oparg=<optimized out>, pp_stack=0x7fffffffddc0) at ../Python/ceval.c:4041
#24 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffdb51e050, for file <string>, line 1, in <module> (), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#25 0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7ffff7ea6b30, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, kws=<optimized out>,
    kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3252
#26 0x0000000000596e82 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:667
#27 0x0000000000596ebb in run_mod.42576 (mod=<optimized out>, filename=<optimized out>,
    globals={'run_func': <function at remote 0x7fffe24937d0>, 'post_reason': <function at remote 0x7fffe1f95938>, 'wait_process': <function at remote 0x7fffe1f95488>, 'osr': <module at remote 0x7fffe272a3d0>, 'deregister_all_jpeg2000_drivers_but': <function at remote 0x7fffe1f96578>, 'runexternal_out_and_err': <function at remote 0x7fffe1f956e0>, 'find_lib': <function at remote 0x7fffe1f96c80>, 'tempfile': <function at remote 0x7fffe1f97320>, 'approx_equal': <function at remote 0x7fffe1f95b90>, 'SetCacheMax': <function at remote 0x7fffe1f97050>, 'reregister_all_jpeg2000_drivers': <function at remote 0x7fffe1f965f0>, 'get_lineno_2framesback': <function at remote 0x7fffe1f958c0>, 'config_options': <function at remote 0x7fffe1f97230>, 'jpeg2000_drv_unregistered': False, 'count_skipped_tests_download': 0, '__file__': 'pymod/gdaltest.pyc', 'success_counter': 100, 'get_opened_files_has_warned': False, 'urlescape': <function at remote 0x7fffe1f95230>, 'run_slow_tests': <function at remote 0x7fffe1f96938>, 'is_travis_branch': <f...(truncated),
    locals={'files': ['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask.py', 'testnonboundtoswig.py', 'rasterio.py', 'aaigrid_write.py', 'misc.py', 'hdf4_read.py', 'vrtmisc.py', 'vsihdfs.py', 'vsiaz.py', 'pam.py', 'tiff_read.py', 'aaigrid_read.py', 'testnonboundtoswig.pyc', 'colortable.py', 'histogram.py', 'vrt_read.py', 'hdf4_write.py', 'asyncreader.py', 'minixml.py', 'tiff_write.py', 'virtualmem.py', 'tiff_srs.py', 'aaigrid_write.pyc', 'gcps2geotransform.py', 'envi_read.py', 'hfa_read.py', 'vsifile.py', 'pnm_read.pyc', '__pycache__', 'vsicrypt.py', 'hfa_srs.py', 'hfa_rfc40.py', 'vsistdin.py', 'gdal_stats.py', 'geoloc.py', 'vsigs.py', 'gtiff_write.py', 'transformer.py', 'bmp_write.pyc', 'hfa_write.py', 'vsiwebhdfs.py', 'pamproxydb.py', 'overviewds.py', 'numpy_rw.py', 'rfc30.py', 'identify.py', 'vsiswift.py', 'misc.pyc', 'rat.py', 'mask.pyc', 'gdal_api_proxy.py', 'data', 'tmp', 'vsicurl.py', 'pixfun.pyc', 'vsizip.py', 'thread_test.py', 'vsis3.py', 'basic_test.py', 'vsioss.py', 'vsicurl_streaming.py', 'bm...(truncated), flags=<optimized out>, arena=<optimized out>)
    at ../Python/pythonrun.c:1370
#28 0x0000000000596e2e in PyRun_StringFlags (str=0x7fffdb51c684 "run_tests( misc.gdaltest_list)", start=257,
    globals={'run_func': <function at remote 0x7fffe24937d0>, 'post_reason': <function at remote 0x7fffe1f95938>, 'wait_process': <function at remote 0x7fffe1f95488>, 'osr': <module at remote 0x7fffe272a3d0>, 'deregister_all_jpeg2000_drivers_but': <function at remote 0x7fffe1f96578>, 'runexternal_out_and_err': <function at remote 0x7fffe1f956e0>, 'find_lib': <function at remote 0x7fffe1f96c80>, 'tempfile': <function at remote 0x7fffe1f97320>, 'approx_equal': <function at remote 0x7fffe1f95b90>, 'SetCacheMax': <function at remote 0x7fffe1f97050>, 'reregister_all_jpeg2000_drivers': <function at remote 0x7fffe1f965f0>, 'get_lineno_2framesback': <function at remote 0x7fffe1f958c0>, 'config_options': <function at remote 0x7fffe1f97230>, 'jpeg2000_drv_unregistered': False, 'count_skipped_tests_download': 0, '__file__': 'pymod/gdaltest.pyc', 'success_counter': 100, 'get_opened_files_has_warned': False, 'urlescape': <function at remote 0x7fffe1f95230>, 'run_slow_tests': <function at remote 0x7fffe1f96938>, 'is_travis_branch': <f...(truncated),
    locals={'files': ['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask.py', 'testnonboundtoswig.py', 'rasterio.py', 'aaigrid_write.py', 'misc.py', 'hdf4_read.py', 'vrtmisc.py', 'vsihdfs.py', 'vsiaz.py', 'pam.py', 'tiff_read.py', 'aaigrid_read.py', 'testnonboundtoswig.pyc', 'colortable.py', 'histogram.py', 'vrt_read.py', 'hdf4_write.py', 'asyncreader.py', 'minixml.py', 'tiff_write.py', 'virtualmem.py', 'tiff_srs.py', 'aaigrid_write.pyc', 'gcps2geotransform.py', 'envi_read.py', 'hfa_read.py', 'vsifile.py', 'pnm_read.pyc', '__pycache__', 'vsicrypt.py', 'hfa_srs.py', 'hfa_rfc40.py', 'vsistdin.py', 'gdal_stats.py', 'geoloc.py', 'vsigs.py', 'gtiff_write.py', 'transformer.py', 'bmp_write.pyc', 'hfa_write.py', 'vsiwebhdfs.py', 'pamproxydb.py', 'overviewds.py', 'numpy_rw.py', 'rfc30.py', 'identify.py', 'vsiswift.py', 'misc.pyc', 'rat.py', 'mask.pyc', 'gdal_api_proxy.py', 'data', 'tmp', 'vsicurl.py', 'pixfun.pyc', 'vsizip.py', 'thread_test.py', 'vsis3.py', 'basic_test.py', 'vsioss.py', 'vsicurl_streaming.py', 'bm...(truncated), flags=0x0) at ../Python/pythonrun.c:1333
#29 0x00000000004ccc24 in exec_statement (
    locals={'files': ['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask.py', 'testnonboundtoswig.py', 'rasterio.py', 'aaigrid_write.py', 'misc.py', 'hdf4_read.py', 'vrtmisc.py', 'vsihdfs.py', 'vsiaz.py', 'pam.py', 'tiff_read.py', 'aaigrid_read.py', 'testnonboundtoswig.pyc', 'colortable.py', 'histogram.py', 'vrt_read.py', 'hdf4_write.py', 'asyncreader.py', 'minixml.py', 'tiff_write.py', 'virtualmem.py', 'tiff_srs.py', 'aaigrid_write.pyc', 'gcps2geotransform.py', 'envi_read.py', 'hfa_read.py', 'vsifile.py', 'pnm_read.pyc', '__pycache__', 'vsicrypt.py', 'hfa_srs.py', 'hfa_rfc40.py', 'vsistdin.py', 'gdal_stats.py', 'geoloc.py', 'vsigs.py', 'gtiff_write.py', 'transformer.py', 'bmp_write.pyc', 'hfa_write.py', 'vsiwebhdfs.py', 'pamproxydb.py', 'overviewds.py', 'numpy_rw.py', 'rfc30.py', 'identify.py', 'vsiswift.py', 'misc.pyc', 'rat.py', 'mask.pyc', 'gdal_api_proxy.py', 'data', 'tmp', 'vsicurl.py', 'pixfun.pyc', 'vsizip.py', 'thread_test.py', 'vsis3.py', 'basic_test.py', 'vsioss.py', 'vsicurl_streaming.py', 'bm...(truncated),
    globals={'run_func': <function at remote 0x7fffe24937d0>, 'post_reason': <function at remote 0x7fffe1f95938>, 'wait_process': <function at remote 0x7fffe1f95488>, 'osr': <module at remote 0x7fffe272a3d0>, 'deregister_all_jpeg2000_drivers_but': <function at remote 0x7fffe1f96578>, 'runexternal_out_and_err': <function at remote 0x7fffe1f956e0>, 'find_lib': <function at remote 0x7fffe1f96c80>, 'tempfile': <function at remote 0x7fffe1f97320>, 'approx_equal': <function at remote 0x7fffe1f95b90>, 'SetCacheMax': <function at remote 0x7fffe1f97050>, 'reregister_all_jpeg2000_drivers': <function at remote 0x7fffe1f965f0>, 'get_lineno_2framesback': <function at remote 0x7fffe1f958c0>, 'config_options': <function at remote 0x7fffe1f97230>, 'jpeg2000_drv_unregistered': False, 'count_skipped_tests_download': 0, '__file__': 'pymod/gdaltest.pyc', 'success_counter': 100, 'get_opened_files_has_warned': False, 'urlescape': <function at remote 0x7fffe1f95230>, 'run_slow_tests': <function at remote 0x7fffe1f96938>, 'is_travis_branch': <f...(truncated), prog='run_tests( misc.gdaltest_list)',
    f=<optimized out>) at ../Python/ceval.c:4753
```

I can provide a core file if it helps.

**Comment by craigds** [comment]
thanks!
