### ISSUE TITLE
Segfault running tiff_write_125 test in vagrant VM

### ISSUE THREAD

**Issue by craigds** [OSGeo/gdal#1026]
## Expected behavior and actual behavior.

The `tiff_write_125` test in `autotest/gcore/tiff_write.py` reliably segfaults on master, in the trusty vagrant machine.

```
  TEST: tiff_write_124 ... success
  TEST: tiff_write_125 ... ERROR 6: Scanline/tile/strip size bigger than 2GB.
ERROR 6: Scanline/tile/strip size bigger than 2GB.
  Segmentation fault (core dumped)
```

## Steps to reproduce the problem.

* `vagrant up`
* in VM, `cd /vagrant/autotest/ && ./run_all.py gcore`

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

master @ a9fda8eff52207bef5a704065c15858f52824cc3

## gdb trace

```
#0  0x0000000000453465 in PyErr_ExceptionMatches (exc=<optimized out>) at ../Python/errors.c:137
#1  PyErr_NoMemory () at ../Python/errors.c:279
#2  0x0000000000515722 in PyString_FromStringAndSize (str=0x0, size=2147000063) at ../Objects/stringobject.c:90
#3  0x00007ffff6ae4c1f in GDALRasterBandShadow_ReadBlock (buf=<synthetic pointer>, yoff=0, xoff=0, self=0x7fffdc052590) at extensions/gdal_wrap.cpp:5496
#4  _wrap_Band_ReadBlock (args=<optimized out>, kwargs=<optimized out>) at extensions/gdal_wrap.cpp:23234
#5  0x00000000004cb240 in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>, pp_stack=0x7fffffffd730,
    func=<built-in function Band_ReadBlock>) at ../Python/ceval.c:4330
#6  PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7fffdb5465d8, for file /usr/lib/python2.7/dist-packages/osgeo/gdal.py, line 2593, in ReadBlock (self=<Band(this=<SwigPyObject at remote 0x7fffda22bb40>) at remote 0x7fffda22ef90>, args=(0, 0), kwargs={}), throwflag=throwflag@entry=0) at ../Python/ceval.c:2705
#7  0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7fffe2d16330, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>,
    kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3252
#8  0x00000000004c9419 in fast_function (nk=<optimized out>, na=3, n=3, pp_stack=0x7fffffffd950, func=<function at remote 0x7fffe24aac08>)
    at ../Python/ceval.c:4116
#9  call_function (oparg=<optimized out>, pp_stack=0x7fffffffd950) at ../Python/ceval.c:4041
#10 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7fffda24a850, for file ./tiff_write.py, line 5328, in tiff_write_125 (ds=<Dataset(this=<SwigPyObject at remote 0x7fffda22b570>) at remote 0x7fffda22ed10>), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#11 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=0, pp_stack=0x7fffffffdad0, func=<function at remote 0x7fffda236aa0>)
    at ../Python/ceval.c:4106
#12 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdad0) at ../Python/ceval.c:4041
#13 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffe1fc8420, for file pymod/gdaltest_python2.py, line 43, in run_func (func=<function at remote 0x7fffda236aa0>),
    throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#14 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffdc50, func=<function at remote 0x7fffe24b57d0>)
    at ../Python/ceval.c:4106
#15 call_function (oparg=<optimized out>, pp_stack=0x7fffffffdc50) at ../Python/ceval.c:4041
#16 PyEval_EvalFrameEx (
    f=f@entry=Frame 0xb97970, for file pymod/gdaltest.py, line 138, in run_tests (test_list=[<function at remote 0x7fffda225aa0>, <function at remote 0x7fffda225b18>, <function at remote 0x7fffda225b90>, <function at remote 0x7fffda225c08>, <function at remote 0x7fffda225c80>, <function at remote 0x7fffda225cf8>, <function at remote 0x7fffda225d70>, <function at remote 0x7fffda225de8>, <function at remote 0x7fffda225e60>, <function at remote 0x7fffda225ed8>, <function at remote 0x7fffda225f50>, <function at remote 0x7fffda234050>, <function at remote 0x7fffda2340c8>, <function at remote 0x7fffda234140>, <function at remote 0x7fffda2341b8>, <function at remote 0x7fffda234230>, <function at remote 0x7fffda2342a8>, <function at remote 0x7fffda234320>, <function at remote 0x7fffda234398>, <function at remote 0x7fffda234410>, <function at remote 0x7fffda234488>, <function at remote 0x7fffda234500>, <function at remote 0x7fffda234578>, <function at remote 0x7fffda2345f0>, <function at remote 0x7fffda234668>, <function at remote ...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#17 0x00000000004c8762 in fast_function (nk=<optimized out>, na=<optimized out>, n=1, pp_stack=0x7fffffffddd0, func=<function at remote 0x7fffe1fbb848>)
    at ../Python/ceval.c:4106
#18 call_function (oparg=<optimized out>, pp_stack=0x7fffffffddd0) at ../Python/ceval.c:4041
#19 PyEval_EvalFrameEx (f=f@entry=Frame 0x7fffda270560, for file <string>, line 1, in <module> (), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#20 0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7ffff7ea6bb0, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>,
    kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3252
#21 0x0000000000596e82 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:667
#22 0x0000000000596ebb in run_mod.42576 (mod=<optimized out>, filename=<optimized out>,
    globals={'run_func': <function at remote 0x7fffe24b57d0>, 'post_reason': <function at remote 0x7fffe1fbb938>, 'wait_process': <function at remote 0x7fffe1fbb488>, 'osr': <module at remote 0x7fffe274c3d0>, 'test_ct_data': [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 255, 0)], 'deregister_all_jpeg2000_drivers_but': <function at remote 0x7fffe1fbc578>, 'webserver_process': None, 'runexternal_out_and_err': <function at remote 0x7fffe1fbb6e0>, 'find_lib': <function at remote 0x7fffe1fbcc80>, 'tempfile': <function at remote 0x7fffe1fbd320>, 'approx_equal': <function at remote 0x7fffe1fbbb90>, 'SetCacheMax': <function at remote 0x7fffe1fbd050>, 'reregister_all_jpeg2000_drivers': <function at remote 0x7fffe1fbc5f0>, 'get_lineno_2framesback': <function at remote 0x7fffe1fbb8c0>, 'config_options': <function at remote 0x7fffe1fbd230>, 'jpeg2000_drv_unregistered': False, 'count_skipped_tests_download': 11, '__file__': 'pymod/gdaltest.pyc', 'success_counter': 585, 'get_opened_files_has_warned': False, 'urlescape': <function...(truncated),
    locals={'hdf4_write': <module at remote 0x7fffda2d9408>, 'mask': <module at remote 0x7fffe00b9f68>, 'misc': <module at remote 0x7fffdb55e910>, 'module': 'tiff_write', 'vsihdfs': <module at remote 0x7fffda184da8>, 'aaigrid_write': <module at remote 0x7fffdb55e2b8>, 'testnonboundtoswig': <module at remote 0x7fffdb54f4e8>, 'pnm_read': <module at remote 0x7fffe00b9718>, 'dirlist': ['gcore/'], 'vrtmisc': <module at remote 0x7fffda1847f8>, 'tiff_write': <module at remote 0x7fffda2279f0>, 'filename': 'tiff_write.py', 'vsiaz': <module at remote 0x7fffda19da98>, 'run_as_external': False, 'rasterio': <module at remote 0x7fffdb54ff68>, 'pam': <module at remote 0x7fffda302130>, 'old_path': ['/vagrant/autotest', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', 'pymod'], 'files': ['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask...(truncated), flags=<optimized out>, arena=<optimized out>) at ../Python/pythonrun.c:1370
#23 0x0000000000596e2e in PyRun_StringFlags (str=0x7fffda22d414 "run_tests( tiff_write.gdaltest_list)", start=257,
    globals={'run_func': <function at remote 0x7fffe24b57d0>, 'post_reason': <function at remote 0x7fffe1fbb938>, 'wait_process': <function at remote 0x7fffe1fbb488>, 'osr': <module at remote 0x7fffe274c3d0>, 'test_ct_data': [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 255, 0)], 'deregister_all_jpeg2000_drivers_but': <function at remote 0x7fffe1fbc578>, 'webserver_process': None, 'runexternal_out_and_err': <function at remote 0x7fffe1fbb6e0>, 'find_lib': <function at remote 0x7fffe1fbcc80>, 'tempfile': <function at remote 0x7fffe1fbd320>, 'approx_equal': <function at remote 0x7fffe1fbbb90>, 'SetCacheMax': <function at remote 0x7fffe1fbd050>, 'reregister_all_jpeg2000_drivers': <function at remote 0x7fffe1fbc5f0>, 'get_lineno_2framesback': <function at remote 0x7fffe1fbb8c0>, 'config_options': <function at remote 0x7fffe1fbd230>, 'jpeg2000_drv_unregistered': False, 'count_skipped_tests_download': 11, '__file__': 'pymod/gdaltest.pyc', 'success_counter': 585, 'get_opened_files_has_warned': False, 'urlescape': <function...(truncated),
    locals={'hdf4_write': <module at remote 0x7fffda2d9408>, 'mask': <module at remote 0x7fffe00b9f68>, 'misc': <module at remote 0x7fffdb55e910>, 'module': 'tiff_write', 'vsihdfs': <module at remote 0x7fffda184da8>, 'aaigrid_write': <module at remote 0x7fffdb55e2b8>, 'testnonboundtoswig': <module at remote 0x7fffdb54f4e8>, 'pnm_read': <module at remote 0x7fffe00b9718>, 'dirlist': ['gcore/'], 'vrtmisc': <module at remote 0x7fffda1847f8>, 'tiff_write': <module at remote 0x7fffda2279f0>, 'filename': 'tiff_write.py', 'vsiaz': <module at remote 0x7fffda19da98>, 'run_as_external': False, 'rasterio': <module at remote 0x7fffdb54ff68>, 'pam': <module at remote 0x7fffda302130>, 'old_path': ['/vagrant/autotest', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', 'pymod'], 'files': ['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask...(truncated), flags=0x0) at ../Python/pythonrun.c:1333
#24 0x00000000004ccc24 in exec_statement (
    locals={'hdf4_write': <module at remote 0x7fffda2d9408>, 'mask': <module at remote 0x7fffe00b9f68>, 'misc': <module at remote 0x7fffdb55e910>, 'module': 'tiff_write', 'vsihdfs': <module at remote 0x7fffda184da8>, 'aaigrid_write': <module at remote 0x7fffdb55e2b8>, 'testnonboundtoswig': <module at remote 0x7fffdb54f4e8>, 'pnm_read': <module at remote 0x7fffe00b9718>, 'dirlist': ['gcore/'], 'vrtmisc': <module at remote 0x7fffda1847f8>, 'tiff_write': <module at remote 0x7fffda2279f0>, 'filename': 'tiff_write.py', 'vsiaz': <module at remote 0x7fffda19da98>, 'run_as_external': False, 'rasterio': <module at remote 0x7fffdb54ff68>, 'pam': <module at remote 0x7fffda302130>, 'old_path': ['/vagrant/autotest', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages', 'pymod'], 'files': ['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask...(truncated),
    globals={'run_func': <function at remote 0x7fffe24b57d0>, 'post_reason': <function at remote 0x7fffe1fbb938>, 'wait_process': <function at remote 0x7fffe1fbb488>, 'osr': <module at remote 0x7fffe274c3d0>, 'test_ct_data': [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 255, 0)], 'deregister_all_jpeg2000_drivers_but': <function at remote 0x7fffe1fbc578>, 'webserver_process': None, 'runexternal_out_and_err': <function at remote 0x7fffe1fbb6e0>, 'find_lib': <function at remote 0x7fffe1fbcc80>, 'tempfile': <function at remote 0x7fffe1fbd320>, 'approx_equal': <function at remote 0x7fffe1fbbb90>, 'SetCacheMax': <function at remote 0x7fffe1fbd050>, 'reregister_all_jpeg2000_drivers': <function at remote 0x7fffe1fbc5f0>, 'get_lineno_2framesback': <function at remote 0x7fffe1fbb8c0>, 'config_options': <function at remote 0x7fffe1fbd230>, 'jpeg2000_drv_unregistered': False, 'count_skipped_tests_download': 11, '__file__': 'pymod/gdaltest.pyc', 'success_counter': 585, 'get_opened_files_has_warned': False, 'urlescape': <function...(truncated), prog='run_tests( tiff_write.gdaltest_list)', f=<optimized out>) at ../Python/ceval.c:4753
#25 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x9e43c0, for file pymod/gdaltest.py, line 330, in run_all (dirlist=['gcore/'], run_as_external=False, dir_name='gcore/', files=['bmp_write.py', 'pixfun.py', 'rasterio.pyc', 'pnm_read.py', 'mask.py', 'testnonboundtoswig.py', 'rasterio.py', 'aaigrid_write.py', 'misc.py', 'hdf4_read.py', 'vrtmisc.py', 'vsihdfs.py', 'vsiaz.py', 'pam.py', 'tiff_read.py', 'minixml.pyc', 'aaigrid_read.py', 'testnonboundtoswig.pyc', 'colortable.py', 'histogram.py', 'vrt_read.py', 'hdf4_write.py', 'asyncreader.pyc', 'asyncreader.py', 'minixml.py', 'tiff_write.py', 'virtualmem.py', 'tiff_srs.py', 'histogram.pyc', 'aaigrid_write.pyc', 'gcps2geotransform.py', 'envi_read.py', 'vrt_read.pyc', 'hfa_read.py', 'vsifile.py', 'pnm_read.pyc', 'hdf4_write.pyc', '__pycache__', 'vsicrypt.py', 'hfa_srs.py', 'hfa_rfc40.py', 'vrtmisc.pyc', 'vsiaz.pyc', 'vsistdin.py', 'pam.pyc', 'aaigrid_read.pyc', 'gdal_stats.py', 'geoloc.py', 'vsigs.py', 'gtiff_write.py', 'transformer.py', 'bmp_write.pyc', 'hfa_write.py', 'vsiwebhdfs.py', '__init__.pyc', 'pamp...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:1880
#26 0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7ffff7e82930, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>,
    kws=<optimized out>, kwcount=1, defs=0x7ffff7e2fea8, defcount=1, closure=0x0) at ../Python/ceval.c:3252
#27 0x00000000004c8314 in fast_function (nk=<optimized out>, na=1, n=<optimized out>, pp_stack=0x7fffffffe2a0, func=<function at remote 0x7fffe1fbba28>)
    at ../Python/ceval.c:4116
#28 call_function (oparg=<optimized out>, pp_stack=0x7fffffffe2a0) at ../Python/ceval.c:4041
#29 PyEval_EvalFrameEx (f=f@entry=Frame 0x7ffff7e845f0, for file ./run_all.py, line 72, in <module> (), throwflag=throwflag@entry=0) at ../Python/ceval.c:2666
#30 0x00000000004cfedc in PyEval_EvalCodeEx (co=0x7ffff7ed7a30, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>,
    kws=<optimized out>, kwcount=0, defs=0x0, defcount=0, closure=0x0) at ../Python/ceval.c:3252
#31 0x0000000000596e82 in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at ../Python/ceval.c:667
#32 0x0000000000596ebb in run_mod.42576 (mod=<optimized out>, filename=<optimized out>,
```

**Comment by rcoup** [comment]
@craigds does increasing the memory available to the VM fix this?
