### ISSUE TITLE
gdal2tiles.py with --xyz raises TypeError

### ISSUE THREAD

**Issue by calebrob6** [OSGeo/gdal#10356]
### What is the bug?

Running gdal2tiles.py with the `--xyz` flag causes a TypeError while running without `--xyz` does not.

 ```
Traceback (most recent call last):
  File "/home/calebrobinson/.conda/envs/geo/bin/gdal2tiles.py", line 15, in <module>
    sys.exit(main(sys.argv, called_from_main=True))
  File "......./python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4686, in main
    return submain(argv, called_from_main=called_from_main)
  File "......./python3.10/site-packages/osgeo_utils/auxiliary/util.py", line 62, in enable_exceptions_wrapper
    return fun(*args, **kwargs)
  File "......./python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4705, in submain
    single_threaded_tiling(input_file, output_folder, options)
  File "......./python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4552, in single_threaded_tiling
    conf, tile_details = worker_tile_details(input_file, output_folder, options)
  File "......./python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4471, in worker_tile_details
    gdal2tiles.generate_metadata()
  File "......./python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 2811, in generate_metadata
    f.write(self.generate_mapml().encode("utf-8"))
  File "......./python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4419, in generate_mapml
    s = open(template, "rb").read().decode("utf-8")
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Steps to reproduce the issue

To reproduce the issue:
```
gdal2tiles.py --xyz -z 12-19 rgb.tif rgb_tiles/
```
and you should observe an error while the following does not give the error.

```
gdal2tiles.py -z 12-19 rgb.tif rgb_tiles/
```

### Versions and provenance

GDAL 3.9.1, released 2024/06/22 (installed via conda-forge)

I can also confirm that the same command works on the same system with GDAL 3.8.5.

**Comment by elpaso** [comment]
I cannot reproduce on current master on a Linux build. 

There is also a test case covering `--xyz` usage and it passes.

Does the error happen with a particular input file?

**Comment by calebrob6** [comment]
Here's a file that I'm able to reproduce with -- [test_raster_cog.zip](https://github.com/user-attachments/files/16086665/test_raster_cog.zip)

**Comment by elpaso** [comment]
Works fine here both with system's gdal (GDAL 3.4.1, released 2021/12/27) and with master build (GDAL 3.10.0dev-a8fd2d438e, released 2024/07/02 (debug build))

I tested zoom 0-1 for speed, does this work for you?

**Comment by calebrob6** [comment]
If I copy `template_tiles.mapml` to the local directory I'm running in, then it works. This doesn't get called in the `--xyz` path (https://github.com/OSGeo/gdal/blob/a8fd2d438e0a5c5dc1f1b2de8827b1e8eff5402d/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py#L2800)

It looks like my conda environment with 3.9.1 is missing `/share/gdal/template_tiles.mapml`. I'm going to close as this is definitely not an issue in OSGeo/gdal!
