### ISSUE TITLE
`gdal2tiles` crashes if run with `--nodata-values-pct-threshold` but not `--excluded-values`

### ISSUE THREAD

**Issue by jamesscottbrown** [OSGeo/gdal#10363]
### What is the bug?

`gdal2tiles` crashes if run with `--nodata-values-pct-threshold` but not `--excluded-values`. It shouldn't be necessary to define which values are *excluded*, as I am instead specifying how to handle *nodata* pixels. 

### Steps to reproduce the issue

For example:

```
gdal2tiles.py -s epsg:27700 --xyz -z 9-18  --nodata-values-pct-threshold=50 tree_map_web.tif test.tif

Generating Base Tiles:

0Traceback (most recent call last):

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/bin/.gdal2tiles.py-wrapped", line 18, in <module>

    sys.exit(main(sys.argv, called_from_main=True))

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo_utils/gdal2tiles.py", line 4687, in main

    return submain(argv, called_from_main=called_from_main)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo_utils/gdal2tiles.py", line 4706, in submain

    single_threaded_tiling(input_file, output_folder, options)

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo_utils/gdal2tiles.py", line 4553, in single_threaded_tiling

    create_base_tile(conf, tile_detail)

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo_utils/gdal2tiles.py", line 1439, in create_base_tile

    scale_query_to_tile(dsquery, dstile, options, tilefilename=tilefilename)

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo_utils/gdal2tiles.py", line 892, in scale_query_to_tile

    gdal.Warp(

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo/gdal.py", line 1193, in Warp

    return wrapper_GDALWarpDestDS(destNameOrDestDS, srcDSTab, opts, callback, callback_data)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/nix/store/l5zhk7jwvg9v38wl3nkkbcyj3r3yddms-gdal-3.9.0/lib/python3.11/site-packages/osgeo/gdal.py", line 9686, in wrapper_GDALWarpDestDS

    return _gdal.wrapper_GDALWarpDestDS(*args)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

RuntimeError: EXCLUDED_VALUES should contain one or several tuples of 3 values formatted like <R>,<G>,<B> or (<R1>,<G1>,<B1>),(<R2>,<G2>,<B2>) if there are multiple tuples
```

The meaning of *nodata* is defined correctly for my input file - the output of`gdalinfo` includes:

```
Band 1 Block=80000x1 Type=Byte, ColorInterp=Red

  NoData Value=255

Band 2 Block=80000x1 Type=Byte, ColorInterp=Green

  NoData Value=255

Band 3 Block=80000x1 Type=Byte, ColorInterp=Blue

  NoData Value=255
```

### Versions and provenance

```
gdalinfo --version
GDAL 3.9.0, released 2024/05/07
```

I'm running GDAL inside a Nix shell on a MacBook Pro running macOS 14.5 (23F79).

### Additional context

If the `--nodata-values-pct-threshold` argument is provided, then `options.nodata_values_pct_threshold` is set, so [this branch is taken](https://github.com/OSGeo/gdal/blob/c89aeb430754a637b6687f836859835760456802/swig/python/gdal-utils/osgeo_utils/gdal2tiles.py#L894):

```python
    if options.resampling == "average" and (
        options.excluded_values or options.nodata_values_pct_threshold < 100
    ):

        gdal.Warp(
            dstile,
            dsquery,
            options="-r average "
            + f"-wo EXCLUDED_VALUES={options.excluded_values} "
            + f"-wo EXCLUDED_VALUES_PCT_THRESHOLD={options.excluded_values_pct_threshold} "
            + f"-wo NODATA_VALUES_PCT_THRESHOLD={options.nodata_values_pct_threshold}",
        )
```

However, `options.excluded_values` is not necessarily set when `options.nodata_values_pct_threshold` is.

This fragment of code should probably be something more like:

```python

    if options.resampling == "average" and (
        options.excluded_values or options.nodata_values_pct_threshold < 100
    ):

        options = "-r average "

        if options.nodata_values_pct_threshold:
            options += f"-wo NODATA_VALUES_PCT_THRESHOLD={options.nodata_values_pct_threshold}"

        if options.excluded_values and options.excluded_values_pct_threshold:
	    options += f"-wo EXCLUDED_VALUES={options.excluded_values} "
	    options += f"-wo EXCLUDED_VALUES_PCT_THRESHOLD={options.excluded_values_pct_threshold} "
	elif options.excluded_values_pct_threshold:
             exit_with_error("You must specify --excluded-values if you specify --nodata-values-pct-threshold")

        gdal.Warp(
            dstile,
            dsquery,
            options=options,
        )

```

I don't understand why this issue doesn't cause the [`test_gdal2tiles_nodata_values_pct_threshold`](https://github.com/OSGeo/gdal/blob/master/autotest/pyscripts/test_gdal2tiles.py#L685) test (in `gdal/autotest/pyscripts/test_gdal2tiles.py`) to fail when it tried to run:

```python
    test_py_scripts.run_py_script_as_external_script(
        script_path,
        "gdal2tiles",
        f"-q -z 0-1 --nodata-values-pct-threshold=25 {input_tif} {output_folder}",
    )
```

**Comment by rouault** [comment]
Fix in https://github.com/OSGeo/gdal/pull/10366

> I don't understand why this issue doesn't cause the [`test_gdal2tiles_nodata_values_pct_threshold`](https://github.com/OSGeo/gdal/blob/master/autotest/pyscripts/test_gdal2tiles.py#L685) test

Actually the NODATA_VALUES_PCT_THRESHOLD warp option was set to "NODATA_VALUES_PCT_THRESHOLD=None" and the warper saw it as a single value. The test was done on a single-band value, so a single nodata value was fine. Whereas on a 3 band raster, one needs to specify 3 values.
