### ISSUE TITLE
gdal_translate segfault with MrSID / ALIGNED_LEVELS

### ISSUE THREAD

**Issue by kmarsh** [OSGeo/gdal#10697]
### What is the bug?

I'm encountering a segfault with certain MrSID files from NAIP. The error only happens when I used the `-co ALIGNED_LEVELS` flag in conjunction with `-tr 4.77 4.77` (to generate level 15 tiles.) `-tr 9.55 9.55`, for example, works fine.

Most I tried worked fine, but 13/88 counties in Ohio, for example, exited with an error when I tried to generate a COG from them using the following command:

```
gdal_translate -tr 4.77 4.77 \
  -b 1 -b 2 -b 3 \
  -of COG \
  -co COMPRESS=WEBP -co QUALITY=95 \
  -co TILING_SCHEME=GoogleMapsCompatible -co ALIGNED_LEVELS=6 \
  -co BIGTIFF=IF_SAFER \
  -r bilinear \
  ortho_1-1_hm_s_oh029_2023_1.sid \
  ortho_1-1_hm_s_oh029_2023_1.tif
```

I also ran with gdb to get more information:

```
   Starting program: /usr/local/bin/gdal_translate -tr 4.77 4.77 -b 1 -b 2 -b 3 -of COG -co COMPRESS=WEBP -co QUALITY=95 -co TILING_SCHEME=GoogleMapsCompatible -co ALIGNED_LEVELS=6 -co BIGTIFF=IF_SAFER -r bilinear ortho_1-1_hm_s_oh029_2023_1.sid ortho_1-1_hm_s_oh029_2023_1.tif
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Input file size is 176900, 139733
0[New Thread 0x7faa77d0a640 (LWP 241)]
[New Thread 0x7faa77909640 (LWP 242)]
[New Thread 0x7faa77508640 (LWP 243)]
[New Thread 0x7faa77107640 (LWP 244)]
[New Thread 0x7faa76905640 (LWP 246)]
[New Thread 0x7faa76d06640 (LWP 245)]
[New Thread 0x7faa76504640 (LWP 247)]
[New Thread 0x7faa76103640 (LWP 248)]
[New Thread 0x7faa75d02640 (LWP 249)]
[New Thread 0x7faa75901640 (LWP 250)]
[New Thread 0x7faa750ff640 (LWP 252)]
[New Thread 0x7faa74cfe640 (LWP 253)]
[New Thread 0x7faa75500640 (LWP 251)]
[New Thread 0x7faa744fc640 (LWP 254)]
[New Thread 0x7faa748fd640 (LWP 255)]
...10...20...30..
Thread 1 "gdal_translate" received signal SIGSEGV, Segmentation fault.
0x00007faa7f63df20 in GDALDataset::BandBasedRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
(gdb)
(gdb) bt
#0  0x00007faa7f63df20 in GDALDataset::BandBasedRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#1  0x00007faa7f6f3c31 in GDALDataset::BlockBasedRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#2  0x00007faa7f0765fe in MrSIDRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35

# snip, there are lots more of these but mostly repeated...

#23080 0x00007faa7f6f3c31 in GDALDataset::BlockBasedRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23081 0x00007faa7f0765fe in MrSIDRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23082 0x00007faa7f63de9a in GDALDataset::BandBasedRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23083 0x00007faa7f6f3c31 in GDALDataset::BlockBasedRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23084 0x00007faa7f64182b in GDALDataset::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23085 0x00007faa7eadbab1 in VRTSimpleSource::DatasetRasterIO(GDALDataType, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23086 0x00007faa7eaee9b0 in VRTDataset::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23087 0x00007faa7f64182b in GDALDataset::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int*, long long, long long, long long, GDALRasterIOExtraArg*) () from /usr/local/lib/libgdal.so.35
#23088 0x00007faa7e8e57e4 in GDALWarpOperation::WarpRegionToBuffer(int, int, int, int, void*, GDALDataType, int, int, int, int, double, double, double, double) () from /usr/local/lib/libgdal.so.35
#23089 0x00007faa7e8e69b2 in GDALWarpOperation::WarpRegion(int, int, int, int, int, int, int, int, double, double, double, double) () from /usr/local/lib/libgdal.so.35
#23090 0x00007faa7e8e6d8d in GDALWarpOperation::ChunkAndWarpImage(int, int, int, int) () from /usr/local/lib/libgdal.so.35
#23091 0x00007faa7f7d6415 in GDALWarpDirect(char const*, void*, int, void**, GDALWarpAppOptions*, int*) () from /usr/local/lib/libgdal.so.35
#23092 0x00007faa7f7d7f84 in GDALWarp () from /usr/local/lib/libgdal.so.35
#23093 0x00007faa7ea50b80 in GDALCOGCreator::Create(char const*, GDALDataset*, char**, int (*)(double, char const*, void*), void*) () from /usr/local/lib/libgdal.so.35
#23094 0x00007faa7ea53a1d in COGCreateCopy(char const*, GDALDataset*, int, char**, int (*)(double, char const*, void*), void*) () from /usr/local/lib/libgdal.so.35
#23095 0x00007faa7f630594 in GDALDriver::CreateCopy(char const*, GDALDataset*, int, char const* const*, int (*)(double, char const*, void*), void*) () from /usr/local/lib/libgdal.so.35
#23096 0x00007faa7f7b92fc in GDALTranslate () from /usr/local/lib/libgdal.so.35
#23097 0x00005615c89710d6 in main ()
```

### Steps to reproduce the issue

1. Download a NAIP MrSID from Box: https://nrcs.app.box.com/v/naip/file/1365563970176 and unzip
2. Run the following command: `gdal_translate -tr 4.77 4.77 -b 1 -b 2 -b 3 -of COG -co COMPRESS=WEBP -co QUALITY=95 -co TILING_SCHEME=GoogleMapsCompatible -co ALIGNED_LEVELS=6 -co BIGTIFF=IF_SAFER -r bilinear ortho_1-1_hm_s_oh029_2023_1.sid ortho_1-1_hm_s_oh029_2023_1.tif`

### Versions and provenance

- I originally experienced the issue with GDAL 3.8.5, but still saw it after upgrading to 3.9.2
- GDAL compiled with MrSID_DSDK-9.5.5.5244-rhel9.x86-64.gcc1131
- Running in Debian 12 via Docker

**Comment by kmarsh** [comment]
@rouault Wow, thanks so much for the quick fix. I'll compile and have a go. Cheers!
