### ISSUE TITLE
DLL Load Failures in PyCharm for GDAL and Rasterio After Installing OpenCV in Micromamba Environment

### ISSUE THREAD

**Issue by mht2953658596** [OSGeo/gdal#10707]
### What is the bug?

I've been using Python with Conda but later installed Micromamba. Although Micromamba doesn't use the base environment, everything worked fine until I installed OpenCV in a Micromamba environment. During the installation, dependency conflicts occurred, and Micromamba started removing conflicting packages. However, when it tried to remove the GDAL package, it failed to delete the proj.db file, causing an error. I terminated the process and created a new environment in Micromamba to reinstall GDAL.

Now, I created a simple test script (test.py) with just one line:
`from osgeo import gdal`

Strangely, when I run the script directly from PyCharm, I get the following error:

```
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code_space\shendong-gee\celery_worker\test.py", line 1, in <module>
    from osgeo import gdal
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 35, in <module>
    _gdal = swig_import_helper()
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```

Additionally, when I try to import rasterio, I get this error:

```
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\celery_worker\test.py", line 1, in <module>
    import rasterio
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\rasterio\__init__.py", line 28, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: DLL load failed while importing _version: The specified module could not be found.
```

I noticed that any libraries requiring DLLs seem to fail with a "specified module could not be found" error.

Thinking Micromamba might be the issue, I switched to Pixi, but the same problem persists. However, the strangest part is that when I run the script directly from the command line using:

`D:\code_space\shendong-gee\.pixi\envs\default\python.EXE D:\code_space\shendong-gee\celery_worker\test.py`

it works perfectly fine. The issue only occurs when running the script from PyCharm.

When running the script from PyCharm, I expected it to execute without any errors, just as it does when running the script directly from the command line. Specifically, I expected:

The from osgeo import gdal line to execute successfully without any ImportError or ModuleNotFoundError.
The script to run without issues related to missing DLLs or modules.
Does anyone have any idea what might be causing this, or how I could resolve the issue?

### Steps to reproduce the issue

`from osgeo import gdal`

```
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code_space\shendong-gee\celery_worker\test.py", line 1, in <module>
    from osgeo import gdal
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 35, in <module>
    _gdal = swig_import_helper()
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal
```'


import rasterio


```
Traceback (most recent call last):
  File "D:\code_space\shendong-gee\celery_worker\test.py", line 1, in <module>
    import rasterio
  File "D:\code_space\shendong-gee\.pixi\envs\default\lib\site-packages\rasterio\__init__.py", line 28, in <module>
    from rasterio._version import gdal_version, get_geos_version, get_proj_version
ImportError: DLL load failed while importing _version: The specified module could not be found.
```




### Versions and provenance

windows11
python 3.10
gdal 3.6.2

### Additional context

_No response_

**Comment by rouault** [comment]
This doesn't look like a GDAL upstream bug, but a usage/integration one.
Make sure that the PATH under PyCharm contains a directory where gdal.dll and its dependencies are located.

**Comment by mht2953658596** [comment]
@rouault  Hello, I am a beginner and I'm not sure how to follow the setup instructions you mentioned. Could you please provide detailed steps? Also, why was everything working fine before, but now this problem has appeared?And do I need to reconfigure everything every time I switch virtual environments?

**Comment by rouault** [comment]
Sorry but I can't provide more help (I don't know PyCharm and hardly Windows) and the issue tracker is only for bugs. Maybe use GIS Stack Exchange or other support forums

I see also that you opened the same ticket in https://github.com/prefix-dev/pixi/issues/1953 . It is bad practice to open the same issue in different bug trackers, without at least cross referencing them.
