### ISSUE TITLE
gdal2tiles calling wrong member variable on TileJobInfo

### ISSUE THREAD

**Issue by psusmars** [OSGeo/gdal#1127]
## Expected behavior and actual behavior.

gdal2tiles.py appears to be calling a member variable that doesn't exist:
```
Traceback (most recent call last):
  File "/usr/bin/gdal2tiles.py", line 2927, in <module>
    main()
  File "/usr/bin/gdal2tiles.py", line 2921, in main
    single_threaded_tiling(input_file, output_folder, options)
  File "/usr/bin/gdal2tiles.py", line 2854, in single_threaded_tiling
    create_base_tile(conf, tile_detail)
  File "/usr/bin/gdal2tiles.py", line 995, in create_base_tile
    get_tile_swne(tile_job_info, options), tile_job_info.options
  File "/usr/bin/gdal2tiles.py", line 512, in generate_kml
    args['south'], args['west'], args['north'], args['east'] = tileswne(tx, ty, tz)
  File "/usr/bin/gdal2tiles.py", line 2818, in rastertileswne
    west = tile_job_info.out_geo_trans[0] + x * tile_job_info.tilesize * pixelsizex
AttributeError: 'TileJobInfo' object has no attribute 'tilesize'
```
It appears TileJobInfo has `tile_size` but not `tilesize`. Correcting the called attribute to the proper name generates the tiles. The following is what I changed (around 2816):
```
def rastertileswne(x, y, z):
                pixelsizex = (2 ** (tile_job_info.tmaxz - z) * tile_job_info.out_geo_trans[1])
                west = tile_job_info.out_geo_trans[0] + x * tile_job_info.tile_size * pixelsizex
                east = west + tile_job_info.tile_size * pixelsizex
                south = tile_job_info.ominy + y * tile_job_info.tile_size * pixelsizex
                north = south + tile_job_info.tile_size * pixelsizex
```
Included the image [foo_tiles_in.tif.zip](https://github.com/OSGeo/gdal/files/2631321/foo_tiles_in.tif.zip)

## Steps to reproduce the problem.

$ gdal2tiles.py -v -t tinynirgeotagged_StitchedNIR.kmz -p raster -k foo_tiles_in.tif

## Operating system

Ubuntu 14.04 64 bit

## GDAL version and provenance

2.3.2 - built from source with configuration: 
```
./configure --with-poppler=yes \
    --prefix=/usr \
    --with-geos --with-geotiff --with-jpeg --with-png --with-expat --with-libkml \
    --with-openjpeg --with-geos --with-pg \
    --with-curl \
    --with-spatialite \
    --with-python \
    --with-expat
```

**Comment by Sockenhans** [comment]
The renaming to 'tile_size' seems to brake the getUrl(bounds) function in gdal2tiles.py. 
When calling something like
_gdal2tiles --profile=mercator --s_srs=EPSG:3857 --zoom=15-20 <input.tif>_
the resulting Openlayers.html will only show the background map.
