### ISSUE TITLE
Installation on windows fails

### ISSUE THREAD

**Issue by AngRodrigues** [OSGeo/gdal#11483]
### What is the bug?

Apologies in advance if not a bug. 
The installation seems to be failing via conda on windows 11. 
I get an error about a libminizip.dll not found when running `gdalinfo --version`
![image](https://github.com/user-attachments/assets/5ceb4bb5-8e0b-4d15-85bc-4e6e1e1c86b9)

If I open python and import gdal, I get:
`from osgeo import gdal`

```
(test2) [redacted_path]>python
Python 3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:06:23) [MSC v.1942 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'gdal'
>>> from osgeo import gdal
Traceback (most recent call last):
  File "redacted_path\anaconda3\envs\test2\Lib\site-packages\osgeo\__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "redacted_path\anaconda3\envs\test2\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing _gdal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "redacted_path\anaconda3\envs\test2\Lib\site-packages\osgeo\__init__.py", line 35, in <module>
    _gdal = swig_import_helper()
            ^^^^^^^^^^^^^^^^^^^^
  File "redacted_path\anaconda3\envs\test2\Lib\site-packages\osgeo\__init__.py", line 32, in swig_import_helper
    return importlib.import_module('_gdal')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "redacted_path\anaconda3\envs\test2\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_gdal'
```

### Steps to reproduce the issue

```
conda create -n test2 python=3.11
conda activate test2
conda install -c conda-forge gdal
gdalinfo --version
````

### Versions and provenance

as above

**Comment by rouault** [comment]
@AngRodrigues Would you mind re-creating this issue at https://github.com/conda-forge/gdal-feedstock/issues ? This is rather where it belongs to

**Comment by AngRodrigues** [comment]
Sure thing, will do. 
Thanks for letting me know.
