### ISSUE TITLE
pytest 3.5 fails to run on OpenBSD

### ISSUE THREAD

**Issue by landryb** [OSGeo/gdal#1165]
The new pytest-based suite looks great, but unfortunately it fails to run for me be it with python2 or python3:
```
c64:/usr/obj/ports/gdal-2.4.0/gdal-2.4.0/autotest/ $python2 -m pytest                                                                                 
===================================================================== test session starts =====================================================================
platform openbsd6 -- Python 2.7.15, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /usr/obj/ports/gdal-2.4.0/gdalautotest-2.4.0, inifile: pytest.ini
collecting 6370 items                                                                                                                                         INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 107, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 144, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 154, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 354, in perform_collect
INTERNALERROR>     config=self.config, items=items)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 77, in get_result
INTERNALERROR>     _reraise(*ex)  # noqa
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/obj/ports/gdal-2.4.0/gdalautotest-2.4.0/conftest.py", line 59, in pytest_collection_modifyitems
INTERNALERROR>     for mark in item.iter_markers('require_driver'):
INTERNALERROR> AttributeError: 'Function' object has no attribute 'iter_markers'

================================================================ no tests ran in 10.19 seconds ================================================================
```

adding some debug prints, seems that `item` is indeed a function (i think it fails on the first it tries to run) and not an object, which doesnt have an `iter_markers()` method. Same thing if invoked as `py.test` of course, be it all tests or a single test file.

I'm not sure if this is due to the fact that some `require_driver` marks are not done as `@pytest.mark` decorators..

py-gdal & py3-gdal from 2.4.0 are installed systemwide before running the tests.

**Comment by landryb** [comment]
adding a return before the loop in `pytest_collection_modifyitems` at least allows py.test to start but that feels wrong.

**Comment by landryb** [comment]
Manually running a test requiring a missing driver (like `./gdrivers/bag.py`) fails in that case, but at least it doesnt blow the whole testsuite

**Comment by rouault** [comment]
From my quick testing, at least pytest 3.7.0 is required. @craigds We should probably update autotest/requirements.txt

**Comment by landryb** [comment]
right, that makes sense now. didnt realize 3.5 was a bit old...

**Comment by craigds** [comment]
It seems ok for me with 3.6.0, which seems in line with the docs ([iter_markers](https://docs.pytest.org/en/3.6.0/reference.html#_pytest.nodes.Node.iter_markers) is in 3.6.0)
