### ISSUE TITLE
Python does not raise an exception when opening a VRT with inaccessible tiles when SourceProperties tag exists

### ISSUE THREAD

**Issue by DanielFEvans** [OSGeo/gdal#1515]
## Expected behavior and actual behavior.

I have a VRT file which refers to some TIFF tiles on Linux. The directory structure is:
test.vrt
tiles/bogota.tif

The user can read test.vrt, but does not have read permissions on bogota.tif.

Using Python, if I simply import gdal and attempt to read a pixel, I get an error printed as expected:
```
>>> from osgeo import gdal
>>> ds = gdal.Open("test.vrt")
>>> band = ds.GetRasterBand(1)
>>> res = band.ReadAsArray(249, 250, 1, 1)
ERROR 4: tiles/bogota.tif: Permission denied
```

If I enable Python exceptions, I expect an exception to be raised. However, no such exception is raised, and nothing is printed to screen:
```
>>> from osgeo import gdal
>>> ds = gdal.Open("test.vrt")
>>> band = ds.GetRasterBand(1)
>>> gdal.UseExceptions()
>>> res = band.ReadAsArray(249, 250, 1, 1)
```

The only obvious hint is that the result is None, but that's not unexpected for some other failure modes:
```
>>> res is None
True
```

If I tried to open the unreadable tiff directly, I get an exception:
```
>>> from osgeo import gdal
>>> gdal.UseExceptions()
>>> ds = gdal.Open("tiles/bogota.tif")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: tiles/bogota.tif: Permission denied
```

(Edit: the odd VRT behaviour also applies if the underlying rasters the VRT refers to simply don't exist, so it's not specific to permissions-based errors)

(Edit 2: as noted in my comments below, some VRTs do raise an exception on opening. The SourceProperties tag in the VRT seems to be involved somehow.)

## Steps to reproduce the problem.
Make a test VRT:
```
$ wget https://download.osgeo.org/geotiff/samples/made_up/bogota.tif
$ mkdir tiles
$ cp bogota.tif tiles/
$ gdalbuildvrt test.vrt tiles/bogota.tif
```

Make the tile unreadable:
```
$ chmod -r tiles/bogota.tif
```

Run the following Python code:
```
>>> from osgeo import gdal
>>> ds = gdal.Open("test.vrt")
>>> band = ds.GetRasterBand(1)
>>> gdal.UseExceptions()
>>> res = band.ReadAsArray(249, 250, 1, 1)
```

No exception is raised.

## Operating system

Scientific Linux 64-bit (have not tested behaviour on Windows, but expect similar).

## GDAL version and provenance

GDAL 2.2.0 built locally from source.

**Comment by DanielFEvans** [comment]
This seems to be more subtle than it first appears. The very first test in the VRT test suite tests this behaviour - in it, a VRT should fail to open if the underlying tiles do not exist.

https://github.com/OSGeo/gdal/blob/8528a635e815557ca4a7d26054602f0fe22cc408/autotest/gcore/vrt_read.py

And if I download and attempt to open the test data "idontexist.vrt", it does indeed print an error or raise an exception (as appropriate) on trying to open the VRT, explicitly stating which tile could not be opened. I don't get the same behaviour when opening the VRT I created. Even if I modify "idontexist.vrt" to point to the same (unreadable) bogota.tif, I still get an explicit error/exception.

**Comment by DanielFEvans** [comment]
It appears that the difference is the existence of a `SourceProperties` tag in the VRT I created. If I remove this line from the VRT, it behaves as expected:

```
>>> from osgeo import gdal
>>> gdal.UseExceptions()
>>> ds = gdal.Open("test.vrt")
>>> ds = gdal.Open("test_no_properties.vrt")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: tiles/bogota.tif: Permission denied
```
