### ISSUE TITLE
UnboundLocalError Python exception with gdal_polygonize without '-f' option

### ISSUE THREAD

**Issue by grizonnetm** [OSGeo/gdal#1533]
I try to directly write geojson vector as output of the gdal_polygonize Python utility.

The documentation of gdal_polygonize.py states that without '-f' option the format is guessed from the extension.

In case the output vector file extension is .geojson there is a not that clear Python exception related to local variable referenced before assigment.

Note that the format guess works with other formats like .gpkg or .shp and that adding the option '-f geojson' solves the issue.

## Expected behavior and actual behavior.

The exception triggered by gdal_polygonize:

```
Traceback (most recent call last):
  File "/usr/bin/gdal_polygonize.py", line 163, in <module>
    frmt = GetOutputDriverFor(dst_filename)
  File "/usr/bin/gdal_polygonize.py", line 87, in GetOutputDriverFor
    print("Several drivers matching %s extension. Using %s" % (ext, drv_list[0]))
UnboundLocalError: local variable 'ext' referenced before assignment
```

## Steps to reproduce the problem.

gdal_polygonize.py input_raster.tif output_vector.geojson

## Operating system

Ubuntu 18.04 64 bits

## GDAL version and provenance

gdal master branch (commit Id 9b2c3e7057c4) build using the dockerfile provided inside the source tree.

**Comment by grizonnetm** [comment]
Thanks a lot @rouault !
