### ISSUE TITLE
Gdal 2.3.3 Cannot open file from Minio Object Storage server using /vsis3/

### ISSUE THREAD

**Issue by Giangblackk** [OSGeo/gdal#1609]
## Expected behavior and actual behavior.
I am trying to use gdal to open a geotiff file from my own Minio object storage server (s3 compatible) using /vsis3/, here is the code:

```python
from osgeo import gdal
import numpy as np

gdal.UseExceptions()

gdal.SetConfigOption('AWS_REGION', 'us-east-1')
gdal.SetConfigOption('AWS_SECRET_ACCESS_KEY', 'secret_key')
gdal.SetConfigOption('AWS_ACCESS_KEY_ID', 'access_key')

path = '/vsis3/bucket/image.tif'
ds = gdal.Open(path)

band = ds.GetRasterBand(1)

xoff, yoff, xcount, ycount = (0, 0, 10, 10)
np_array = band.ReadAsArray(xoff, yoff, xcount, ycount)
```

The error is:
```python-traceback
Traceback (most recent call last):
  File "gdal_minio.py", line 17, in <module>
    ds = gdal.Open(path)
  File "/usr/python/lib/python3.6/site-packages/osgeo/gdal.py", line 3087, in Open
    return _gdal.Open(*args)
RuntimeError: Cannot open file '/vsis3/bucket/image.tif/product.xml'
```

Why does gdal's api search for a `product.xml` file?
Is there anything I missing from how to use gdal /vsis3/?

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

the 2.3.3 version from anaconda official channel

**Comment by rouault** [comment]
You likely also need to set the AWS_S3_ENDPOINT config option to point to your Minio endpoint :
https://gdal.org/user/virtual_file_systems.html#vsis3-streaming-aws-s3-files-streaming
And if you want to limit the number of auxiliary files to be probed, you must define GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR and CPL_VSIL_CURL_ALLOWED_EXTENSIONS=tif

**Comment by Giangblackk** [comment]
@rouault I forgot to mention that I've already set the AWS_S3_ENDPOINT config option in my .bashrc file.
Here is the update code, and it's still had error, even though my geotiff image is totally normal.

Please reopen the issue.

```python
from osgeo import gdal
import numpy as np

gdal.UseExceptions()

# These only need to be set if they're not already in the environment,
# ~/.aws/config, or you're running on an EC2 instance with an IAM role.
gdal.SetConfigOption('AWS_REGION', 'us-east-1')
gdal.SetConfigOption('AWS_SECRET_ACCESS_KEY', 'secret_key')
gdal.SetConfigOption('AWS_ACCESS_KEY_ID', 'access_key')
gdal.SetConfigOption('ASW_S3_ENDPOINT', 'localhost:9000')
gdal.SetConfigOption('AWS_HTTPS', 'NO')
gdal.SetConfigOption('CPL_VSIL_CURL_ALLOWED_EXTENSIONS', '.tif')
gdal.SetConfigOption('GDAL_DISABLE_READDIR_ON_OPEN', 'YES')

# 'sentinel-pds' is the S3 bucket name
path = '/vsis3/bucket/image.tif'
ds = gdal.Open(path)

band = ds.GetRasterBand(1)

xoff, yoff, xcount, ycount = (0, 0, 10, 10)
np_array = band.ReadAsArray(xoff, yoff, xcount, ycount)
```

The error now is:
```python-traceback
Traceback (most recent call last):
  File "gdal_minio.py", line 21, in <module>
    ds = gdal.Open(path)
  File "/usr/python/lib/python3.6/site-packages/osgeo/gdal.py", line 3087, in Open
    return _gdal.Open(*args)
RuntimeError: `/vsis3/bucket/image.tif' not recognized as a supported file format.
```

**Comment by rcoup** [comment]
@Giangblackk can you run with `CPL_CURL_VERBOSE=YES` & `CPL_DEBUG=YES` environment variables set? (check for & `*****` any access keys/etc that are logged)

**Comment by Giangblackk** [comment]
@rouault 
Here is the updated code:
```python
from osgeo import gdal
import numpy as np

gdal.UseExceptions()

# These only need to be set if they're not already in the environment,
# ~/.aws/config, or you're running on an EC2 instance with an IAM role.
gdal.SetConfigOption('CPL_CURL_VERBOSE', 'YES')
gdal.SetConfigOption('CPL_DEBUG', 'YES')
gdal.SetConfigOption('AWS_REGION', 'us-east-1')
gdal.SetConfigOption('AWS_SECRET_ACCESS_KEY', '**********')
gdal.SetConfigOption('AWS_ACCESS_KEY_ID', '**********')
gdal.SetConfigOption('ASW_S3_ENDPOINT', 'localhost:9000')
gdal.SetConfigOption('AWS_HTTPS', 'NO')
gdal.SetConfigOption('GDAL_DISABLE_READDIR_ON_OPEN', 'YES')
gdal.SetConfigOption('CPL_VSIL_CURL_ALLOWED_EXTENSIONS', '.tif')

# 'sentinel-pds' is the S3 bucket name
path = '/vsis3/bucket/image.tif'
ds = gdal.Open(path)

band = ds.GetRasterBand(1)

xoff, yoff, xcount, ycount = (0, 0, 10, 10)
np_array = band.ReadAsArray(xoff, yoff, xcount, ycount)
```
And Here is the output:
```python-traceback
* Expire in 0 ms for 6 (transfer 0x56107b6ecc80)
* Couldn't find host bucket.s3.amazonaws.com in the .netrc file; using defaults
* Expire in 1 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 0 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 1 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 0 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 0 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 2 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 50 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 50 ms for 1 (transfer 0x56107b6ecc80)
* Expire in 50 ms for 1 (transfer 0x56107b6ecc80)
*   Trying 52.217.1.156...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x56107b6ecc80)
* Connected to bucket.s3.amazonaws.com (52.217.1.156) port 80 (#0)
> GET /image.tif HTTP/1.1
Host: bucket.s3.amazonaws.com
Accept: */*
Range: bytes=0-16383
x-amz-date: 20190603T092140Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=**********/20190603/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=438addd5fbbc1dc1c40f35fef5223bdd810dd5beaffd149ded486c77e93b59c0

< HTTP/1.1 403 Forbidden
< x-amz-request-id: F0CA031910097A6D
< x-amz-id-2: hS60ZN9gvK/wuTTDkEAR58UQuGUZB3A9ALdbwl1K0Tn/GhLG/pgUWmikp7OVgmL4vpHuhWxlk2Y=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 03 Jun 2019 09:21:40 GMT
< Server: AmazonS3
< 
* Connection #0 to host bucket.s3.amazonaws.com left intact
* Expire in 0 ms for 6 (transfer 0x56107b6ecc80)
* Couldn't find host bucket.s3.amazonaws.com in the .netrc file; using defaults
* Found bundle for host bucket.s3.amazonaws.com: 0x56107b6db2e0 [can pipeline]
* Re-using existing connection! (#0) with host bucket.s3.amazonaws.com
* Connected to bucket.s3.amazonaws.com (52.217.1.156) port 80 (#0)
* Expire in 0 ms for 6 (transfer 0x56107b6ecc80)
> GET /?delimiter=%2F&max-keys=1&prefix=image.tif%2F HTTP/1.1
Host: bucket.s3.amazonaws.com
Accept: */*
x-amz-date: 20190603T092141Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=**********/20190603/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=21e5682d08ce1217eb44e49ed931f3b485cbbaead51a85af5e11c192ff2235b5

< HTTP/1.1 403 Forbidden
< x-amz-bucket-region: us-east-1
< x-amz-request-id: E811040043D2D7BB
< x-amz-id-2: jPfQeDAa/z77n6ghc0G1peFRtR5RIh6F8VF/a33GhqP0CWb6BwlK3I5Kd0/AQrI3wlNvnPAR37s=
< Content-Type: application/xml
< Transfer-Encoding: chunked
< Date: Mon, 03 Jun 2019 09:21:41 GMT
< Server: AmazonS3
< 
* Connection #0 to host bucket.s3.amazonaws.com left intact
Traceback (most recent call last):
  File "gdal_minio.py", line 23, in <module>
    ds = gdal.Open(path)
  File "/usr/python/lib/python3.6/site-packages/osgeo/gdal.py", line 3087, in Open
    return _gdal.Open(*args)
RuntimeError: `/vsis3/bucket/image.tif' not recognized as a supported file format.
```
For more information, I also tried to use `gdalinfo`, here is the command and output:
```bash
$ gdalinfo --config AWS_S3_ENDPOINT "localhost:9000" --config AWS_REGION "us-east-1" --config AWS_SECRET_ACCESS_KEY "**********" --config AWS_ACCESS_KEY_ID "**********" --config AWS_HTTPS "NO" --config GDAL_DISABLE_READDIR_ON_OPEN "YES" --config CPL_VSIL_CURL_ALLOWED_EXTENSIONS ".tif"  --config CPL_CURL_VERBOSE "YES" --config CPL_DEBUG "YES"   /vsis3/bucket/image.tif
```
The output:
```
* Expire in 0 ms for 6 (transfer 0x55c89b1d38d0)
* Couldn't find host bucket.localhost in the .netrc file; using defaults
* Expire in 1 ms for 1 (transfer 0x55c89b1d38d0)
* Expire in 0 ms for 1 (transfer 0x55c89b1d38d0)
* Expire in 1 ms for 1 (transfer 0x55c89b1d38d0)
* Expire in 0 ms for 1 (transfer 0x55c89b1d38d0)
* Expire in 0 ms for 1 (transfer 0x55c89b1d38d0)
* Expire in 50 ms for 1 (transfer 0x55c89b1d38d0)
*   Trying ::1...
* TCP_NODELAY set
* Expire in 149949 ms for 3 (transfer 0x55c89b1d38d0)
* Expire in 200 ms for 4 (transfer 0x55c89b1d38d0)
* Connected to bucket.localhost (::1) port 9000 (#0)
> GET /image.tif HTTP/1.1
Host: bucket.localhost:9000
Accept: */*
Range: bytes=0-16383
x-amz-date: 20190603T093121Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=**********/20190603/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=41f23fe94352e459e94f7add69582d437aa0af4901853bee6d24a7b27a9e335f

< HTTP/1.1 404 Not Found
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/RELEASE.2019-05-23T00-29-34Z
< Vary: Origin
< X-Amz-Request-Id: 15A4A65B37DD91F2
< X-Minio-Deployment-Id: 6ba6b52b-3ffe-49ed-b929-2371d1e461a4
< X-Xss-Protection: 1; mode=block
< Date: Mon, 03 Jun 2019 09:31:21 GMT
< Transfer-Encoding: chunked
< 
* Connection #0 to host bucket.localhost left intact
* Expire in 0 ms for 6 (transfer 0x55c89b1d38d0)
* Couldn't find host bucket.localhost in the .netrc file; using defaults
* Found bundle for host bucket.localhost: 0x55c89b1ca960 [can pipeline]
* Re-using existing connection! (#0) with host bucket.localhost
* Connected to bucket.localhost (::1) port 9000 (#0)
* Expire in 0 ms for 6 (transfer 0x55c89b1d38d0)
> GET /?delimiter=%2F&max-keys=1&prefix=image.tif%2F HTTP/1.1
Host: bucket.localhost:9000
Accept: */*
x-amz-date: 20190603T093121Z
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=**********/20190603/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=b4a05274084e0e61c997743909f529502e32bff1accb7a33299523772f50fce0

< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Content-Security-Policy: block-all-mixed-content
< Content-Type: application/xml
< Server: MinIO/RELEASE.2019-05-23T00-29-34Z
< Vary: Origin
< X-Amz-Request-Id: 15A4A65B38013CA7
< X-Minio-Deployment-Id: 6ba6b52b-3ffe-49ed-b929-2371d1e461a4
< X-Xss-Protection: 1; mode=block
< Date: Mon, 03 Jun 2019 09:31:21 GMT
< Transfer-Encoding: chunked
< 
* Connection #0 to host bucket.localhost left intact
ERROR 4: `/vsis3/bucket/image.tif' not recognized as a supported file format.
gdalinfo failed - unable to open '/vsis3/bucket/image.tif'.

```

**Comment by Giangblackk** [comment]
@rouault After I read the output of the code and the command, I found out that the error came from 2 things:
- A typo `ASW_S3_ENDPOINT` instead of `AWS_S3_ENDPOINT`
- I need to add `AWS_VIRTUAL_HOSTING=FALSE` to prevent `gdal` for searching a subdomain `bucket.localhost:9000`

It works now! Thank you very much for your support.

I leave the code that works here for reference:
```python
import os

from osgeo import gdal
import numpy as np

gdal.SetConfigOption('AWS_HTTPS', 'NO')
gdal.SetConfigOption('GDAL_DISABLE_READDIR_ON_OPEN', 'YES')
gdal.SetConfigOption('AWS_VIRTUAL_HOSTING', 'FALSE')

# configs for enabling debugging mode
# gdal.UseExceptions()
# gdal.SetConfigOption('CPL_CURL_VERBOSE', 'YES')
# gdal.SetConfigOption('CPL_DEBUG', 'YES')

gdal.SetConfigOption('AWS_S3_ENDPOINT', 'localhost:9000')
gdal.SetConfigOption('AWS_SECRET_ACCESS_KEY', '**********')
gdal.SetConfigOption('AWS_ACCESS_KEY_ID', '**********')

# unnecessary configs
# gdal.SetConfigOption('AWS_REGION', 'us-east-1')
# gdal.SetConfigOption('CPL_VSIL_CURL_ALLOWED_EXTENSIONS', '.tif')

path = '/vsis3/bucket/image.tif'
ds = gdal.Open(path)

band = ds.GetRasterBand(1)

xoff, yoff, xcount, ycount = (0, 0, 10, 10)
np_array = band.ReadAsArray(xoff, yoff, xcount, ycount)
```
