### ISSUE TITLE
GDAL hides S3 denial of access when `GDAL_DISABLE_READDIR_ON_OPEN=YES`

### ISSUE THREAD

**Issue by sgillies** [OSGeo/gdal#1900]
In the absence of `GDAL_DISABLE_READDIR_ON_OPEN=YES` GDAL will attempt to get a bucket/prefix listing and when not authenticated will set an "Access Denied" error. This is a clear error, because authentication is the thing a developer can address in code.

In the case of  `GDAL_DISABLE_READDIR_ON_OPEN=YES` GDAL does not attempt a listing and goes directly to the file of interest or its auxiliary files. GDAL gets a 403 (unauthenticated) response from AWS but continues after logging it at a low severity level and ends by setting a more obscure "Open Failed" error.

Here's an example from rasterio https://github.com/mapbox/rasterio/issues/1706:

```
DISABLE_READDIR_ON_OPEN=YES rio -vvv info s3://sentinel-s2-l1c/non_existing.tif                                                                  
DEBUG:rasterio.env:Entering env context: <rasterio.env.Env object at 0x7f7ec2b8deb8>                                                                                                                               
DEBUG:rasterio.env:Starting outermost env                                                                                                                                                                          
DEBUG:rasterio.env:No GDAL environment exists                                                                                                                                                                      
DEBUG:rasterio.env:New GDAL environment <rasterio._env.GDALEnv object at 0x7f7ec2b8df28> created                                                                                                                   
DEBUG:rasterio._env:GDAL_DATA found in environment: '/home/sean/local/share/gdal'.                                                                                                                                 
DEBUG:rasterio._env:PROJ_LIB found in environment: '/home/sean/local/share/proj'.                                                                                                                                  
DEBUG:rasterio._env:Started GDALEnv <rasterio._env.GDALEnv object at 0x7f7ec2b8df28>.                                                                                                                              
DEBUG:rasterio.env:Entered env context: <rasterio.env.Env object at 0x7f7ec2b8deb8>                                                                                                                                
DEBUG:rasterio.env:Got a copy of environment <rasterio._env.GDALEnv object at 0x7f7ec2b8df28> options                                                                                                              
DEBUG:botocore.hooks:Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane                                                                                               
DEBUG:botocore.hooks:Changing event name from before-call.apigateway to before-call.api-gateway                                                                                                                    
DEBUG:botocore.hooks:Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict                                                                                  
DEBUG:botocore.hooks:Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration                                        
DEBUG:botocore.hooks:Changing event name from before-parameter-build.route53 to before-parameter-build.route-53                                                                                                    
DEBUG:botocore.hooks:Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search                                                                                
DEBUG:botocore.hooks:Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section                                      
DEBUG:botocore.hooks:Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask                                                              
DEBUG:botocore.hooks:Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section                                                            
DEBUG:botocore.hooks:Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search                                                                  
DEBUG:botocore.hooks:Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section                                                                
DEBUG:botocore.credentials:Looking for credentials via: env                                                                                                                                                        
DEBUG:botocore.credentials:Looking for credentials via: assume-role                                                                                                                                                
DEBUG:botocore.credentials:Looking for credentials via: shared-credentials-file                                                                                                                                    
INFO:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials                                                                                                                         
DEBUG:rasterio.env:Entering env context: <rasterio.env.Env object at 0x7f7ec2b60710>                                                                                                                               
DEBUG:rasterio.env:Got a copy of environment <rasterio._env.GDALEnv object at 0x7f7ec2b8df28> options                                                                                                              
DEBUG:rasterio.env:Entered env context: <rasterio.env.Env object at 0x7f7ec2b60710>                                                                                                                                
DEBUG:rasterio._base:Sharing flag: 0                                                                                                                                                                               
DEBUG:rasterio._env:CPLE_None in HTTP: libcurl/7.58.0 GnuTLS/3.5.18 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3                                                            
DEBUG:rasterio._env:CPLE_None in VSICURL: Downloading 0-16383 (https://sentinel-s2-l1c.s3.amazonaws.com/non_existing.tif)...                                                                                       
DEBUG:rasterio._env:CPLE_None in VSICURL: Got response_code=400                                                                                                                                                    
DEBUG:rasterio._env:CPLE_None in S3: Switching to region eu-central-1                                                                                                                                              
DEBUG:rasterio._env:CPLE_None in VSICURL: Downloading 0-16383 (https://sentinel-s2-l1c.s3.amazonaws.com/non_existing.tif)...                                                                                       
DEBUG:rasterio._env:CPLE_None in VSICURL: Got response_code=403                                                                                                                                                    
DEBUG:rasterio._env:CPLE_None in S3: <?xml version="1.0" encoding="UTF-8"?>                                                                                                                                        
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>8EF483C224F9A85B</RequestId><HostId>uEcJeyBCf6g7WDvR9FoXU/z+h3guVpwM2nLkZ3FHPRrSASqyDPUaOKOfFxZhlQWEVXJPZatyYSU=</HostId></Error>       
WARNING:rasterio._env:CPLE_AppDefined in HTTP response code on https://sentinel-s2-l1c.s3.amazonaws.com/non_existing.tif.xml: 403                                                                                  
DEBUG:rasterio._env:CPLE_None in VSICURL: GetFileSize(https://sentinel-s2-l1c.s3.amazonaws.com/non_existing.tif.xml)=0  response_code=403                                                                          
DEBUG:rasterio._env:CPLE_None in S3: <?xml version="1.0" encoding="UTF-8"?>                                                                                                                                        
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>B6E759E8420C1857</RequestId><HostId>V2PrmB2nzBIjSO2/g+k5WAppLww1rtSdX88GN/OD9sbq2cZv5PqEo55dQiMI03MKX38OTf86Y2o=</HostId></Error>       
DEBUG:rasterio.env:Exiting env context: <rasterio.env.Env object at 0x7f7ec2b60710>
DEBUG:rasterio.env:Cleared existing <rasterio._env.GDALEnv object at 0x7f7ec2b8df28> options
DEBUG:rasterio._env:Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f7ec2b8df28>.
DEBUG:rasterio.env:No GDAL environment exists
DEBUG:rasterio.env:New GDAL environment <rasterio._env.GDALEnv object at 0x7f7ec2b8df28> created
DEBUG:rasterio._env:GDAL_DATA found in environment: '/home/sean/local/share/gdal'.
DEBUG:rasterio._env:PROJ_LIB found in environment: '/home/sean/local/share/proj'.
DEBUG:rasterio._env:Started GDALEnv <rasterio._env.GDALEnv object at 0x7f7ec2b8df28>.
DEBUG:rasterio.env:Exited env context: <rasterio.env.Env object at 0x7f7ec2b60710>
DEBUG:rasterio.env:Exiting env context: <rasterio.env.Env object at 0x7f7ec2b8deb8>
DEBUG:rasterio.env:Cleared existing <rasterio._env.GDALEnv object at 0x7f7ec2b8df28> options
DEBUG:rasterio._env:Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7f7ec2b8df28>.
DEBUG:rasterio.env:Exiting outermost env
DEBUG:rasterio.env:Exited env context: <rasterio.env.Env object at 0x7f7ec2b8deb8>
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 216, in rasterio._base.DatasetBase.__init__
    self._hds = open_dataset(filename, flags, driver, kwargs, None)
  File "rasterio/_shim.pyx", line 77, in rasterio._shim.open_dataset
    return exc_wrap_pointer(hds)
  File "rasterio/_err.pyx", line 205, in rasterio._err.exc_wrap_pointer
    raise exc
rasterio._err.CPLE_OpenFailedError: '/vsis3/sentinel-s2-l1c/non_existing.tif' not recognized as a supported file format.
```

I think it would be better for developers if the "Access Denied" error from AWS was propagated in the case of `GDAL_DISABLE_READDIR_ON_OPEN=YES`.

**Comment by rouault** [comment]
> What do you think @rouault?

Ideally we should get the Access Denied error even in GDAL_DISABLE_READDIR_ON_OPEN=YES case. Something somewhere must clear the initial VSIError.

**Comment by j08lue** [comment]
@sgillies - in the first line of your issue description, the flag should be `FALSE`, right?

**Comment by ungarj** [comment]
@rouault you are amaizing, thanks!
