### ISSUE TITLE
pip install gdal failing on macOS

### ISSUE THREAD

**Issue by dstansby** [OSGeo/gdal#2166]
## Expected behavior and actual behavior.

As of the new release (3.0.3), `pip install gdal` is failing for me. Error is
```python
$ pip install gdal
Collecting gdal
  Downloading https://files.pythonhosted.org/packages/77/99/adf9183a8cd02a3a4b7b35d6d3c14be1fd133801d7a2f8cc6f296f7584df/GDAL-3.0.3.tar.gz (577kB)
     |████████████████████████████████| 583kB 155kB/s 
    ERROR: Command errored out with exit status 1:
     command: /Users/dstansby/miniconda3/envs/dev/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py'"'"'; __file__='"'"'/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/pip-egg-info
         cwd: /private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/
    Complete output (72 lines):
    running egg_info
    creating /private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/pip-egg-info/GDAL.egg-info
    writing /private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/pip-egg-info/GDAL.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/pip-egg-info/GDAL.egg-info/dependency_links.txt
    writing top-level names to /private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/pip-egg-info/GDAL.egg-info/top_level.txt
    writing manifest file '/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/pip-egg-info/GDAL.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 151, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config': '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 249, in get_gdal_config
        return fetch_config(option, gdal_config=self.gdal_config)
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 154, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config': '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 151, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/subprocess.py", line 800, in __init__
        restore_signals, start_new_session)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/subprocess.py", line 1551, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config': 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 450, in <module>
        setup(**setup_kwargs)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Users/dstansby/miniconda3/envs/dev/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 311, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 255, in get_gdal_config
        return fetch_config(option)
      File "/private/var/folders/3j/f7vtq4q1397bxjn19wftn_fm0000gn/T/pip-install-fpjeo49t/gdal/setup.py", line 154, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config': 'gdal-config'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## Steps to reproduce the problem.
`pip install gdal`

## Operating system

macOS 10.15.2

## GDAL version and provenance

3.0.3 from pypi

**Comment by rouault** [comment]
"pip install gdal" requires to have the GDAL native library and its development headers to build the Python extension module

**Comment by dstansby** [comment]
Would it be possible to print a better error message to that effect when `pip install` fails?

**Comment by rouault** [comment]
Hopefully d718f736ab06f40d5d44ba238a2d11c782929bd5 should make it more obvious

**Comment by Cadair** [comment]
Would it be possible to distribute binary wheels with the c-lib included or are there technical / licencing issues with that?

**Comment by rouault** [comment]
> Would it be possible to distribute binary wheels with the c-lib included or are there technical / licencing issues with that?

Mostly a matter of people stepping up to do it. One issue with binary wheels though is that you need to decide which GDAL dependency libraries you want to depend on (which can have licensing impacts on the final build, depending on which depedency you add). Rasterio does provide GDAL binary wheels with https://github.com/rasterio/rasterio-wheels if I'm right

**Comment by dstansby** [comment]
> Hopefully [d718f73](https://github.com/OSGeo/gdal/commit/d718f736ab06f40d5d44ba238a2d11c782929bd5) should make it more obvious

Thanks!

**Comment by AndreasLuckert** [comment]
> "pip install gdal" requires to have the GDAL native library and its development headers to build the Python extension module

As I still get errors upon installing GDAL even when having installed all its libraries and headers, I don't know how to resolve this problem.
I put [more details on that](https://github.com/OSGeo/gdal/issues/2827#issuecomment-668076763)  into the thread of my own question.
Hopefully, someone will provide an answer on how to exactly overcome this issue.

**Comment by AndreasLuckert** [comment]
The solution was finally (thanks to @rouault ):

> Pin the version of the bindings that match your native lib: `pip install gdal==2.2.3`

After installing via employing `sudo apt install libgdal-dev`, it is necessary to check the header version:

```
andylu@andylu-ThinkPad-Edge-E130:~/Desktop/Python/Scripts$
gdal-config --version
2.2.3
```

With this, it follows:

```
andylu@andylu-ThinkPad-Edge-E130:~$ pip install gdal==2.2.3
Collecting gdal==2.2.3
  Downloading GDAL-2.2.3.tar.gz (475 kB)
     |████████████████████████████████| 475 kB 1.8 MB/s 
Building wheels for collected packages: gdal
  Building wheel for gdal (setup.py) ... done
  Created wheel for gdal: filename=GDAL-2.2.3-cp38-cp38-linux_x86_64.whl size=2227987 sha256=0c21e35be8365cb856aac0b2e1d9d9494f1019cc425bf06e9d151bdd291c80a1
  Stored in directory: /home/andylu/.cache/pip/wheels/1c/d8/22/8ce120929fb3c2556f2f4da51643caff3346beff30233b9248
Successfully built gdal
Installing collected packages: gdal
Successfully installed gdal-2.2.3
```

**Comment by gitanupam** [comment]
On MacOS, [this solution](https://stackoverflow.com/a/55717357/1526703) worked fine for me:

**Summary**: instead of `pip`, just use `brew` to install gdal
