### ISSUE TITLE
GDAL Python Error: in method 'SpatialReference_AutoIdentifyEPSG', argument 1 of type 'OSRSpatialReferenceShadow *

### ISSUE THREAD

**Issue by palmerj** [OSGeo/gdal#2303]
## Expected behavior and actual behavior.

When calling AutoIdentifyEPSG() on a osr.SpatialReference that isn't valid I get the following error:

```
TypeError: in method 'SpatialReference_AutoIdentifyEPSG', argument 1 of type 'OSRSpatialReferenceShadow *'
```

I can even call Validate() on the srs object, because it has not OSRSpatialReferenceShadow internal pointer.

When I turn on gdal.UserExceptions still no error is thrown. 

## Steps to reproduce the problem.

test.py:
```python
from osgeo import osr

class EpsgIDNotFound(Exception):
    pass

def get_epsg_srs(srs_wkt: str) -> osr.SpatialReference:
    """ Given a WKT proj string get the SRS object which matches an authoritative EPSG code """
    out_srs = osr.SpatialReference()
    srs = osr.SpatialReference(srs_wkt)
    res = srs.AutoIdentifyEPSG()
    if res == 0:
        epsg_id = int(srs.GetAuthorityCode(None))
        assert epsg_id is not None
        out_srs.ImportFromEPSG(epsg_id)
    else:
        matches = srs.FindMatches()
        if len(matches) == 1 and matches[0][1] >= 90:
            out_srs = matches[0][0]
        else:
            raise EpsgIDNotFound(
                "Authoritative EPSG ID could not be found for %s. Potential candidate match count %d" % (srs_wkt, len(matches))
            )
    return out_srs


bad_wkt = """
    PROJCS["FOOBAR",
        GEOGCS["NZGD2000",
            DATUM["FOOBAR",
                SPHEROID["GRS 1980",6378137,298.257222101,
                    AUTHORITY["EPSG","7019"]],
                TOWGS84[0,0,0,0,0,0,0],
            PRIMEM["Greenwich",0,
                AUTHORITY["EPSG","8901"]],
            UNIT["degree",0.0174532925199433,
                AUTHORITY["EPSG","9122"]],
            AUTHORITY["EPSG","4167"]],
        PROJECTION["Transverse_Mercator"],
        PARAMETER["latitude_of_origin",0],
        PARAMETER["central_meridian",173],
        PARAMETER["scale_factor",0.9996],
        PARAMETER["false_easting",1600000],
        PARAMETER["false_northing",10000000],
        UNIT["metre",1,
            AUTHORITY["EPSG","9001"]],
        AUTHORITY["EPSG","2193"]]
"""
test_srs = get_epsg_srs(bad_wkt)
```

python test.py:
```
Traceback (most recent call last):
  File "data_lake/core/utils/geom.py", line 52, in <module>
    test_srs = get_epsg_srs(bad_wkt)
  File "data_lake/core/utils/geom.py", line 14, in get_epsg_srs
    res = srs.AutoIdentifyEPSG()
  File "/Users/jpalmer/Documents/Development/linz-data-lake/.venv/lib/python3.7/site-packages/GDAL-2.4.2-py3.7-macosx-10.15-x86_64.egg/osgeo/osr.py", line 808, in AutoIdentifyEPSG
    return _osr.SpatialReference_AutoIdentifyEPSG(self, *args)
TypeError: in method 'SpatialReference_AutoIdentifyEPSG', argument 1 of type 'OSRSpatialReferenceShadow *'
```

## Operating system

MacOSX 10.15.3

## GDAL version and provenance

GDAL 2.4.2

**Comment by rouault** [comment]
What would you expect in default mode when no exceptions are thrown ?
In ogr.UseExceptions() mode, I see that in master, an exception is now thrown on `srs = osr.SpatialReference(srs_wkt)` whereas it was not thrown indeed in 2.4

**Comment by palmerj** [comment]
Having an exception thrown or a gdal error set and the object is None?

**Comment by palmerj** [comment]
Hi @rouault I've just tested this improvement but have a few issues with the upgrade from 2.4 to 3.X. 

Under 2.4 this projection string found a match level of 100, but under GDAL master it returns 25 (however, still finding the correct EPSG SRID). 

```python
missing_epsg_matches_wkt = """
PROJCS["NZGD2000_New_Zealand_Transverse_Mercator_2000",
GEOGCS["GCS_NZGD2000",
    DATUM["New_Zealand_Geodetic_Datum_2000",
        SPHEROID["GRS 1980",6378137,298.2572221010042,
            AUTHORITY["EPSG","7019"]],
        AUTHORITY["EPSG","6167"]],
    PRIMEM["Greenwich",0],
    UNIT["degree",0.0174532925199433]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",173],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",1600000],
    PARAMETER["false_northing",10000000],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]
]
"""
srs = osr.SpatialReference(missing_epsg_matches_wkt)
srs.AutoIdentifyEPSG()
print srs.FindMatches()[0][1]
```

**Comment by rouault** [comment]
@palmerj  See https://github.com/OSGeo/PROJ/pull/2053 for a fix for this EPSG:2193 identification. The appropriate new confidence level should be 90% according to the new levels defined by PROJ 6

**Comment by palmerj** [comment]
Thanks @rouault. As always, an amazing response.
