### ISSUE TITLE
gdal 3.0.1 Python API return None for scale=1.0 and offset=0.0 even if explicitly written

### ISSUE THREAD

**Issue by cpaulik** [OSGeo/gdal#2579]
## Expected behavior and actual behavior.

We have been writing GeoTiff files with scale factor 1.0 and offset 0.0 as the default to make sure we always have a value for them. But with gdal 3.1.0 the Python API started returning `None` for both scale and offset even for files when these values are explicitly set. During this investigation I also checked the output of `gdalinfo` for the files with scale `1.0` and offset `0.0` and they do not show up.

I would expect to be able to write these values even though they don't make a difference in how the data is interpreted. That would seem more consistent than ignoring them and then returning `None` when reading the file.

## Steps to reproduce the problem.

The following script:

```python
from osgeo import gdal
from osgeo import osr
import numpy as np
from osgeo import gdal_array

geo_transform = (0, 1, 0, 0, 0, 1)

scales = [1.0, 2.0, None]
offsets = [0.0, 0.5, None]

for scale, offset in zip(scales, offsets):

    file_name = 'test_scale_{}_offset{}.tif'.format(scale, offset)
    cols = 3
    rows = 3
    driver = gdal.GetDriverByName("GTiff")
    ds = driver.Create(file_name, cols, rows)
    ds.SetGeoTransform(geo_transform)
    srs = osr.SpatialReference()
    srs.SetWellKnownGeogCS("WGS84")
    projection = srs.ExportToWkt()
    ds.SetProjection(projection)
    band = ds.GetRasterBand(1)

    print("Write scale: {}".format(scale))
    print("Write offset: {}".format(offset))
    band.SetScale(scale)
    band.SetOffset(offset)
    ds = None

    ds1 = gdal.Open(file_name)
    print(ds1.GetRasterBand(1).GetScale())
    print(ds1.GetRasterBand(1).GetOffset())
```

outputs:

### gdal 3.0.1

```
Write scale: 1.0
Write offset: 0.0
1.0
0.0
Write scale: 2.0
Write offset: 0.5
2.0
0.5
Write scale: None
Write offset: None
Traceback (most recent call last):
  File "/home/cpa/.emacs.d/.cache/junk/2020/05/18-155807.py", line 28, in <module>
    band.SetScale(scale)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/base-3/lib/python3.7/site-packages/osgeo/gdal.py", line 2605, in SetScale
    return _gdal.Band_SetScale(self, *args)
TypeError: in method 'Band_SetScale', argument 2 of type 'double'
```

### gdal 3.1.0

```
Write scale: 1.0
Write offset: 0.0
None
None
Write scale: 2.0
Write offset: 0.5
2.0
0.5
Write scale: None
Write offset: None
Traceback (most recent call last):
  File "/home/cpa/.emacs.d/.cache/junk/2020/05/18-155807.py", line 28, in <module>
    band.SetScale(scale)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/gdal3.1.0/lib/python3.8/site-packages/osgeo/gdal.py", line 3473, in SetScale
    return _gdal.Band_SetScale(self, *args)
TypeError: in method 'Band_SetScale', argument 2 of type 'double'
```

## Operating system

Linux, Arch

## GDAL version and provenance

gdal 3.0.1 and gdal 3.1.0 from conda forge

**Comment by rouault** [comment]
For the reading side, this behaviour is a consequence of 69f25f253d141faf836c400676f9f94dd3f43707 which fixed PAM to wrongly report scale and offset even when they were not set.

On the writing side, the logic in https://github.com/OSGeo/gdal/blob/master/gdal/frmts/gtiff/geotiff.cpp#L11644 doesn't write scale and offset is they are at (1, 0). It could test that they have been explicitly set instead of checking the values, but as the API has no way to unset values, setting to (1,0) is the convention used to unset scale / value. So making that change would break tests at https://github.com/OSGeo/gdal/blob/master/autotest/gcore/tiff_write.py#L2620

So I'm not sure there's an immediate fix for that.

**Comment by cpaulik** [comment]
Not being able to unset using `None` was actually a second minor gripe with the API. 

What speaks against using e.g.

```python
    band.SetScale(None)
    band.SetOffset(None)
```
to unset the values.

That would be consistent with the values that are returned if nothing is set.

Or is this not a choice for the Python API alone?

**Comment by rouault** [comment]
> is this not a choice for the Python API alone?

the Python API indeed relies on the C one, which expects a double

**Comment by cpaulik** [comment]
Is it an option to use `double nan` as the value to reset scale and offset in C++?

If so we might adapt the swig interface to replace a Python `None` by `double nan` when setting the values?

**Comment by rouault** [comment]
Technically that could work. However in the past for a similar issue with nodata, we introduced an explicit DeleteNoDataValue() method in the C & C++ & Python API. For consistency, I guess we should follow that route if we wanted to address this

**Comment by cpaulik** [comment]
Not sure I completely understand. 

Would that mean it would work like this:

```python
band.SetScale(1.0)
band.DeleteScaleValue() #to unset
```

or like this

```python
band.SetScale(1.0)
band.SetScale(band.DeleteNoDataValue()) # to unset
```

At least from a Python perspective a symmetrical API would be something I would prefer. Meaning if `band.GetScale()` can return `None` then it should also be possible to use this value in `band.SetScale()`.

**Comment by rouault** [comment]
band.DeleteScale() / band.DeleteOffset() would be the direct mapping of the C API.
As a convenience we could probably redirect SetScale(None) to DeleteScale() (resp. for offset)
