### ISSUE TITLE
LVBAG: member call on null pointer of type 'VSIVirtualHandle'

### ISSUE THREAD

**Issue by rouault** [OSGeo/gdal#2627]
From https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22711

The relevant stack trace

```
  | cpl_vsil.cpp:1732:26: runtime error: member call on null pointer of type 'VSIVirtualHandle'
  | #0 0x4f793e in VSIFSeekL gdal/gdal/port/cpl_vsil.cpp:1732:26
  | #1 0x4f7a5c in VSIRewindL gdal/gdal/port/cpl_vsil.cpp:1795:24
  | #2 0x29c4b3e in OGRLVBAGLayer::OGRLVBAGLayer(char const*) gdal/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbaglayer.cpp:61:5
  | #3 0x29c0c31 in OGRLVBAGDataSource::Open(char const*) gdal/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdatasource.cpp:49:33
  | #4 0x19c551a in OGRLVBAGDriverOpen(GDALOpenInfo*) gdal/gdal/ogr/ogrsf_frmts/lvbag/ogrlvbagdriver.cpp:101:24
  | #5 0x13febd7 in GDALOpenEx gdal/gdal/gcore/gdaldataset.cpp:3387:20
  | #6 0x1bd6c7d in OGRVRTLayer::FullInitialize() gdal/gdal/ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp:653:38
  | #7 0x1bebe89 in OGRVRTLayer::GetLayerDefn() gdal/gdal/ogr/ogrsf_frmts/vrt/ogrvrtlayer.cpp:2239:32
  | #8 0x62d8a7 in OGRLayer::GetSpatialRef() gdal/gdal/ogr/ogrsf_frmts/generic/ogrlayer.cpp:1039:9
  | #9 0x62dc8e in OGR_L_GetSpatialRef gdal/gdal/ogr/ogrsf_frmts/generic/ogrlayer.cpp:1060:43
  | #10 0x4c9c4a in LLVMFuzzerTestOneInput gdal/gdal/./fuzzers/ogr_fuzzer.cpp:116:13
 ```

I didn't manage to make the reproduce work with an out-of-the box build. Probably depends a bit on GDAL being built with -DHAVE_FUZZER_FRIENDLY_ARCHIVE to disable some checks, but there are definitely unsafe uses of the ``fp`` member in OGRLVBAGLayer. The VSIFRewind() call in its constructor should be protected against nullness, and I guess the OGRLVBAGDataSource::Open() call should check for non null fp and give up early so as to avoid other potential uses of a NULL fp in OGRLVBAGLayer

**Comment by rouault** [comment]
CC  @yorickdewid
