### ISSUE TITLE
crs2crs2grid.py error?

### ISSUE THREAD

**Issue by jgrn307** [OSGeo/gdal#2655]
## Expected behavior and actual behavior.

I'm using the latest htdp and crs2crs2grid.py is not working even using the example.

## Steps to reproduce the problem.

crs2crs2grid.py 29 2002.0 8 2002.0 -o nad83_2002.ct2

Returns:

```
********************************************************
   HTDP (Horizontal Time-Dependent Positioning)
   SOFTWARE VERSION: 3.2.9
   VERSION DATE:     May 17, 2020

   AUTHORS: Richard Snay, Chris Pearson, Jarir Saleh,
            and Michael Dennis
            Email: ngs.cors.htdp@noaa.gov
********************************************************

 This software incorporates numerical models that
 characterize continuous crustal motion as well as
 the episodic motion associated with earthquakes.

 The User Guide contains additional information and a set
 of exercises to familiarize users with the software.

 Hit ENTER or RETURN to continue.
 ***************************************
 MAIN MENU:
    0... Exit software.
    1... Estimate horizontal displacements between two dates.
    2... Estimate horizontal velocities.
    3... Transform observations to a specified reference frame and/or date.
    4... Transform positions between reference frames and/or dates.
    5... Transform velocities between reference frames.
 Please enter the name for the file to contain
 the transformed positions.
 *******************************************
 Enter the reference frame of the input positions
  1...NAD_83(2011/CORS96/2007)  (North American plate fixed)
  2...NAD_83(PA11/PACP00)       (Pacific plate fixed)
  3...NAD_83(MA11/MARP00)       (Mariana plate fixed)

  5...WGS_84(transit) (NAD_83(2011) used)  15...ITRF91
  6...WGS_84(G730) (ITRF91 used)           16...ITRF92
  7...WGS_84(G873) (ITRF94 used)           17...ITRF93
  8...WGS_84(G1150) (ITRF2000 used)        18...ITRF94
  9...WGS_84(G1674) (ITRF2008 used)        19...ITRF96
 10...WGS_84(G1762) (IGb08 used)           20...ITRF97 or IGS97
 11...SIO/MIT_92 (ITRF91 used)    21...ITRF2000 or IGS00/IGb00
 12...ITRF88                      22...ITRF2005 or IGS05
 13...ITRF89                      23...ITRF2008 or IGS08/IGb08
 14...ITRF90 or (PNEOS90/NEOS90)  24...ITRF2014 or IGS14/IGb14

  Improper selection -- try again.
 *******************************************
 Enter the reference frame of the input positions
  1...NAD_83(2011/CORS96/2007)  (North American plate fixed)
  2...NAD_83(PA11/PACP00)       (Pacific plate fixed)
  3...NAD_83(MA11/MARP00)       (Mariana plate fixed)

  5...WGS_84(transit) (NAD_83(2011) used)  15...ITRF91
  6...WGS_84(G730) (ITRF91 used)           16...ITRF92
  7...WGS_84(G873) (ITRF94 used)           17...ITRF93
  8...WGS_84(G1150) (ITRF2000 used)        18...ITRF94
  9...WGS_84(G1674) (ITRF2008 used)        19...ITRF96
 10...WGS_84(G1762) (IGb08 used)           20...ITRF97 or IGS97
 11...SIO/MIT_92 (ITRF91 used)    21...ITRF2000 or IGS00/IGb00
 12...ITRF88                      22...ITRF2005 or IGS05
 13...ITRF89                      23...ITRF2008 or IGS08/IGb08
 14...ITRF90 or (PNEOS90/NEOS90)  24...ITRF2014 or IGS14/IGb14
3...NAD_83(MA11/MARP00)       (Mariana plate fixed)

  5...WGS_84(transit) (NAD_83(2011) used)  15...ITRF91
  6...WGS_84(G730) (ITRF91 used)           16...ITRF92
  7...WGS_84(G873) (ITRF94 used)           17...ITRF93
  8...WGS_84(G1150) (ITRF2000 used)        18...ITRF94
  9...WGS_84(G1674) (ITRF2008 used)        19...ITRF96
 10...WGS_84(G1762) (IGb08 used)           20...ITRF97 or IGS97
 11...SIO/MIT_92 (ITRF91 used)    21...ITRF2000 or IGS00/IGb00
 12...ITRF88                      22...ITRF2005 or IGS05
 13...ITRF89                      23...ITRF2008 or IGS08/IGb08
 14...ITRF90 or (PNEOS90/NEOS90)  24...ITRF2014 or IGS14/IGb14


 Enter the reference date of the input positions.
 How do you wish to enter the time?
     1. month-day-year in free format
        for example, 5,12,1979
        represents May 12, 1979
     2. decimal year
        for example the entry 1979.359
        represents UTC midnight at the begining
        of May 12, 1979.

  Enter decimal year
 The model is not valid for dates prior to 1906.

  Do you wish to re-enter the date? (y/n)
 ***************************************
 MAIN MENU:
    0... Exit software.
    1... Estimate horizontal displacements between two dates.
    2... Estimate horizontal velocities.
    3... Transform observations to a specified reference frame and/or date.
    4... Transform positions between reference frames and/or dates.
    5... Transform velocities between reference frames.
 ********************************************
 Please enter the time to which the updated
 positions and/or observations are to correspond:
 How do you wish to enter the time?
     1. month-day-year in free format
        for example, 5,12,1979
        represents May 12, 1979
     2. decimal year
        for example the entry 1979.359
        represents UTC midnight at the begining
        of May 12, 1979.

 Improper entry
 How do you wish to enter the time?
     1. month-day-year in free format
        for example, 5,12,1979
        represents May 12, 1979
     2. decimal year
        for example the entry 1979.359
        represents UTC midnight at the begining
        of May 12, 1979.

 Improper entry
 How do you wish to enter the time?
     1. month-day-year in free format
        for example, 5,12,1979
        represents May 12, 1979
     2. decimal year
        for example the entry 1979.359
        represents UTC midnight at the begining
        of May 12, 1979.

 Improper entry
 Improper entry
 How do you wish to enter the time?
     1. month-day-year in free format
        for example, 5,12,1979
        represents May 12, 1979
     2. decimal year
        for example the entry 1979.359
        represents UTC midnight at the begining
        of May 12, 1979.



 Failed to read option in GETDMY:ios=          -1
 ABNORMAL TERMINATION
 PLEASE CHECK YOUR INPUT FILE AND TRY AGAIN
htdp run complete.
 HTDP OUTPUT, VERSION 3.2.9




points found:    0
points expected: 153361

 Enter the reference frame for the output positions
  1...NAD_83(2011/CORS96/2007)  (North American plate fixed)
  2...NAD_83(PA11/PACP00)       (Pacific plate fixed)
  3...NAD_83(MA11/MARP00)       (Mariana plate fixed)
```

## Operating system

Ubuntu 16.04 64 bit

## GDAL version and provenance

GDAL 3.0.4, released 2020/01/28

**Comment by jgrn307** [comment]
A bit more digging revealed a different bug -- first off, it looks like the latest version of HTDP doesn't support CRSid "29" in the latest version.  I think using "1" is the equivalent (you may want to change the example to match this):

crs2crs2grid.py 1 2002.0 8 2002.0 -o nad83_2002.ct2 

This reveals a new bug that I believe is in the read_grid_crs_to_crs function.  It completes the htdp run, and the output (if using a -kwf flag) looks "legit" (there is data there), but I get this error:

```
htdp run complete.
 HTDP OUTPUT, VERSION 3.2.9

 TRANSFORMING POSITIONS FROM NAD_83(2011/CORS96/2007) (EPOCH = 01-01-2002 (2002.0000))
                          TO WGS_84(G1150)            (EPOCH = 01-01-2002 (2002.0000))

Traceback (most recent call last):
  File "/usr/local/bin/crs2crs2grid.py", line 378, in <module>
    adjustment = read_grid_crs_to_crs(out_grid_fn, grid.shape)
  File "/usr/local/bin/crs2crs2grid.py", line 89, in read_grid_crs_to_crs
    ptuple = next_point(fd)
  File "/usr/local/bin/crs2crs2grid.py", line 67, in next_point
    lat_src = float(tokens[1]) + float(tokens[2]) / 60.0 + float(tokens[3]) / 3600.0
ValueError: could not convert string to float: '"PNT_0_1"'
```

**Comment by jgrn307** [comment]
If it helps, I dropped the three -kwf files here (the output file I suspect is what you'll need to fix this):

https://drive.google.com/drive/folders/1iNC85Yw01bxkDECpTU0y6FZgxwWKjL2g?usp=sharing
