### ISSUE TITLE
Issue with importing gdal and looking for unknown plugin

### ISSUE THREAD

**Issue by ev0065** [OSGeo/gdal#2700]
## Expected behavior and actual behavior.

When I run gdal2tiles.py, I expect it to run or output a help prompt. In reality, I receive an error (which will be shown below). I started an issue [here](https://github.com/OSGeo/gdal/issues/2693) and found an issue with gdal 3.1 (I think) and want to debug it here with others. 

## Steps to reproduce the problem.

1. Install Python 3.7.7 64 bit
2. Install these binaries from [GISInternals](https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-mapserver.zip): `gdal-300-1911-x64-core.msi` and `GDAL-3.1.0.win-amd64-py3.7.msi`
3. Add `C:\Program Files\GDAL` to PATH.
4. Add 2 system environment variables: `GDAL_DATA`=`C:\Program Files\GDAL\gdal-data` and `GDAL_DRIVER_PATH`=`C:\Program Files\GDAL\gdalplugins`
5. Navigate to command prompt. Run `gdalinfo --version`. This should work and outputs `GDAL 3.1.0dev, released 2019/99/99`
6. Run `gdal2tiles.py` after ensuring that .py files are opened with python executable
7. Get an error

-- Here's the fun part --
As per the other issue, I downloaded a process monitor and looked at the command prompt and python behind-the-scenes. If I opened a python shell (just type `python`) and imported gdal (`from osgeo import gdal`) then I get this* error. Looking at the process monitor, it is searching for a plugin called `gdal301.dll` in many directories. As expected, it is looking in `C:\Program Files\GDAL`, where I see `gdal300.dll` but not 301. **I cannot find `gdal301.dll` anywhere. It does not exist (even after multiple installations and uninstallations)!**

So, I believe that there is a bug in GDAL 3.1.0 that's causing this critical issue. I would appreciate it if someone could look at this issue and help me solve it. I can provide additional information if needed. Thanks 

*the error
```
>>> from osgeo import gdal
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 32, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\site-packages\osgeo\__init__.py", line 31, in swig_import_helper
    return importlib.import_module('_gdal')
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```
## Operating system

I am using Windows 10, 64 bit.

## GDAL version and provenance

Gdal 3.1.0

**Comment by rouault** [comment]
>     2\. Install these binaries from [GISInternals](https://www.gisinternals.com/query.html?content=filelist&file=release-1911-x64-gdal-mapserver.zip): `gdal-300-1911-x64-core.msi` and `GDAL-3.1.0.win-amd64-py3.7.msi`

Using gdal 3.0 binaries (gdal-300-1911-x64-core.msi) with gdal 3.1 python bindings is not going to work. https://github.com/gisinternals/buildsystem/issues would probably the best place to report this

**Comment by ev0065** [comment]
@rouault I opened it there. But FYI, there is no gdal 3.1 binaries (e.g. the core install). So i guess we'll see what comes out of it
