### ISSUE TITLE
Gdal.SetConfigOption exception encountered for x64 

### ISSUE THREAD

**Issue by ylimemily** [OSGeo/gdal#2951]
I filed a ticket in build but wasn't sure if that's the correct location to for the issue i encountered so I am filing another one here. My apologies in advance. 
https://github.com/gisinternals/buildsystem/issues/160#issue-703959584

I downloaded gdal 2.4.4 and gdal.native 2.4.4 through nuget.org in a C# project and I am encountering exceptions in Gdal.SetConfigOption calls in GdalConfiguration.cs. The exceptions only occurs if the nativePath variable is set to x64 , it works fine when set to x86. I think this has been raised before in this link but the latest version available in nuget is 2.4.4 and I'm still encountering the issue. So i'm not sure if this has been fixed or is there another version that I can grab from nuget? Thanks.

Trace output:
Exception thrown: 'System.TypeInitializationException' in gdal_csharp.dll
error: System.TypeInitializationException: The type initializer for 'OSGeo.GDAL.GdalPINVOKE' threw an exception. ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_Gdal(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..cctor()
--- End of inner exception stack trace ---
at OSGeo.GDAL.GdalPINVOKE.SWIGExceptionHelper..ctor()
at OSGeo.GDAL.GdalPINVOKE..cctor()
--- End of inner exception stack trace ---
at OSGeo.GDAL.GdalPINVOKE.SetConfigOption(String jarg1, String jarg2)
at OSGeo.GDAL.Gdal.SetConfigOption(String pszKey, String pszValue)
at TestGdal.GdalConfiguration..cctor() in D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\GdalConfiguration.cs:line 96
error: Executing directory: D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\bin\Debug
error: gdal directory: D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\bin\Debug\gdal
error: native directory: D:\Visual Studio 2015\Projects\CheckGdal\TestGdal\TestGdal\bin\Debug\gdal\x64

**Comment by rouault** [comment]
I guess the ticket in gisinternals will do. Looks more like a distribution/usage issue than an upstream one
