### ISSUE TITLE
gdal2tiles.py --profile=raster crashes when not specifying s_srs

### ISSUE THREAD

**Issue by w4rum** [OSGeo/gdal#2998]
## Expected behavior and actual behavior.

I expected to be able to split [this image](https://static.wikia.nocookie.net/squad_gamepedia/images/2/2b/Alpha_v9_Yehorivka_Map.jpg/revision/latest?cb=20200608220110) into tiles using
```
gdal2tiles.py --xyz --profile=raster --s_srs=xyz /mnt/map-resources/full-size/Yehorivka.jpg /mnt/map-resources/tiles/Yehorivka/
```
Instead, the script crashes with the following traceback:
```
Traceback (most recent call last):
  File "/usr/bin/gdal2tiles.py", line 3223, in <module>
    main()
  File "/usr/bin/gdal2tiles.py", line 3217, in main
    single_threaded_tiling(input_file, output_folder, options)
  File "/usr/bin/gdal2tiles.py", line 3137, in single_threaded_tiling
    conf, tile_details = worker_tile_details(input_file, output_folder, options)
  File "/usr/bin/gdal2tiles.py", line 3053, in worker_tile_details
    gdal2tiles.open_input()
  File "/usr/bin/gdal2tiles.py", line 1694, in open_input
    self.out_srs = setup_output_srs(self.in_srs, self.options)
  File "/usr/bin/gdal2tiles.py", line 896, in setup_output_srs
    output_srs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
AttributeError: 'NoneType' object has no attribute 'SetAxisMappingStrategy'
```

When manually specifying `--s_srs=xyz`, it works as expected. (Is that even the correct SRS? I just guessed and it works.)

## Steps to reproduce the problem.

1. Download [this image](https://static.wikia.nocookie.net/squad_gamepedia/images/2/2b/Alpha_v9_Yehorivka_Map.jpg/revision/latest?cb=20200608220110). I have also tested it with other images and always ran into the same problem.
2. Pull the docker image
`osgeo/gdal:latest Digest:sha256:2e8d5b19503df6bbd8c1e8fea62599ea0538dc9e0da45b04963a2abd93bd1add`
`docker pull osgeo/gdal`
3. Run `gdal2tiles.py` inside the docker container (you might have to adjust directories):
```
docker run \
	--mount type=bind,source=$(PWD),target=/mnt/map-resources \
	osgeo/gdal \
	gdal2tiles.py \
	--xyz \
	--profile=raster \
	--processes=16 \
	--zoom=0-5 \
	/mnt/map-resources/full-size/Yehorivka.jpg /mnt/map-resources/tiles/Yehorivka/
```

## Operating system
Running Docker `1:19.03.13-1` on Arch Linux, kernel version `5.8.12-arch1-1`.

## GDAL version and provenance

Official docker image `osgeo/gdal:latest Digest:sha256:2e8d5b19503df6bbd8c1e8fea62599ea0538dc9e0da45b04963a2abd93bd1add`.
```
gdal2tiles.py --version
GDAL 3.2.0dev-1272475c527cb478a46b9bc48d33fa29e71855b6, released 2020/10/02
```

## Additional comments
In `gdal2tiles.py`, line 873, `setup_input_srs` returns `input_srs` as `None`:
```python
def setup_input_srs(input_dataset, options):
    """
    Determines and returns the Input Spatial Reference System (SRS) as an osr object and as a
    WKT representation

    Uses in priority the one passed in the command line arguments. If None, tries to extract them
    from the input dataset
    """

    input_srs = None
    input_srs_wkt = None

    if options.s_srs:
        input_srs = osr.SpatialReference()
        input_srs.SetFromUserInput(options.s_srs)
        input_srs_wkt = input_srs.ExportToWkt()
    else:
        # this branch is taken
        # returns None
        input_srs_wkt = input_dataset.GetProjection()
        # not taken
        if not input_srs_wkt and input_dataset.GetGCPCount() != 0:
            input_srs_wkt = input_dataset.GetGCPProjection()
        # not taken
        if input_srs_wkt:
            input_srs = osr.SpatialReference()
            input_srs.ImportFromWkt(input_srs_wkt)
        # input_srs_wkt is still None and input_srs is not set

    if input_srs is not None:
        input_srs.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
    
    return input_srs, input_srs_wkt
```

**Comment by w4rum** [comment]
@rouault Thank you for handling this so quickly!
