### ISSUE TITLE
segfault in VRTPansharpenedDataset

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#3189]
On gdal 3.2 and master, doing a simple gdalinfo on a VRTPansharpenedDataset results in:

```
#0  0x0000008000000000 in ?? ()
#1  0x00007ffff771114c in VRTSimpleSource::FlushCache (this=0x555555607310) at vrtsources.cpp:178
#2  0x00007ffff7710c20 in VRTSourcedRasterBand::FlushCache (this=0x555555607190) at vrtsourcedrasterband.cpp:1751
#3  0x00007ffff774bbe4 in GDALDataset::FlushCache (this=0x555555606eb0) at gdaldataset.cpp:429
#4  0x00007ffff76c0dbf in VRTFlushCacheStruct<VRTDataset>::FlushCache (obj=...) at vrtdataset.cpp:156
#5  0x00007ffff76ba59c in VRTDataset::FlushCache (this=0x555555606eb0) at vrtdataset.cpp:127
#6  0x00007ffff76ba31e in VRTDataset::~VRTDataset (this=0x555555606eb0, __in_chrg=<optimized out>) at vrtdataset.cpp:96
#7  0x00007ffff76ba53a in VRTDataset::~VRTDataset (this=0x555555606eb0, __in_chrg=<optimized out>) at vrtdataset.cpp:115
#8  0x00007ffff7433259 in GDALPansharpenOperation::~GDALPansharpenOperation (this=0x5555555cc460, __in_chrg=<optimized out>)
    at gdalpansharpen.cpp:179
#9  0x00007ffff76f92ba in VRTPansharpenedDataset::CloseDependentDatasets (this=0x5555555ea8f0) at vrtpansharpened.cpp:187
#10 0x00007ffff76f915e in VRTPansharpenedDataset::~VRTPansharpenedDataset (this=0x5555555ea8f0, __in_chrg=<optimized out>)
    at vrtpansharpened.cpp:157
#11 0x00007ffff76f91d2 in VRTPansharpenedDataset::~VRTPansharpenedDataset (this=0x5555555ea8f0, __in_chrg=<optimized out>)
    at vrtpansharpened.cpp:159
#12 0x00007ffff76f9394 in VRTPansharpenedDataset::CloseDependentDatasets (this=0x5555555abb70) at vrtpansharpened.cpp:204
#13 0x00007ffff76f915e in VRTPansharpenedDataset::~VRTPansharpenedDataset (this=0x5555555abb70, __in_chrg=<optimized out>)
    at vrtpansharpened.cpp:157
#14 0x00007ffff76f91d2 in VRTPansharpenedDataset::~VRTPansharpenedDataset (this=0x5555555abb70, __in_chrg=<optimized out>)
    at vrtpansharpened.cpp:159
#15 0x00007ffff7750b36 in GDALClose (hDS=0x5555555abb70) at gdaldataset.cpp:3692
#16 0x0000555555555b4d in main (argc=2, argv=0x5555555ab240) at gdalinfo_bin.cpp:223
```

this also happens with other (all?) gdal utilities, not just gdalinfo.

the vrt's panchroband references another simple vrt that references a geotiff
the vrt's spectralbands reference a single other vrt that references the 4 bands of a single geotiff

I can provide the data privately if needed.

**Comment by rouault** [comment]
> I can provide the data privately if needed.

that would be helpful
