### ISSUE TITLE
(Bug?) GDAL Import Error: DLL Load Failed when executing gdal_calc.py

### ISSUE THREAD

**Issue by DavidWei10** [OSGeo/gdal#3517]
I have Qgis Version 3.16.3. and GDAL 3.1.4. installed, also Python 3.7. which comes with OSGEO4W Shell. My operating system is Windows 10 Pro 10.0.19041 Build 19041.

## Steps to reproduce the problem.

If I try to execute "gdal_calc.py", I get the following error message:

`Traceback (most recent call last): File "C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo_init_.py", line 18, in swig_import_helper return importlib.import_module(mname) File "C:\OSGeo4W64\apps\Python37\lib\importlib_init_.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1006, in _gcd_import File "", line 983, in _find_and_load File "", line 967, in _find_and_load_unlocked File "", line 670, in _load_unlocked File "", line 583, in module_from_spec File "", line 1043, in create_module File "", line 219, in _call_with_frames_removed ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden. (In English: The stated module cannot be found)

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "C:\Program Files\GDAL\gdal_calc.py", line 5, in from osgeo.utils.gdal_calc import * # noqa File "C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo_init_.py", line 32, in gdal = swig_import_helper() File "C:\OSGeo4W64\apps\Python37\lib\site-packages\osgeo_init.py", line 31, in swig_import_helper return importlib.import_module('gdal') File "C:\OSGeo4W64\apps\Python37\lib\importlib_init.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

E:\UniversitaetHD\WS 2020 - 2021\Seminar GIS\Gruppenarbeit\Dateien>PAUSE"

My system variables are already correct configured:

https://i.stack.imgur.com/3LWwP.png
https://i.stack.imgur.com/IYrT8.png

I have the recent version of QGIs/GDAL installed.

While executing `from osgeo import gdal` in python, the same error message appears.

Thanks in advance!

**Comment by rouault** [comment]
This is likely an issue with the use of the binary distribution than with GDAL upstream. Closing
