### ISSUE TITLE
Translate from TIFF to JPEG2000 get "Segmentation fault"

### ISSUE THREAD

**Issue by lcxywfe** [OSGeo/gdal#4054]
## Expected behavior and actual behavior.

I expected to translate a TIFF file to JPEG2000, get segmetation fault instead.

## Steps to reproduce the problem.

gdal_translate xxx.tif xxx.jp2

## Operating system

Ubuntu 18.04 64 bit

## GDAL version and provenance

GDAL 3.4.0dev-8b9bff3

## GDB backtrace
```
#0  0x00007fe20d19cd1d in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007fe20d961b36 in lru11::Cache<OSRProjTLSCache::EPSGCacheKey, std::shared_ptr<PJconsts>, lru11::NullLock, std::unordered_map<OSRProjTLSCache::EPSGCacheKey, std::_List_iterator<lru11::KeyValuePair<OSRProjTLSCache::EPSGCacheKey, std::shared_ptr<PJconsts> > >, OSRProjTLSCache::EPSGCacheKeyHasher, std::equal_to<OSRProjTLSCache::EPSGCacheKey>, std::allocator<std::pair<OSRProjTLSCache::EPSGCacheKey const, std::_List_iterator<lru11::KeyValuePair<OSRProjTLSCache::EPSGCacheKey, std::shared_ptr<PJconsts> > > > > > >::get (k=..., this=<optimized out>) at /root/repo/gdal/gdal/port/cpl_mem_cache.h:149
#2  OSRProjTLSCache::GetPJForEPSGCode (this=this@entry=0x7fe20ed60758, nCode=nCode@entry=4326, bUseNonDeprecated=bUseNonDeprecated@entry=true, bAddTOWGS84=bAddTOWGS84@entry=false) at ogr_proj_p.cpp:260
#3  0x00007fe20d9c01a7 in OGRSpatialReference::importFromEPSGA (this=this@entry=0x7ffe71c3ee20, nCode=4326) at ogrspatialreference.cpp:10751
#4  0x00007fe20df9128e in GDALJP2Metadata::GetGMLJP2GeoreferencingInfo (this=this@entry=0x7ffe71c3f450, nEPSGCode=@0x7ffe71c3eec0: 4326, adfOrigin=adfOrigin@entry=0x7ffe71c3eed0, adfXVector=adfXVector@entry=0x7ffe71c3eee0, 
    adfYVector=adfYVector@entry=0x7ffe71c3eef0, pszComment=@0x7ffe71c3eec8: 0x7fe20e56da54 "", osDictBox=..., bNeedAxisFlip=@0x7ffe71c3eec4: 0) at gdaljp2metadata.cpp:1306
#5  0x00007fe20df91887 in GDALJP2Metadata::CreateGMLJP2 (this=this@entry=0x7ffe71c3f450, nXSize=nXSize@entry=2602, nYSize=nYSize@entry=2353) at gdaljp2metadata.cpp:1459
#6  0x00007fe20dd883cc in JP2OpenJPEGDataset::CreateCopy (pszFilename=0x561e295d69e0 "/mnt/cache_dir/input/20862/raw_dsm/copy-hexagon_california_L0_small_test_gpu.0.0.20848.0.0.0/2019034.rect.tif.jp2", poSrcDS=0x561e295a23c0, 
    bStrict=<optimized out>, papszOptions=0x0, pfnProgress=0x7fe20e437e40 <GDALTermProgress(double, char const*, void*)>, pProgressData=0x0) at openjpegdataset.cpp:2940
#7  0x00007fe20df85096 in GDALDriver::CreateCopy (this=this@entry=0x561e29586890, 
    pszFilename=pszFilename@entry=0x561e295d69e0 "/mnt/cache_dir/input/20862/raw_dsm/copy-hexagon_california_L0_small_test_gpu.0.0.20848.0.0.0/2019034.rect.tif.jp2", poSrcDS=poSrcDS@entry=0x561e295a23c0, bStrict=0, 
    papszOptions=0x0, pfnProgress=0x7fe20e437e40 <GDALTermProgress(double, char const*, void*)>, pProgressData=0x0) at gdaldriver.cpp:1058
#8  0x00007fe20df853f7 in GDALCreateCopy (hDriver=hDriver@entry=0x561e29586890, 
    pszFilename=pszFilename@entry=0x561e295d69e0 "/mnt/cache_dir/input/20862/raw_dsm/copy-hexagon_california_L0_small_test_gpu.0.0.20848.0.0.0/2019034.rect.tif.jp2", hSrcDS=hSrcDS@entry=0x561e295a23c0, bStrict=<optimized out>, 
    papszOptions=<optimized out>, pfnProgress=<optimized out>, pProgressData=0x0) at gdaldriver.cpp:1107
#9  0x00007fe20da89253 in GDALTranslate (pszDest=<optimized out>, hSrcDataset=hSrcDataset@entry=0x561e295a23c0, psOptionsIn=psOptionsIn@entry=0x561e295d5fe0, pbUsageError=pbUsageError@entry=0x7ffe71c4552c)
    at gdal_translate_lib.cpp:1171
#10 0x0000561e27f8eb2f in main (argc=<optimized out>, argv=<optimized out>) at gdal_translate_bin.cpp:365
```

**Comment by rouault** [comment]
I strongly suspect the issue is specific to your build. First you should check that it is a clean build, in the case where you would have updated an existing repository. If that's the case, make sure to "make clean" before rebuilding

**Comment by lcxywfe** [comment]
@rouault I confirm it is a clean build, and it worked in Ubuntu 16.04.

**Comment by lcxywfe** [comment]
I tried some version of gdal, and I found the v2.4.4 without this problem.

**Comment by rouault** [comment]
GDAL master has continuous integration configurations that run on Ubuntu 18.04, so this isn't an issue per se
You should perhaps check that your GDAL build links against a single libproj.so. It might be that your GDAL links against an external libgeotiff and/or libspatialite that link against a system libproj, that isn't the libproj version that GDAL itself links against

**Comment by lcxywfe** [comment]
I build the GDAL by ```./configure --with-libtiff=internal --with-geotiff=internal --with-proj=/PATH/TO/PROJ6```, and when I ```ldd libgdal.so```, the dependnet libraries are the correct libraries.

**Comment by rouault** [comment]
Which PROJ version do you use ? Perhaps try upgrading to the latest one

**Comment by lcxywfe** [comment]
proj-6.3.1

**Comment by rouault** [comment]
try with 8.1.0

**Comment by lcxywfe** [comment]
OK

**Comment by rouault** [comment]
@lcxywfe any update on this ?

**Comment by rouault** [comment]
Closing due to lack of feedback
