### ISSUE TITLE
gdal2tiles multiprocessing fails

### ISSUE THREAD

**Issue by stevenjh** [OSGeo/gdal#4154]
## Expected behavior and actual behavior.

gdal2tiles fails when using threads, single threaded works as expected

## Steps to reproduce the problem.

gdal2tiles -s EPSG:3857 -z 10-16 --processes=6 --xyz "3857.jp2" "C:\temp\tiles"

## Operating system

Windows 10

## GDAL version and provenance

From QGIS 3.16.8 LTR, python 3.9

## Traceback generated
```
Generating Base Tiles:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\runpy.py", line 268, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\Scripts\gdal2tiles.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\osgeo_utils\gdal2tiles.py", line 3257, in main
    multi_threaded_tiling(input_file, output_folder, options)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\site-packages\osgeo_utils\gdal2tiles.py", line 3206, in multi_threaded_tiling
    pool = Pool(processes=nb_processes)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\pool.py", line 212, in __init__
    self._repopulate_pool()
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
Traceback (most recent call last):
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "<string>", line 1, in <module>
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    _check_not_importing_main()
    exitcode = _main(fd, parent_sentinel)
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 125, in _main
    raise RuntimeError('''
Traceback (most recent call last):
    prepare(preparation_data)
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.  File "<string>", line 1, in <module>
  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 236, in prepare

  File "C:\PROGRA~1\QGIS31~1.8\apps\Python39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    _fixup_main_from_path(data['init_main_from_path'])
    exitcode = _main(fd, parent_sentinel)
```

**Comment by sagadave** [comment]
Confirming this behaviour also occurs on macOS 11.5 using homebrew distribution. Multiple threaded processing fails with any number of threads. Using 1 thread works. 
GDAL 3.3.1, Python 3.9

**Comment by luo-geng** [comment]
This also happens on `vsis3`. and  `--exclude`  can't work at `vsis3` mode

cmd
 ```bash
docker run -it --rm --network=host  --env-file=env  ghcr.io/osgeo/gdal:ubuntu-full-latest gdal2tiles.py -z 1-13 -p mercator --srcnodata=0 --exclude /vsis3/XX.vrt /vsis3/XX

docker run -it --rm --network=host  --env-file=env  ghcr.io/osgeo/gdal:ubuntu-full-latest gdal2tiles.py -z 1-13 -p mercator --srcnodata=0  --processes=8 /vsis3/XX.vrt /vsis3/XX
```

GDAL 3.12.0dev-ce5f0f192b46eb67243a037a241e0ad010a2e378, released 2025/05/06

**Comment by rouault** [comment]
superseded by new gdal raster tile
