### ISSUE TITLE
An Arc/Info Binary Grid raster dataset segfaults GDAL 

### ISSUE THREAD

**Issue by nirvn** [OSGeo/gdal#4316]
## Expected behavior and actual behavior.

The following Arc/Info Binary Grid raster dataset kills QGIS when panning/zoom around for a few seconds. The crash stacktrace indicates GDAL segaults along the way.

## Steps to reproduce the problem.

Dataset:
[k6034_w.zip](https://github.com/OSGeo/gdal/files/7043192/k6034_w.zip)

1. Load the dataset in QGIS (by opening the k6034_w/w001001.adf file)
2. Zoom in and out using your mouse wheel
3. QGIS dies

## Operating system

Ubuntu 21.04

## GDAL version and provenance

GDAL 3.2.2

## GDB stacktrace

```
#0  0x00007fffeae5fc02 in  () at /lib/libgdal.so.28
#1  0x00007fffeae5b9b7 in  () at /lib/libgdal.so.28
#2  0x00007fffeb3f82d1 in GDALRasterBand::GetLockedBlockRef(int, int, int) () at /lib/libgdal.so.28
#3  0x00007fffeb41f088 in GDALRasterBand::IRasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) () at /lib/libgdal.so.28
#4  0x00007fffeb3f7a87 in GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, long long, long long, GDALRasterIOExtraArg*) () at /lib/libgdal.so.28
#5  0x00007ffff1abb95c in QgsGdalProviderBase::gdalRasterIO(void*, GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, int, int, QgsRasterBlockFeedback*)
    (hBand=0x7fffb442db70, eRWFlag=GF_Read, nXOff=3636, nYOff=2689, nXSize=1089, nYSize=861, pData=0x7fffb46cba30, nBufXSize=1089, nBufYSize=861, eBufType=GDT_Byte, nPixelSpace=0, nLineSpace=0, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/providers/gdal/qgsgdalproviderbase.cpp:313
#6  0x00007ffff1ac60af in QgsGdalProvider::readBlock(int, QgsRectangle const&, int, int, void*, QgsRasterBlockFeedback*) (this=
    0x55555a00b890, bandNo=1, reqExtent=..., bufferWidthPix=1114, bufferHeightPix=879, data=0x7fffb4441cb0, feedback=0x5555562f1d30)
    at /home/webmaster/dev/cpp/QGIS/src/core/providers/gdal/qgsgdalprovider.cpp:1134
#7  0x00007ffff1ac2da6 in QgsGdalProvider::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555a00b890, bandNo=1, extent=..., width=1114, height=879, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/providers/gdal/qgsgdalprovider.cpp:648
#8  0x00007ffff234334e in QgsPalettedRasterRenderer::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) (this=
    0x5555562177b0, extent=..., width=1114, height=879, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgspalettedrasterrenderer.cpp:140
#9  0x00007ffff2339077 in QgsBrightnessContrastFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555a02be90, bandNo=1, extent=..., width=1114, height=879, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsbrightnesscontrastfilter.cpp:119
#10 0x00007ffff233b53e in QgsHueSaturationFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555a52d7b0, bandNo=1, extent=..., width=1114, height=879, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgshuesaturationfilter.cpp:124
#11 0x00007ffff2367cad in QgsRasterResampleFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x5555562de340, bandNo=1, extent=..., width=1114, height=879, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterresamplefilter.cpp:164
#12 0x00007ffff232ff9f in QgsRasterProjector::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*)
    (this=0x55555a4960f0, bandNo=1, extent=..., width=1114, height=879, feedback=0x5555562f1d30) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasterprojector.cpp:792
#13 0x00007ffff22fca8a in QgsRasterIterator::readNextRasterPartInternal(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >*, int&, int&, QgsRectangle*)
    (this=0x7fffc5bc4d30, bandNumber=1, nCols=@0x7fffc5bc4c00: 1114, nRows=@0x7fffc5bc4c04: 879, block=0x7fffc5bc4c30, topLeftCol=@0x7fffc5bc4c08: 0, topLeftRow=@0x7fffc5bc4c0c: 0, blockExtent=0x0) at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasteriterator.cpp:130
#14 0x00007ffff22fc242 in QgsRasterIterator::readNextRasterPart(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >&, int&, int&, QgsRectangle*)
    (this=0x7fffc5bc4d30, bandNumber=1, nCols=@0x7fffc5bc4c00: 1114, nRows=@0x7fffc5bc4c04: 879, block=
    std::unique_ptr<QgsRasterBlock> = {...}, topLeftCol=@0x7fffc5bc4c08: 0, topLeftRow=@0x7fffc5bc4c0c: 0, blockExtent=0x0)
    at /home/webmaster/dev/cpp/QGIS/src/core/raster/qgsrasteriterator.cpp:80
#15 0x00007ffff234e27e in QgsRasterDrawer::draw(QPainter*, QgsRasterViewPort*, QgsMapToPixel const*, QgsRasterBlockFeedback*)
```

**Comment by rouault** [comment]
The dataset has a corruption (to the best of my understanding, or we lack something in the reverse engineering of the format). Fix to avoid the crash queued in https://github.com/OSGeo/gdal/pull/4323

**Comment by rouault** [comment]
Do you have access to a non-GDAL implementation (I'd assume Esri software don't use GDAL for this format ?) to check if they manage to read the file correctly (the error is in the main resolution layer) ?
