### ISSUE TITLE
_gdal_array undefined symbol in GDAL 3.3+

### ISSUE THREAD

**Issue by drewgilliam** [OSGeo/gdal#4724]
## Expected behavior and actual behavior.

The dockerfile below illustrates a scenario where one builds PROJ & GDAL from source, then later installs GDAL python bindings from pypi (installing numpy first to ensure gdal_array works).  

This procedure is successful for GDAL 3.2.3.  However, GDAL 3.3+ fails to import gdal_array with the traceback below, indicating an undefined symbol.  Expected behavior would be that GDAL 3.3 compiled from source is compatible with pypi bindings.

## Steps to reproduce the problem.

Using the dockerfile below, GDAL v3.2.3 succeeds
```
docker build --tag gdal/test:3.2.3 --build-arg GDAL_VERSION=3.2.3 --file gdal.Dockerfile .
```
while GDAL v3.3.2 fails
```
docker build --tag gdal/test:3.3.2 --build-arg GDAL_VERSION=3.3.2 --file gdal.Dockerfile .
```
### gdal.Dockerfile
```
FROM quay.io/pypa/manylinux2010_x86_64:2021-10-26-cf1e11e as base_image
SHELL ["/usr/bin/env", "/bin/bash", "-euxvc"]

# ----- BUILD STAGE : PROJ -----
FROM base_image as proj
ARG PROJ_VERSION=6.3.2

# additional build dependencies
RUN yum install -y libcurl-devel libtiff-devel zlib-devel; \
    yum clean all

# build & install proj
RUN TEMP_DIR=/tmp/proj; \
    mkdir -p "${TEMP_DIR}" && cd "${TEMP_DIR}"; \
    # download & unzip
    TAR_FILE="proj-${PROJ_VERSION}.tar.gz"; \
    curl -fsSLO http://download.osgeo.org/proj/${TAR_FILE}; \
    tar -xf ${TAR_FILE} --strip-components=1; \
    # configure, build, & install
    ./configure \
        CFLAGS='-DPROJ_RENAME_SYMBOLS -O2' \
        CXXFLAGS='-DPROJ_RENAME_SYMBOLS -DPROJ_INTERNAL_CPP_NAMESPACE -O2' \
        --disable-static; \
    make -j"$(nproc)"; \
    make install DESTDIR="/proj"; \
    # cleanup
    rm -r "${TEMP_DIR}";

# ----- BUILD STAGE : GDAL -----
from base_image as gdal
ARG GDAL_VERSION

# copy proj
COPY --from=proj /proj/usr/local /usr/local

# build & install GDAL
RUN TEMP_DIR=/tmp/gdal; \
    mkdir -p "${TEMP_DIR}" && cd "${TEMP_DIR}"; \
    # download & unzip
    TAR_FILE="gdal-${GDAL_VERSION}.tar.gz"; \
    curl -fsSLO "http://download.osgeo.org/gdal/${GDAL_VERSION}/${TAR_FILE}"; \
    tar -xf "${TAR_FILE}" --strip-components=1; \
    # configure, build, & install
    ./configure \
        --without-libtool \
        --with-hide-internal-symbols \
        --with-libtiff=internal --with-rename-internal-libtiff-symbols \
        --with-geotiff=internal --with-rename-internal-libgeotiff-symbols \
        --with-proj="/usr/local"; \
    make -j"$(nproc)"; \
    make install DESTDIR="/gdal"; \
    # cleanup
    rm -r "${TEMP_DIR}";

# ----- BUILD STAGE : PYPI -----
from python:3.8
ARG GDAL_VERSION

# copy
COPY --from=proj /proj/usr/local /usr/local
COPY --from=gdal /gdal/usr/local /usr/local
RUN ldconfig

# python bindings from pypi (install numpy 1st)
RUN pip install numpy; \
    pip install GDAL==${GDAL_VERSION};

# test python bindings
RUN python3 -c "from osgeo import gdal_array; print('SUCCESS')"
```

Traceback on the last step for v3.3.2 is as follows

```
$ python3 -c "from osgeo import gdal_array"

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/osgeo/gdal_array.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1166, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.8/site-packages/osgeo/_gdal_array.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK11GDALDataset14GetFieldDomainERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/osgeo/gdal_array.py", line 17, in <module>
    _gdal_array = swig_import_helper()
  File "/usr/local/lib/python3.8/site-packages/osgeo/gdal_array.py", line 16, in swig_import_helper
    return importlib.import_module('_gdal_array')
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal_array
```

**Comment by fechen123** [comment]
I experienced the same error on GDAL3.4.1: 

I built my own python3.8.10 and used "pip3 install numpy", then build GDAL with the python bindings. They are using the same version of gcc ( gcc version 8.4.1 20200928 (Red Hat 8.4.1-1.0.1) (GCC)). 

When I execute gdal_merge.py built above from another environment that has python 3.8.3, I got this error: 

_gdal_array.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK11GDALDataset14GetFieldDomainERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

What could have caused this issue? GDAL built from python 3.8.10 cannot be invoked using python 3.8.3?



> ok, that was tricky... The issue is that the manylinux2010_x86_64 uses a gcc configured to use the old C++ ABI (-D_GLIBCXX_USE_CXX11_ABI=0), but the python:3.8 image uses GCC 10 with the new C++ ABI. Hence the C++ symbols are exported in a difference way, which cause issues with the gdal_array module which uses GDAL C++ API. A workaround I found was the following hack to force the GDAL Python bindings to be built with the old C++ ABI.
> 
> ```
> RUN pip install numpy
> RUN printf "#!/bin/sh\ngcc -D_GLIBCXX_USE_CXX11_ABI=0 \$*\n" > /tmp/mygcc.sh && chmod +x /tmp/mygcc.sh
> RUN CC=/tmp/mygcc.sh pip install -vvv GDAL==${GDAL_VERSION};
> ```
> 
> But perhaps you should upgrade your manylinux to manylinux2014.
