### ISSUE TITLE
gdal_sieve.py fails on GeoTIFF without NoData value, version 3.4.0

### ISSUE THREAD

**Issue by jirik** [OSGeo/gdal#4899]
## Expected behavior and actual behavior.

gdal_sieve.py should run successfully with input GeoTIFF without NoData value. However it fails with this message:
```
Traceback (most recent call last):
  File "/usr/bin/gdal_sieve.py", line 11, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_sieve.py", line 113, in main
    return gdal_sieve(src_filename=src_filename, dst_filename=dst_filename, driver_name=driver_name,
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_sieve.py", line 175, in gdal_sieve
    dstband.SetNoDataValue(srcband.GetNoDataValue())
  File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 3777, in SetNoDataValue
    return _gdal.Band_SetNoDataValue(self, *args)
TypeError: in method 'Band_SetNoDataValue', argument 2 of type 'double'
```

It's broken in docker image `osgeo/gdal:ubuntu-small-3.4.0`, but it works in `osgeo/gdal:ubuntu-small-3.3.2`

I think it's because of this change: https://github.com/OSGeo/gdal/commit/86de2ac49b57a62ce6cc22bac368ade3a7768302#diff-cdebd9f7f232dc52e76ea0a3fa916b6b65d2feca714ca6f98de7a0c74fe5eb66 It does not take into account GeoTIFF files witout NoData values.

## Steps to reproduce the problem.

```
gdal_sieve.py -nomask -st 10000 -4 input.tif output.tif
```

## Operating system

Docker image `osgeo/gdal:ubuntu-small-3.4.0`

## GDAL version and provenance

Docker image `osgeo/gdal:ubuntu-small-3.4.0`

**Comment by jirik** [comment]
@rouault Thanks for quick fix!
