### ISSUE TITLE
VSICurlClearCache leaks memory from CPLMalloc and CPLRealloc

### ISSUE THREAD

**Issue by simoneves** [OSGeo/gdal#5457]
## Expected behavior and actual behavior.

Calls to `VSICurlClearCache()` seem to leak. Our ASAN builds report this, which goes away when our (only) call to that method is removed.

This has been introduced since GDAL 3.2.2 which does not appear to have the issue.

I will look at the GDAL code myself, but not today. Reporting it for now in case it's an obvious (to the devs) problem.

```
==33219==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 960 byte(s) in 2 object(s) allocated from:
    #0 0x7feb86139c3e in __interceptor_realloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:163
    #1 0x7feb7797d62f in CPLRealloc /home/simon.eves/work/pr/omniscidb-internal/scripts/gdal-3.4.1/port/cpl_conv.cpp:253

Indirect leak of 616 byte(s) in 48 object(s) allocated from:
    #0 0x7feb86139808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x7feb7797e1a5 in CPLMalloc /home/simon.eves/work/pr/omniscidb-internal/scripts/gdal-3.4.1/port/cpl_conv.cpp:190

```

## Operating system

Ubuntu 20.04

## GDAL version and provenance

3.4.1

**Comment by simoneves** [comment]
That was fast. Thank you! We'll patch our build.
