### ISSUE TITLE
Failure warping in-memory VRTs

### ISSUE THREAD

**Issue by tbonfort** [OSGeo/gdal#5533]
The following example raises a `ERROR 4: : No such file or directory` error although the resulting file is (correctly?) created:

```c++
#include <gdal.h>
#include <gdal_utils.h>

GDALDatasetH make_band_vrt(GDALDatasetH inds, char *band) {
   char *opts[] = {"-b",band,"-of","VRT",NULL};
	GDALTranslateOptions *translateopts = GDALTranslateOptionsNew(opts,nullptr);
	int usageErr=0;
	GDALDatasetH ret = GDALTranslate("", inds, translateopts, &usageErr);
	GDALTranslateOptionsFree(translateopts);
   return ret;
}
int main(int argc, char **argv) {
   GDALAllRegister();
   GDALDriverH hDriver = GDALGetDriverByName("GTiff");
   GDALDatasetH hTIFDS = GDALCreate( hDriver, "6b.tif", 512, 512, 6, GDT_Byte, NULL);
   GDALSetProjection(hTIFDS,"+proj=lonlat");
   double gt[] = {45,0.001,0,30,0,-0.001};
   GDALSetGeoTransform(hTIFDS,gt);
   GDALClose(hTIFDS);
   hTIFDS = GDALOpen("6b.tif", GA_ReadOnly);
   GDALDatasetH sources[] = {make_band_vrt(hTIFDS,"1"),
   make_band_vrt(hTIFDS,"2"),
   make_band_vrt(hTIFDS,"3"),
   make_band_vrt(hTIFDS,"4"),
   make_band_vrt(hTIFDS,"5"),
   make_band_vrt(hTIFDS,"6")};

   char *opts[]={"-separate",nullptr};
	GDALBuildVRTOptions *ropts = GDALBuildVRTOptionsNew(opts,nullptr);
	int usageErr=0;
	GDALDatasetH hVRTDS = GDALBuildVRT("", 6, sources, nullptr, ropts, &usageErr);
 
	GDALWarpAppOptions *warpopts = GDALWarpAppOptionsNew(nullptr,nullptr);
	GDALDatasetH ret = GDALWarp("6bwarped.tif", nullptr, 1, &hVRTDS, warpopts, &usageErr);
	GDALWarpAppOptionsFree(warpopts);
   GDALClose(ret);
   GDALClose(hVRTDS);
   for(int i=0;i<6;i++) {
      GDALClose(sources[i]);
   }
   GDALClose(hTIFDS);
}
```

Here is the backtrace of CPLError:
```
#0  CPLError (eErrClass=CE_Failure, err_no=4, fmt=0x7ffff7890362 "%s") at /home/tbonfort/dev/thirdparty/gdal/port/cpl_error.cpp:312
#1  0x00007ffff66b24fd in VSIToCPLError (eErrClass=CE_Failure, eDefaultErrorNo=4)
    at /home/tbonfort/dev/thirdparty/gdal/port/cpl_vsi_error.cpp:280
#2  0x00007ffff76b06b6 in GDALOpenEx (pszFilename=0x5555556525e0 "", nOpenFlags=66, papszAllowedDrivers=0x0, papszOpenOptions=0x0, 
    papszSiblingFiles=0x0) at /home/tbonfort/dev/thirdparty/gdal/gcore/gdaldataset.cpp:3663
#3  0x00007ffff6a50b01 in GDALDataset::Open (pszFilename=0x5555556525e0 "", nOpenFlags=66, papszAllowedDrivers=0x0, 
    papszOpenOptions=0x0, papszSiblingFiles=0x0) at /home/tbonfort/dev/thirdparty/gdal/gcore/gdal_priv.h:661
#4  0x00007ffff7719901 in GDALDatasetPool::_RefDataset (this=0x55555571ebf0, pszFileName=0x5555556525e0 "", eAccess=GA_ReadOnly, 
    papszOpenOptions=0x0, bShared=1, bForceOpen=true, pszOwner=0x0) at /home/tbonfort/dev/thirdparty/gdal/gcore/gdalproxypool.cpp:355
#5  0x00007ffff771a010 in GDALDatasetPool::RefDataset (pszFileName=0x5555556525e0 "", eAccess=GA_ReadOnly, papszOpenOptions=0x0, 
    bShared=1, bForceOpen=true, pszOwner=0x0) at /home/tbonfort/dev/thirdparty/gdal/gcore/gdalproxypool.cpp:503
#6  0x00007ffff771af74 in GDALProxyPoolDataset::RefUnderlyingDataset (this=0x5555556525c0, bForceOpen=true)
    at /home/tbonfort/dev/thirdparty/gdal/gcore/gdalproxypool.cpp:816
#7  0x00007ffff771bfdd in GDALProxyPoolRasterBand::RefUnderlyingRasterBand (this=0x55555592d720, bForceOpen=true)
    at /home/tbonfort/dev/thirdparty/gdal/gcore/gdalproxypool.cpp:1217
#8  0x00007ffff771c0b9 in GDALProxyPoolRasterBand::RefUnderlyingRasterBand (this=0x55555592d720)
    at /home/tbonfort/dev/thirdparty/gdal/gcore/gdalproxypool.cpp:1243
#9  0x00007ffff7718913 in GDALProxyRasterBand::GetOverviewCount (this=0x55555592d720)
    at /home/tbonfort/dev/thirdparty/gdal/gcore/gdalproxydataset.cpp:387
#10 0x00007ffff6b85eed in CheckBandForOverview (poBand=0x5555559fe280, poFirstBand=@0x7fffffffd668: 0x0, 
    nOverviews=@0x7fffffffd650: 0, apoOverviewsBak=std::vector of length 1, capacity 1 = {...})
    at /home/tbonfort/dev/thirdparty/gdal/frmts/vrt/vrtdataset.cpp:2009
#11 0x00007ffff6b86356 in VRTDataset::BuildVirtualOverviews (this=0x55555571d710)
    at /home/tbonfort/dev/thirdparty/gdal/frmts/vrt/vrtdataset.cpp:2040
#12 0x00007ffff6b63acc in VRTRasterBand::GetOverviewCount (this=0x5555559fe280)
    at /home/tbonfort/dev/thirdparty/gdal/frmts/vrt/vrtrasterband.cpp:1302
#13 0x00007ffff78293a4 in GDALWarpDirect (pszDest=0x55555555604c "6bwarped.tif", hDstDS=0x5555555a4bf0, nSrcCount=1, 
    pahSrcDS=0x7fffffffdb70, psOptions=0x555555703fc0, pbUsageError=0x7fffffffdb68)
    at /home/tbonfort/dev/thirdparty/gdal/apps/gdalwarp_lib.cpp:2487
#14 0x00007ffff782560f in GDALWarp (pszDest=0x55555555604c "6bwarped.tif", hDstDS=0x0, nSrcCount=1, pahSrcDS=0x7fffffffdb70, 
    psOptionsIn=0x555555703eb0, pbUsageError=0x7fffffffdb68) at /home/tbonfort/dev/thirdparty/gdal/apps/gdalwarp_lib.cpp:1293
```

**Comment by rouault** [comment]
Fixed per https://github.com/OSGeo/gdal/pull/5536
