### ISSUE TITLE
numpy is installed after gdal when we do pip install gdal[numpy] ImportError: cannot import name '_gdal_array' from 'osgeo'

### ISSUE THREAD

**Issue by NoharaMasato** [OSGeo/gdal#5844]
## Expected behavior and actual behavior.
- Expected behavior:
gdal is installed after `numpy` when we run `pip install gdal[numpy]`

- actual behavior:
gdal is installed before `numpy`.

## Steps to reproduce the problem.
```bash
$ python3 -V
Python 3.9.12
# create clean environment using virtualenv
$ pip install virtualenv
$ python3 -m virtualenv venv
$ source venv/bin/activate
$ pip install --no-cache gdal[numpy]
$ python3
>>> from osgeo import gdal_array
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/masato.nohara/Desktop/spacemaps/pipeline/LNG/venv/lib/python3.9/site-packages/osgeo/gdal_array.py", line 13, in <module>
    from . import _gdal_array
ImportError: cannot import name '_gdal_array' from 'osgeo' ([mypath]/venv/lib/python3.9/site-packages/osgeo/__init__.py)
>>>
```

## Related issues and PRs
- https://github.com/jazzband/pip-tools/issues/992
- https://github.com/OSGeo/gdal/pull/2281
- https://github.com/OSGeo/gdal/issues/2158

## Operating system
- Mac OS Montery 12.2.1

## GDAL version and provenance
```bash
$ gdal-config --version
3.5.0
$ pip show gdal
Name: GDAL
Version: 3.5.0
Summary: GDAL: Geospatial Data Abstraction Library
Home-page: http://www.gdal.org
Author: Frank Warmerdam
Author-email: warmerdam@pobox.com
License: MIT
Location: [mypath]/lib/python3.9/site-packages
Requires:
Required-by:
```

**Comment by rouault** [comment]
This has been fixed in a 3.5.0.3 patch release of the gdal pip package:
```
$ pip install --no-cache gdal[numpy]
Collecting gdal[numpy]
  Downloading GDAL-3.5.0.3.tar.gz (745 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 745.2/745.2 KB 2.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting numpy>1.0.0
  Downloading numpy-1.22.4-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 2.0 MB/s eta 0:00:00
Building wheels for collected packages: gdal
  Building wheel for gdal (setup.py) ... done
  Created wheel for gdal: filename=GDAL-3.5.0.3-cp38-cp38-linux_x86_64.whl size=2787740 sha256=daf71558e9f0a47ef9840eb45515ed74e47e92f6bd0de78f7bc10e4222b44fbd
  Stored in directory: /tmp/pip-ephem-wheel-cache-5qxo2nd7/wheels/ae/2c/c9/a84661ca3b52265c26dee46272177483359a11f9fed2ae7c10
Successfully built gdal
Installing collected packages: numpy, gdal
Successfully installed gdal-3.5.0.3 numpy-1.22.4
```
