### ISSUE TITLE
ogr.Geometry.Within returns True when using invalid geometry

### ISSUE THREAD

**Issue by cpaulik** [OSGeo/gdal#598]
## Expected behavior and actual behavior.

It should raise an error like e.g. shapely does or at least return `None`.

## Steps to reproduce the problem.

The following code shows the problem. I load the two `geojson` files which are available at [this gist](https://gist.github.com/cpaulik/9ce76906edadff41d2efeb9036668a13) and convert them to a geometry. This is done instead of reading the with ogr directly because I normally get them as a string in our system.

Conversion to shapely objects raises an error because the second collection contains a self intersecting polygon.

``` python
import json
from osgeo import ogr
import shapely
import shapely.wkb
import shapely.validation
import gdal

gdal.UseExceptions()

def geojson_to_geom(geojson):
    """
    Convert a geojson object or objects into a OGR Geometry.

    Parameters
    ----------
    geojson: list or string or dict
        geojson strings or dicts. Either one or a list of them.

    Returns
    -------
    geom: ogr.Geometry
        GeoJSON as geometry
    """
    geom = ogr.Geometry(ogr.wkbGeometryCollection)

    if type(geojson) is not list:
        geojson = [geojson]
    for geojson_el in geojson:
        if type(geojson_el) == dict:
            geojson_el = json.dumps(geojson_el)
            geom.AddGeometry(ogr.CreateGeometryFromJson(geojson_el))
    return geom

def within_geojson(geojson_shape, geojson_area_allowed):

    shape_geom = geojson_to_geom(geojson_shape)
    area_allowed_geom = geojson_to_geom(geojson_area_allowed)
    print 'shape_geom within area_allowed_geom', shape_geom.Within(area_allowed_geom)


    shape_shapely = shapely.wkb.loads(shape_geom.ExportToWkb())
    area_allowed_shapely = shapely.wkb.loads(area_allowed_geom.ExportToWkb())
    print shapely.validation.explain_validity(area_allowed_shapely)
    print shape_shapely.is_valid
    print shapely.validation.explain_validity(shape_shapely)
    print shape_shapely.within(area_allowed_shapely)

geojson_aa = json.loads(open('area_allowed.geojson').read())
geojson_shape = json.loads(open('roi_shape.geojson').read())
within = within_geojson(geojson_shape, geojson_aa)
assert within == False
```

### script output

```
shape_geom within area_allowed_geom True
Valid Geometry
False
Self-intersection[118.876735 -32.028315]
No handlers could be found for logger "shapely.geos"
Traceback (most recent call last):
  File "geojson_intersection.py", line 53, in <module>
    within_geojson(geojson_shape, geojson_aa)
  File "geojson_intersection.py", line 48, in within_geojson
    print shape_shapely.within(area_allowed_shapely)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/onesat/lib/python2.7/site-packages/shapely/geometry/base.py", line 723, in within
    return bool(self.impl['within'](self, other))
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/onesat/lib/python2.7/site-packages/shapely/predicates.py", line 18, in __call__
    self._check_topology(err, this, other)
  File "/home/cpa/.pyenv/versions/miniconda2-4.3.30/envs/onesat/lib/python2.7/site-packages/shapely/topology.py", line 38, in _check_topology
    self.fn.__name__, repr(geom)))
shapely.errors.TopologicalError: The operation 'GEOSWithin_r' could not be performed. Likely cause is invalidity of the geometry <shapely.geometry.collection.GeometryCollection object at 0x7fe939d51dd0>
```

## Operating system

I've seen this on Arch and Ubuntu 16.04

## GDAL version and provenance

gdal                      2.2.3                    py27_0    conda-forge

**Comment by rouault** [comment]
You can.should call Geometry.IsValid() before if you are uncertain of the geometry validity. OGR just wraps the underlying GEOS calls and GEOS doesn't check validity (as this might be a costly operation).
I'll add some notes in the documentation of that function and similar ones

**Comment by cpaulik** [comment]
Thanks. That is really good to know.
