### ISSUE TITLE
ModuleNotFoundError: No module named '_gdal'

### ISSUE THREAD

**Issue by cuiyc2000** [OSGeo/gdal#6275]
## Expected behavior and actual behavior.

import  osgeo, it returns an error message:

```
Traceback (most recent call last):
  File "/Users/cuiyc/opt/anaconda3/envs/minio/lib/python3.10/site-packages/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "/Users/cuiyc/opt/anaconda3/envs/minio/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: dlopen(/Users/cuiyc/opt/anaconda3/envs/minio/lib/python3.10/site-packages/osgeo/_gdal.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '_CPLDefaultErrorHandler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cuiyc/bigdata/minio/py/minio/test.py", line 1, in <module>
    from osgeo import gdal
  File "/Users/cuiyc/opt/anaconda3/envs/minio/lib/python3.10/site-packages/osgeo/__init__.py", line 46, in <module>
    _gdal = swig_import_helper()
  File "/Users/cuiyc/opt/anaconda3/envs/minio/lib/python3.10/site-packages/osgeo/__init__.py", line 43, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/Users/cuiyc/opt/anaconda3/envs/minio/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'

Process finished with exit code 1

```

## Steps to reproduce the problem.

install
```
brew install gdal
conda create -n gdalenv python=3.10
conda activate gdalenv
pip install gdal
```

run
```
from osgeo import gdal
# or
import osgeo
```

## Operating system

MAC OS 12.4

## GDAL version and provenance

gdal-3.5.1

**Comment by rouault** [comment]
sounds like a usage issue / mix-up in your setup

**Comment by cuiyc2000** [comment]
> sounds like a usage issue / mix-up in your setup

Hi @rouaul. The brew and pip install version are both 3.5.1. Can you describe it in detail? How can I correct this error? Thank you

**Comment by rouault** [comment]
likely by using only the gdal python package of conda, and not trying to mess up with pip & brew

**Comment by cuiyc2000** [comment]
> likely by using only the gdal python package of conda, and not trying to mess up with pip & brew

Thanks. @rouault I'll try. But as you can see, I have installed gdal using pip and brew. Will current state of the environment affect the coda installation？

**Comment by rouault** [comment]
> Will current state of the environment affect the coda installation？

I'm not familiar enough with OSX and all those package managers to reliably tell...

**Comment by cuiyc2000** [comment]
> > Will current state of the environment affect the coda installation？
> 
> 
> 
> I'm not familiar enough with OSX and all those package managers to reliably tell...

Well, nevertheless, thank you very much for your help
