### ISSUE TITLE
Installation Issues: Docker GDAL 3.6 + pyarrow

### ISSUE THREAD

**Issue by snowman2** [OSGeo/gdal#6698]
The libarrow wheels don't go well with GDAL:
```
docker run -it osgeo/gdal:ubuntu-full-3.6.0 /bin/bash
```
```bash
apt-get update
apt-get install -y python3-pip
python -m pip install pyarrow
```
```
root@0afffa859617:/# python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> pyarrow.show_versions()
pyarrow version info
--------------------
Package kind              : python-wheel-manylinux2014
Arrow C++ library version : 10.0.0  
Arrow C++ compiler        : GNU 10.2.1
Arrow C++ compiler flags  :  -fdiagnostics-color=always -O2 -DNDEBUG -ftree-vectorize
Arrow C++ git revision    : 89f9a0948961f6e94f1ef5e4f310b707d22a3c11
Arrow C++ git description :         
Arrow C++ build type      : release 
```
```
root@0afffa859617:/# python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /usr/local/lib/python3.10/dist-packages/pyarrow/libarrow_python.so.1000: undefined symbol: _ZNK5arrow8DataType18ComputeFingerprintEv

```
```
root@0afffa859617:/# python
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> from osgeo import gdal
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/osgeo/__init__.py", line 30, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 674, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1176, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: /lib/x86_64-linux-gnu/libgdal.so.32: undefined symbol: _ZN5arrow2fs10FileSystem13NormalizePathENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/osgeo/__init__.py", line 46, in <module>
    _gdal = swig_import_helper()
  File "/usr/lib/python3/dist-packages/osgeo/__init__.py", line 43, in swig_import_helper
    return importlib.import_module('_gdal')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_gdal'
```
Currently working on installing `pyarrow` from source to avoid this. No success yet (https://issues.apache.org/jira/browse/ARROW-18322)

**Comment by snowman2** [comment]
Side note: Using pyarrow==9.0.0 wheels, the issue is resolved.

Hopefully this is helpful for someone else's reference if they run into this.
