### ISSUE TITLE
3.6.0 Installation fails on Apple M1

### ISSUE THREAD

**Issue by pkage** [OSGeo/gdal#6700]
## Expected behavior and actual behavior.

Expected behavior: installation of GDAL via Pip: 

```
$ pip install gdal==3.6.0
# ... successful installation ....
```

Actual behavior: Wheel build failure

```
$ pip install gdal==3.6.0
Collecting gdal==3.6.0
  Using cached GDAL-3.6.0.tar.gz (757 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/tiler-ytFWLohN-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/tiler-ytFWLohN-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/patrick/Library/Caches/pypoetry/virtualenvs/tiler-ytFWLohN-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/pm/dvglhyn133sbzgg266kj4kqr0000gn/T/pip-build-env-ifxh2bik/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/pm/dvglhyn133sbzgg266kj4kqr0000gn/T/pip-build-env-ifxh2bik/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/pm/dvglhyn133sbzgg266kj4kqr0000gn/T/pip-build-env-ifxh2bik/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 483, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/private/var/folders/pm/dvglhyn133sbzgg266kj4kqr0000gn/T/pip-build-env-ifxh2bik/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 145, in <module>
        File "<string>", line 63, in get_numpy_include
      AttributeError: 'dict' object has no attribute '__NUMPY_SETUP__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
```

Installation of 3.5.3 via `pip install gdal==3.5.3` does work, so this seems to be a regression.

## Steps to reproduce the problem.

Installation of GDAL in a clean virtualenv:

```
$ python3 -m venv env_gdal
$ source env_gdal/bin/activate
$ pip install gdal==3.6.0
```

## Operating system

macOS Monterey (12.3.1), running Python 3.10.8

## GDAL version and provenance

version 3.6.0 from PyPI.

**Comment by rouault** [comment]
Is the version of the native GDAL library 3.6.0 ? If not, the error is expected, as the pip gdal module doesn't provide a binary wheel.
Do you have numpy installed ?

**Comment by rouault** [comment]
I suspect https://github.com/conda-forge/gdal-feedstock/commit/c56c727cd5997fbec3156fc0ee9dc1b8497131ff should fix this

**Comment by pkage** [comment]
Ah that's probably it, I installed the native library with `brew install gdal`, but i assumed that to install `3.6.0` but it looks like it's on `3.5.3`. I do have NumPy installed, adding it to the virtualenv didn't affect the install errors so I omitted it from the repro steps.

**Comment by rouault** [comment]
@pkage  Would you mind testing "pip install GDAL-3.6.0.tar.gz" with [GDAL-3.6.0.tar.gz](https://github.com/OSGeo/gdal/files/10007507/GDAL-3.6.0.tar.gz) being patched with the fix of https://github.com/OSGeo/gdal/pull/6702 ?  (this will likely fail at some point if your native libgdal is still 3.5.3, but it should get over the ``'dict' object has no attribute '__NUMPY_SETUP__'`` error)

**Comment by rouault** [comment]
A 3.6.0.1 pip release has been made with the fix: https://pypi.org/project/GDAL/3.6.0.1/
