### ISSUE TITLE
When an SQLITE sql statement returns no rows, the VectorTranslate output file is often missing or invalid 

### ISSUE THREAD

**Issue by theroggy** [OSGeo/gdal#6976]
## Expected behavior and actual behavior.

When using VectorTranslate to run an sql statement of the 'SQLITE' dialect on an empty file, the sql statement doesn't return any rows or if the geometries returned by the query is NULL, often there is either no output file or the output file is invalid.
The expected behaviour would be that in all situations a valid output file/layer would be written, containing the columns consistent with the sql query but no rows.
In some cases it might be unclear which geometry type the output file should have, but when an output geometry type is specified I guess this should never be an issue?

There are a lot of different situations leading to different outputs, so I ended up writing a script thats lists many situations and its results. I'll post a comment with the full listing + a comment with the script.

The big lines:
- for some SQLITE sql statements, if they start with '\n', '\t' or ' ' and the input file is an empty (no rows) .shp file, no output file will be created. If the statement doesn't start like that, output is ok.
- if a simple SQLITE sql statement starts with '\n' or '\t' and the input file is an empty (no rows) .gpkg file, the output file will be invalid, if the simple sql statement doesn't start with these, the output is OK.
- when a SQLITE sql statement is ran on an empty (no rows) .gpkg file, an invalid .gpkg is created (when it is opened, an exception is thrown that the file is "not recognized as a supported file format"
- when a SQLITE sql statement is ran on a .gpkg file and it returns no rows or NULL geometries, depending on whether (output)geometrytype is specified or not another variant of invalid output file is written.
- if NULL geometries are returned when running the SQLITE sql statement on a .gpkg, in some cases VectorTranslate throws an exception. In all other cases no exception is thrown.

## Steps to reproduce the problem.

Script in following comment.

## Operating system

Windows 10.

## GDAL version and provenance

gdal 3.6.1 installed from conda-forge (build py39h3be0312_1)

**Comment by theroggy** [comment]
Script to test many situations:
```
import logging
import os
from pathlib import Path
import shutil

from osgeo import gdal
import osgeo.ogr as ogr
import osgeo.osr as osr

logging.basicConfig(level=logging.DEBUG)
gdal.UseExceptions()
# gdal.ConfigurePythonLogging(logger_name="gdal", enable_debug=True)
# os.environ["CPL_LOG_ERRORS"] = "ON"


def run_test(driver, src_empty, sql_descr, sql, sql_prefix, dir="."):
    # Prepare empty test input file
    # -----------------------------
    dir = Path(dir)
    shutil.rmtree(dir)
    dir.mkdir(parents=True, exist_ok=True)
    if driver == "GPKG":
        suffix = ".gpkg"
        geometrycolumn = "geom"
    else:
        suffix = ".shp"
        geometrycolumn = "geometry"

    src_stem = "point_empty" if src_empty else "point"
    src = dir / f"{src_stem}{suffix}"

    # Create datasource
    ogr_driver = ogr.GetDriverByName(driver)
    data_source = ogr_driver.CreateDataSource(str(src))

    # Create layer
    srs = osr.SpatialReference()
    srs.ImportFromEPSG(4326)
    layer = data_source.CreateLayer(src.stem, srs, ogr.wkbPoint)
    field_name = ogr.FieldDefn("name", ogr.OFTString)
    field_name.SetWidth(24)
    layer.CreateField(field_name)

    if not src_empty:
        # create a feature
        feature = ogr.Feature(layer.GetLayerDefn())
        feature.SetField("Name", "test")
        point = ogr.CreateGeometryFromWkt("POINT(1.0 1.0)")
        feature.SetGeometry(point)
        layer.CreateFeature(feature)
        feature = None

    # Save and close the datasource
    data_source = None

    # Run tests
    # ---------
    if sql is None:
        # No sql statement: no use running for each prefix, geometrytype
        if sql_prefix == "" and geometrytype is None:
            run_translate(src, src_empty, sql_descr)
    else:
        # Run sql
        sql = sql.format(sql_prefix=sql_prefix, geometrycolumn=geometrycolumn, src=src)
        run_translate(src, src_empty, sql_descr, sql, sql_prefix, geometrytype)


def run_translate(
    src: Path, src_empty: bool, sql_descr: str, sql=None, sql_prefix="", geometrytype=None
):
    # Init
    descr = sql_descr
    if geometrytype is not None:
        descr = f"{descr}_{geometrytype}"

    # Prepare sql_prefix for printing
    if sql_prefix == "\t":
        sql_prefix_print = "TAB"
    elif sql_prefix == "\n":
        sql_prefix_print = "NEWLINE"
    else:
        sql_prefix_print = f"{sql_prefix}"
    ex_str = "no"
    dst_file = "???"

    # Prepare + check output path
    dst = src.parent / f"{src.stem}_out_{descr}_{sql_prefix_print}{src.suffix}"
    if dst.exists():
        raise ValueError(f"output path exists already, stop: {dst}")

    try:
        result_ds = gdal.VectorTranslate(
            destNameOrDestDS=str(dst),
            srcDS=str(src),
            SQLStatement=sql,
            SQLDialect="SQLITE",
            layerName="empty_output",
            geometryType=geometrytype,
        )
    except Exception as ex:
        ex_str = "YES"
    finally:
        result_ds = None

    if dst.exists():
        try:
            result_ds = gdal.OpenEx(str(dst))
            nb_layers = result_ds.GetLayerCount()
            if nb_layers == 0:
                dst_file = "not ok: 0 layers"
            else:
                layer = result_ds.GetLayer(0)
                geomtype = gdal.ogr.GeometryTypeToName(layer.GetGeomType())
                if geomtype == "None":
                    dst_file = "not ok: 1 layer but no geometry column"
                else:
                    dst_file = f"ok: 1 layer with {geomtype} column"
        except Exception as ex:
            dst_file = "invalid"
    else:
        dst_file = "not created"

    # Prepare tst description
    descr = descr.ljust(24, " ")
    sql_prefix_print = f"<{sql_prefix_print}>".ljust(10, " ")

    print(
        f"{descr}|{src.suffix.ljust(5, ' ')}|src_empty: {src_empty}|"
        f"sql_prefix: {sql_prefix_print}|dst_file: {dst_file}|exception: {ex_str}"
    )


if __name__ == "__main__":
    dir = r"C:\temp\gdaltest"

    # Prepare sql statements to test 
    sqls = []
    # Plain simple sql statement
    sql_descr = "sql_simple"
    sql = '{sql_prefix}SELECT {geometrycolumn}, name FROM "{src.stem}" layer'
    sqls.append((sql_descr, sql))
    # Sql statement returning NULL goms (if src file not empty)
    sql_descr = "sql_NULL_geoms"
    sql = (
        "{sql_prefix}SELECT ST_Buffer({geometrycolumn}, -1) as geom, name "
        'FROM "{src.stem}" layer '
    )
    sqls.append((sql_descr, sql))
    # Sql statement not returning any rows, even for non-empty src
    sql_descr = "sql_0_result_rows"
    sql = (
        "{sql_prefix}SELECT ST_Buffer({geometrycolumn}, -1) as geom, name "
        'FROM "{src.stem}" layer '
        "WHERE ST_Buffer({geometrycolumn}, -1) IS NOT NULL"
    )
    sqls.append((sql_descr, sql))

    for driver in ["GPKG", "ESRI Shapefile"]:
        for src_empty in [False, True]:
            for sql_descr, sql in sqls:
                for geometrytype in [None, "POINT"]:
                    for sql_prefix in ["", "\t", "\n", " "]:
                        run_test(
                            driver=driver,
                            src_empty=src_empty,
                            sql_descr=sql_descr,
                            sql=sql,
                            sql_prefix=sql_prefix,
                            dir=dir,
                        )
```

**Comment by theroggy** [comment]
Full listing of script output:
```
sql_simple              |.gpkg|src_empty: False|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.gpkg|src_empty: False|sql_prefix: <TAB>     |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.gpkg|src_empty: False|sql_prefix: <NEWLINE> |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.gpkg|src_empty: False|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.gpkg|src_empty: False|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.gpkg|src_empty: False|sql_prefix: <TAB>     |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.gpkg|src_empty: False|sql_prefix: <NEWLINE> |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.gpkg|src_empty: False|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms          |.gpkg|src_empty: False|sql_prefix: <>        |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_NULL_geoms          |.gpkg|src_empty: False|sql_prefix: <TAB>     |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_NULL_geoms          |.gpkg|src_empty: False|sql_prefix: <NEWLINE> |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_NULL_geoms          |.gpkg|src_empty: False|sql_prefix: < >       |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_NULL_geoms_POINT    |.gpkg|src_empty: False|sql_prefix: <>        |dst_file: invalid|exception: YES
sql_NULL_geoms_POINT    |.gpkg|src_empty: False|sql_prefix: <TAB>     |dst_file: invalid|exception: YES
sql_NULL_geoms_POINT    |.gpkg|src_empty: False|sql_prefix: <NEWLINE> |dst_file: invalid|exception: YES
sql_NULL_geoms_POINT    |.gpkg|src_empty: False|sql_prefix: < >       |dst_file: invalid|exception: YES
sql_0_result_rows       |.gpkg|src_empty: False|sql_prefix: <>        |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_0_result_rows       |.gpkg|src_empty: False|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_0_result_rows       |.gpkg|src_empty: False|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
sql_0_result_rows       |.gpkg|src_empty: False|sql_prefix: < >       |dst_file: not ok: 1 layer but no geometry column|exception: no
Exception ignored in: <built-in function delete_Dataset>
Traceback (most recent call last):
  File "c:\Users\PIEROG\Projects\github\geofileops\tmp\testcases\bug_gdal_sql_emptyinput.py", line 103, in run_translate
    result_ds = None
RuntimeError: failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "empty_output" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom"): no such table: empty_output
sql_0_result_rows_POINT |.gpkg|src_empty: False|sql_prefix: <>        |dst_file: invalid|exception: no
sql_0_result_rows_POINT |.gpkg|src_empty: False|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_0_result_rows_POINT |.gpkg|src_empty: False|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
Exception ignored in: <built-in function delete_Dataset>
Traceback (most recent call last):
  File "c:\Users\PIEROG\Projects\github\geofileops\tmp\testcases\bug_gdal_sql_emptyinput.py", line 103, in run_translate
    result_ds = None
RuntimeError: failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "empty_output" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom"): no such table: empty_output
sql_0_result_rows_POINT |.gpkg|src_empty: False|sql_prefix: < >       |dst_file: invalid|exception: no
sql_simple              |.gpkg|src_empty: True|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.gpkg|src_empty: True|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_simple              |.gpkg|src_empty: True|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
sql_simple              |.gpkg|src_empty: True|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.gpkg|src_empty: True|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.gpkg|src_empty: True|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_simple_POINT        |.gpkg|src_empty: True|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
sql_simple_POINT        |.gpkg|src_empty: True|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms          |.gpkg|src_empty: True|sql_prefix: <>        |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_NULL_geoms          |.gpkg|src_empty: True|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_NULL_geoms          |.gpkg|src_empty: True|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
sql_NULL_geoms          |.gpkg|src_empty: True|sql_prefix: < >       |dst_file: not ok: 1 layer but no geometry column|exception: no
Exception ignored in: <built-in function delete_Dataset>
Traceback (most recent call last):
  File "c:\Users\PIEROG\Projects\github\geofileops\tmp\testcases\bug_gdal_sql_emptyinput.py", line 103, in run_translate
    result_ds = None
RuntimeError: failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "empty_output" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom"): no such table: empty_output
sql_NULL_geoms_POINT    |.gpkg|src_empty: True|sql_prefix: <>        |dst_file: invalid|exception: no
sql_NULL_geoms_POINT    |.gpkg|src_empty: True|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_NULL_geoms_POINT    |.gpkg|src_empty: True|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
Exception ignored in: <built-in function delete_Dataset>
Traceback (most recent call last):
  File "c:\Users\PIEROG\Projects\github\geofileops\tmp\testcases\bug_gdal_sql_emptyinput.py", line 103, in run_translate
    result_ds = None
RuntimeError: failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "empty_output" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom"): no such table: empty_output
sql_NULL_geoms_POINT    |.gpkg|src_empty: True|sql_prefix: < >       |dst_file: invalid|exception: no
sql_0_result_rows       |.gpkg|src_empty: True|sql_prefix: <>        |dst_file: not ok: 1 layer but no geometry column|exception: no
sql_0_result_rows       |.gpkg|src_empty: True|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_0_result_rows       |.gpkg|src_empty: True|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
sql_0_result_rows       |.gpkg|src_empty: True|sql_prefix: < >       |dst_file: not ok: 1 layer but no geometry column|exception: no
Exception ignored in: <built-in function delete_Dataset>
Traceback (most recent call last):
  File "c:\Users\PIEROG\Projects\github\geofileops\tmp\testcases\bug_gdal_sql_emptyinput.py", line 103, in run_translate
    result_ds = None
RuntimeError: failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "empty_output" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom"): no such table: empty_output
sql_0_result_rows_POINT |.gpkg|src_empty: True|sql_prefix: <>        |dst_file: invalid|exception: no
sql_0_result_rows_POINT |.gpkg|src_empty: True|sql_prefix: <TAB>     |dst_file: invalid|exception: no
sql_0_result_rows_POINT |.gpkg|src_empty: True|sql_prefix: <NEWLINE> |dst_file: invalid|exception: no
Exception ignored in: <built-in function delete_Dataset>
Traceback (most recent call last):
  File "c:\Users\PIEROG\Projects\github\geofileops\tmp\testcases\bug_gdal_sql_emptyinput.py", line 103, in run_translate
    result_ds = None
RuntimeError: failed to prepare SQL: SELECT "fid", ST_MinX("geom"), ST_MaxX("geom"), ST_MinY("geom"), ST_MaxY("geom") FROM "empty_output" WHERE "geom" NOT NULL AND NOT ST_IsEmpty("geom"): no such table: empty_output
sql_0_result_rows_POINT |.gpkg|src_empty: True|sql_prefix: < >       |dst_file: invalid|exception: no
sql_simple              |.shp |src_empty: False|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.shp |src_empty: False|sql_prefix: <TAB>     |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.shp |src_empty: False|sql_prefix: <NEWLINE> |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.shp |src_empty: False|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.shp |src_empty: False|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.shp |src_empty: False|sql_prefix: <TAB>     |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.shp |src_empty: False|sql_prefix: <NEWLINE> |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.shp |src_empty: False|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms          |.shp |src_empty: False|sql_prefix: <>        |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: False|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: False|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: False|sql_prefix: < >       |dst_file: not created|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: False|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: False|sql_prefix: <TAB>     |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: False|sql_prefix: <NEWLINE> |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: False|sql_prefix: < >       |dst_file: ok: 1 layer with Point column|exception: no
sql_0_result_rows       |.shp |src_empty: False|sql_prefix: <>        |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: False|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: False|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: False|sql_prefix: < >       |dst_file: not created|exception: no
sql_0_result_rows_POINT |.shp |src_empty: False|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_0_result_rows_POINT |.shp |src_empty: False|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_0_result_rows_POINT |.shp |src_empty: False|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_0_result_rows_POINT |.shp |src_empty: False|sql_prefix: < >       |dst_file: not created|exception: no
sql_simple              |.shp |src_empty: True|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple              |.shp |src_empty: True|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_simple              |.shp |src_empty: True|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_simple              |.shp |src_empty: True|sql_prefix: < >       |dst_file: not created|exception: no
sql_simple_POINT        |.shp |src_empty: True|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_simple_POINT        |.shp |src_empty: True|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_simple_POINT        |.shp |src_empty: True|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_simple_POINT        |.shp |src_empty: True|sql_prefix: < >       |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: True|sql_prefix: <>        |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: True|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: True|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_NULL_geoms          |.shp |src_empty: True|sql_prefix: < >       |dst_file: not created|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: True|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: True|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: True|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_NULL_geoms_POINT    |.shp |src_empty: True|sql_prefix: < >       |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: True|sql_prefix: <>        |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: True|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: True|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_0_result_rows       |.shp |src_empty: True|sql_prefix: < >       |dst_file: not created|exception: no
sql_0_result_rows_POINT |.shp |src_empty: True|sql_prefix: <>        |dst_file: ok: 1 layer with Point column|exception: no
sql_0_result_rows_POINT |.shp |src_empty: True|sql_prefix: <TAB>     |dst_file: not created|exception: no
sql_0_result_rows_POINT |.shp |src_empty: True|sql_prefix: <NEWLINE> |dst_file: not created|exception: no
sql_0_result_rows_POINT |.shp |src_empty: True|sql_prefix: < >       |dst_file: not created|exception: no
```

**Comment by rouault** [comment]
> * for some SQLITE sql statements, if they start with '\n', '\t' or ' ' and the input file is an empty (no rows) .shp file, no output file will be created. If the statement doesn't start like that, output is ok.
> 
> * if a simple SQLITE sql statement starts with '\n' or '\t' and the input file is an empty (no rows) .gpkg file, the output file will be invalid, if the simple sql statement doesn't start with these, the output is OK.

Issues fixed per https://github.com/OSGeo/gdal/pull/6979

The other issues comes from the fact that SQLite SQL is loosely typed, and thus if ST_Buffer() doesn't return any row or a row with a NULL value, there's no way we can know it is of geometry type. Thus those issues can't be fixed (or would require considerable effort workarounding SQLite design)
