### ISSUE TITLE
QGIS crash while opening VNP46A2 product

### ISSUE THREAD

**Issue by lnicola** [OSGeo/gdal#7340]
Sorry, unfortunately I don't have a self-contained reproducer, and it might be pretty specific to my HDF5 version.
I didn't file this against QGIS since it's unlikely to be caused by it, but you never know.

## Expected behavior and actual behavior.

Open the attached file in QGIS. [VNP46A2.A2022352.h20v04.001.2022360162337.zip](https://github.com/OSGeo/gdal/files/10873667/VNP46A2.A2022352.h20v04.001.2022360162337.zip)

On my computer I get a crash like:

```
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/Snow_Flag. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/QF_Cloud_Mask. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/Mandatory_Quality_Flag. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/Latest_High_Quality_Retrieval. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/Gap_Filled_DNB_BRDF-Corrected_NTL. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/DNB_Lunar_Irradiance. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
GDAL ERROR 1: Unable to compute a transformation between pixel/line and georeferenced coordinates for HDF5:"/mnt/large/VNP46A2/VNP46A2.A2022352.h20v04.001.2022360162337.h5"://HDFEOS/GRIDS/VNP_Grid_DNB/Data_Fields/DNB_BRDF-Corrected_NTL. There is no affine transformation and no GCPs. Specify transformation option SRC_METHOD=NO_GEOTRANSFORM to bypass this check.
[New Thread 0x7fffe52706c0 (LWP 383904)]
[New Thread 0x7ffef813a6c0 (LWP 383905)]
[New Thread 0x7ffeef9396c0 (LWP 383906)]
[New Thread 0x7ffef79396c0 (LWP 383907)]
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5P.c line 247 in H5Pcreate(): unable to create property list
    major: Property lists
    minor: Unable to create file
  #001: H5Pint.c line 1855 in H5P_create_id(): unable to create property list
    major: Property lists
    minor: Unable to create file
  #002: H5Pint.c line 1769 in H5P__create(): can't insert property into seen skip list
    major: Property lists
    minor: Unable to insert object
  #003: H5SL.c line 1051 in H5SL_insert(): can't create new skip list node
    major: Skip Lists
    minor: Unable to insert object
  #004: H5SL.c line 720 in H5SL__insert_common(): can't insert duplicate key
    major: Skip Lists
    minor: Unable to insert object
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5Pfapl.c line 978 in H5Pset_driver(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5F.c line 607 in H5Fopen(): not a file access property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5P.c line 1490 in H5Pclose(): not a property list
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.12.2) thread 0:
  #000: H5Gdeprec.c line 950 in H5Gget_objinfo(): can't get info for object: '/'
    major: Symbol table
    minor: Can't get value
  #001: H5VLcallback.c line 4517 in H5VL_group_optional(): can't reset VOL wrapper info
    major: Virtual Object Layer
    minor: Can't reset object
  #002: H5VLint.c line 2358 in H5VL_reset_vol_wrapper(): no VOL object wrap context?
    major: Virtual Object Layer
    minor: Bad value
  #003: H5L.c line 3152 in H5L_get_info(): name doesn't exist
    major: Links
    minor: Object already exists
  #004: H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #4294967294: (null) line 754 in (null)()
    major: Symbol table
    minor: Can't move to next iterator location
  #4294967295: (null) line 3114 in (null)()
    major: Links
    minor: Object not found

Thread 35 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff767fc6c0 (LWP 383850)]
__memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:342
Downloading source file /usr/src/debug/glibc/glibc/string/../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S
342		vmovdqu	(%rsi), %xmm0                                                                                                                                                          
(gdb) bt
#0  __memcpy_avx_unaligned_erms () at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:342
#1  0x00007fff94465829 in  () at /usr/lib/libhdf5.so.200
#2  0x00007fff94467a05 in H5SL_insert () at /usr/lib/libhdf5.so.200
#3  0x00007fff9440cc4a in H5P_create_id () at /usr/lib/libhdf5.so.200
#4  0x00007fff943e2800 in H5Pcreate () at /usr/lib/libhdf5.so.200
#5  0x00007fff7c18fcb5 in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#6  0x00007fff7c195479 in  () at /usr/lib/gdalplugins/gdal_HDF5.so
#7  0x00007fffefdd22cd in GDALOpenEx () at /usr/lib/libgdal.so.32
#8  0x00007ffff2f0531d in  () at /usr/lib/libqgis_core.so.3.28.3
#9  0x00007ffff2f12f81 in  () at /usr/lib/libqgis_core.so.3.28.3
#10 0x00007ffff2f18b08 in  () at /usr/lib/libqgis_core.so.3.28.3
#11 0x00007ffff34709d4 in QgsSingleBandGrayRenderer::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.28.3
#12 0x00007ffff344eb9d in QgsBrightnessContrastFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.28.3
#13 0x00007ffff344ef75 in QgsHueSaturationFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.28.3
#14 0x00007ffff346fc74 in QgsRasterResampleFilter::block(int, QgsRectangle const&, int, int, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.28.3
#15 0x00007ffff3424b47 in QgsRasterIterator::readNextRasterPartInternal(int, int&, int&, std::unique_ptr<QgsRasterBlock, std::default_delete<QgsRasterBlock> >*, int&, int&, QgsRectangle*) ()
    at /usr/lib/libqgis_core.so.3.28.3
#16 0x00007ffff3463fb3 in QgsRasterDrawer::draw(QPainter*, QgsRasterViewPort*, QgsMapToPixel const*, QgsRasterBlockFeedback*) () at /usr/lib/libqgis_core.so.3.28.3
#17 0x00007ffff344d36a in QgsRasterLayerRenderer::render() () at /usr/lib/libqgis_core.so.3.28.3
#18 0x00007ffff3351480 in QgsMapRendererParallelJob::renderLayerStatic(LayerRenderJob&) () at /usr/lib/libqgis_core.so.3.28.3
```

Possibly hardware-dependent, too.

## Steps to reproduce the problem.

`qgis VNP46A2.A2022352.h20v04.001.2022360162337.h5`

## Operating system

Arch Linux

## GDAL version and provenance

 - gdal 3.6.2-2.1
 - hdf5 1.12.2-1.1

Both from the distro repository.

**Comment by agiudiceandrea** [comment]
The issue doesn't occur using QGIS 3.28.3 (GDAL/OGR 3.6.2 - HDF5 1.10.7) on Windows (OSGeo4W).

**Comment by lnicola** [comment]
As an extra data point, I can also reproduce it in the Flatpak version (3.28.3).

**Comment by agiudiceandrea** [comment]
QGIS from Flatpak is currently using HDF5 1.12.1 https://github.com/flathub/org.qgis.qgis/blob/master/org.qgis.qgis.json#L369.

**Comment by lnicola** [comment]
And also crashes in 3.22.12 (using the same HDF5 1.12.1).

**Comment by rouault** [comment]
I could reproduce on Linux Alpine with HDF5 1.12.2 package. The issue is not that much the version, but the fact that the HDF5 library is built without thread-safety enabled. https://github.com/OSGeo/gdal/pull/7357 works around that on GDAL side
