### ISSUE TITLE
How to access HDFS file using "gdal.Open"? The method of "/vsihdfs/hdfs://" has failed.

### ISSUE THREAD

**Issue by JenniferYingyiWu2020** [OSGeo/gdal#7632]
Hi,
    I've uploaded a ".tif" image to HDFS cluster, and it can be accessed by "hdfs dfs -ls hdfs://rsMaster:9000/NC_H08_20180715_1230_R21_FLDK.06001_06001.tif".
-rw-r--r--   2 yunyao yunyao      78058 2023-04-06 14:42 hdfs://rsMaster:9000/NC_H08_20180715_1230_R21_FLDK.06001_06001.tif
    However, I'm unable to access it using following codes:    

from osgeo import gdal, osr, ogr, gdalconst

inpath = "/vsihdfs/hdfs://rsMaster:9000/NC_H08_20180715_1230_R21_FLDK.06001_06001.tif"
ds = gdal.Open(inpath)

band = ds.RasterCount  # 波段数
geoTransform = ds.GetGeoTransform()  # 坐标系
proj = ds.GetProjection()  # 投影

hdfsListDirectory(hdfs://rsMaster:9000): FileSystem#listStatus error:
IllegalArgumentException: Pathname  from hdfs://rsMaster:9000 is not a valid DFS filename.java.lang.IllegalArgumentException: Pathname  from hdfs://rsMaster:9000 is not a valid DFS filename.
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:243)
	at org.apache.hadoop.hdfs.DistributedFileSystem.listStatusInternal(DistributedFileSystem.java:1052)
	at org.apache.hadoop.hdfs.DistributedFileSystem.access$1000(DistributedFileSystem.java:131)
	at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1119)
	at org.apache.hadoop.hdfs.DistributedFileSystem$24.doCall(DistributedFileSystem.java:1116)
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
	at org.apache.hadoop.hdfs.DistributedFileSystem.listStatus(DistributedFileSystem.java:1126)

    So, could you pls help to give me some suggestions? Thanks!

**Comment by rouault** [comment]
adressed per https://github.com/OSGeo/gdal/pull/7638

**Comment by jamesmcclain** [comment]
@JenniferYingyiWu2020 JenniferYingyiWu2020 @rouault I am sorry, I missed this ping for a couple of days.  It looks as though the issue has been successfully resolved?  Please let me know if I can be of assistance.

**Comment by JenniferYingyiWu2020** [comment]
Hi, the issue still exist! When I type "ds = gdal.Open("/vsihdfs/hdfs:/NC_H08_20180715_1230_R21_FLDK.06001_06001.tif")", the line can be executed. Also, "ds.RasterCount" and "proj = ds.GetProjection()" can print the result data.
>>> import gdal
>>> from osgeo import gdal_array, osr

>>> ds = gdal.Open("/vsihdfs/hdfs:/NC_H08_20180715_1230_R21_FLDK.06001_06001.tif")

>>> band = ds.RasterCount
>>> band
21

>>> proj = ds.GetProjection() 
>>> proj
'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433],AUTHORITY["EPSG","4326"]]'

    However, when I run "proj = ds.GetProjection()", the following errors appear:
>>> proj = ds.GetProjection()
hdfsListDirectory(hdfs:): constructNewObjectOfPath error:
URISyntaxException: Expected scheme-specific part at index 5: hdfs:java.lang.IllegalArgumentException: java.net.URISyntaxException: Expected scheme-specific part at index 5: hdfs:
	at org.apache.hadoop.fs.Path.initialize(Path.java:259)
	at org.apache.hadoop.fs.Path.<init>(Path.java:217)
Caused by: java.net.URISyntaxException: Expected scheme-specific part at index 5: hdfs:
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.failExpecting(URI.java:2853)
	at java.net.URI$Parser.parse(URI.java:3056)
	at java.net.URI.<init>(URI.java:746)
	at org.apache.hadoop.fs.Path.initialize(Path.java:256)
	... 1 more

    So, could you pls help to give me some suggestions? Thanks!

**Comment by jamesmcclain** [comment]
@JenniferYingyiWu2020 I am not equipped to reproduce this at the moment, but my recollection is that a properly-formatted HDFS URI would be of the form `hdfs://namenode.example.com:8020/user/data/input`.  With that in mind, please try `/vsihdfs/hdfs://NC_H08_20180715_1230_R21_FLDK.06001_06001.tif` (with two forward slashes after the `hdfs://`).  If that fails, please post another stack trace.
