### ISSUE TITLE
Update to GDAL 3.6.3 `ENABLE_HDF5_GLOBAL_LOCK `might be interfering with tensorflow

### ISSUE THREAD

**Issue by 2320sharon** [OSGeo/gdal#7698]
Hello,

Thank you for all your hard work improving and maintaining gdal.

My team has been using gdal and tensorflow in the same conda environment for awhile now with no issues until the release of gdal 3.6.3 which added `GDAL_ENABLE_HDF5_GLOBAL_LOCK` [build option to gdal](https://github.com/OSGeo/gdal/pull/7357). 

## Expected behavior and actual behavior.
I created a fresh anaconda environment using the steps I have included in section **Steps to reproduce the problem** with version 3.6.4 of `gdal` from the conda-forge channel and the most recent version of tensorflow 2.12.0. I ran the standalone script I have included below and when the code attempts to load the model weights files saved as .h5 files it fails claiming `h5py` was not installed (see the outputs of the standalone script). The strange thing is the `h5py` package is installed in the environment (see the contents of conda list), but I've realized that both `gdal` and `tensorflow` use it. Before the 3.6.3 update to gdal the .h5 files would correctly load into the model.

The error message leads me to believe that this [recent update to gdal  which places a lock on the hdf5 library at build time](https://github.com/OSGeo/gdal/pull/7357) could be the cause of this issue. I looked at the [conda forge feedstock  recipe for gdal ](https://github.com/conda-forge/gdal-feedstock/blob/main/recipe/meta.yaml) and I noticed that hdf5 is present in the conda package for the gdal I am installing from conda-forge. Is it possible that since the `hdf5` is present at build time a lock is being placed that is preventing tensorflow from importing the `hdf5` and `h5py` packages properly?

### 1. Anaconda Environment to reproduce the issue
```bash
conda create -n test_env python=3.10
conda activate test_env
conda install -c conda-forge gdal==3.6.4
pip install tensorflow==2.12.0
python test_script.py

```
### 2. Run the Standalone code to reproduce the issue I have below
```bash
(test_env) > python sample_model.py
```

## Standalone code to reproduce the issue
```python
from osgeo import gdal

import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
# Create a simple model

model = Sequential([
Dense(64, activation='relu', input_shape=(32,)),
Dense(10)
])
# Compile the model

model.compile(optimizer='adam',
loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
metrics=['accuracy'])

# Print the model summary

model.summary()

# Save the initial weights to a file

model.save_weights('my_model_weights.h5')

# Change the weights of the model

for layer in model.layers:
weights = layer.get_weights()  # list of numpy arrays
weights = [weight * 0 for weight in weights]
layer.set_weights(weights)

# Check that weights have been changed

print('Weights after resetting:')
print(model.layers[0].get_weights())

# Load the initial weights from the file

model.load_weights('my_model_weights.h5')

# Check that weights have been loaded

print('Weights after loading from file:')
print(model.layers[0].get_weights())
```

## Operating system

Windows 10 version 22H2
Reproducible Example was created in an anaconda environment with the instructions above.

## GDAL version and provenance

GDAL version 3.6.4 installed from conda-forge

## Outputs of Script
- As you can see in the outputs of running `conda list` that I have included below, the `hdf5` and `h5py` packages exist in the environment which has led me to believe that this [recent update to gdal  which places a lock on the hdf5 library at build time](https://github.com/OSGeo/gdal/pull/7357) could be the cause of this issue. I looked at the [conda forge feedstock  recipe for gdal ](https://github.com/conda-forge/gdal-feedstock/blob/main/recipe/meta.yaml) and I noticed that hdf5 is present in the conda package for gdal I am installing too. Is it possible that since the hdf5 is present at build time a lock is being placed that is preventing tensorflow from importing the `hdf5` and `h5py` packages properly?
```python

(test_env) > python sample_model.py
Model: "sequential"
# Layer (type) Output Shape Param #

dense (Dense)               (None, 64)                2112

dense_1 (Dense)             (None, 10)                650

=================================================================
Total params: 2,762
Trainable params: 2,762
Non-trainable params: 0

---

Traceback (most recent call last):
File "C:\1_USGS\1_CoastSeg\1_official_CoastSeg_repo\CoastSeg\src\coastseg\sample_model.py", line 22, in <module>
model.save_weights('my_model_weights.h5')
File "C:\Users\Sharon\anaconda3\envs\test_env\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
raise e.with_traceback(filtered_tb) from None
File "C:\Users\Sharon\anaconda3\envs\test_env\lib\site-packages\keras\saving\legacy\[save.py](http://save.py/)", line 351, in save_weights
raise ImportError(
ImportError: `save_weights` requires h5py when saving in hdf5, but h5py is not available. Try installing h5py package.
```

## Output of Conda List
```
# Name                    Version                   Build  Channel
absl-py                   1.4.0                    pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blosc                     1.21.3               h6c2663c_0
boost-cpp                 1.74.0               h5b4e17d_6    conda-forge
bzip2                     1.0.8                he774522_0
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.3.0                    pypi_0    pypi
cairo                     1.16.0            h63a05c6_1001    conda-forge
certifi                   2022.12.7                pypi_0    pypi
cfitsio                   3.470                h2bbff1b_7
charset-normalizer        3.1.0                    pypi_0    pypi
curl                      7.88.1               h2bbff1b_0
expat                     2.5.0                h63175ca_1    conda-forge
flatbuffers               23.3.3                   pypi_0    pypi
fontconfig                2.14.1               h9c4af85_2
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
gast                      0.4.0                    pypi_0    pypi
gdal                      3.6.2           py310h1c2bfe4_1
geos                      3.8.0                h33f27b4_0
geotiff                   1.7.0                h4545760_1
glib                      2.69.1               h5dc1a3c_2
google-auth               2.17.3                   pypi_0    pypi
google-auth-oauthlib      1.0.0                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.54.0                   pypi_0    pypi
h5py                      3.8.0                    pypi_0    pypi
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.6          nompi_h5268f04_1114    conda-forge
icu                       58.2                 ha925a31_3
idna                      3.4                      pypi_0    pypi
intel-openmp              2023.1.0         h57928b3_46319    conda-forge
jax                       0.4.8                    pypi_0    pypi
jpeg                      9e                   h8ffe710_2    conda-forge
kealib                    1.5.0                hde4a422_0
keras                     2.12.0                   pypi_0    pypi
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h83e58a3_0
lerc                      3.0                  hd77b12b_0
libblas                   3.9.0                     8_mkl    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  16.0.0                   pypi_0    pypi
libcurl                   7.88.1               h86230a5_0
libdeflate                1.17                 h2bbff1b_0
libexpat                  2.5.0                h63175ca_1    conda-forge
libffi                    3.4.2                hd77b12b_6
libgdal                   3.6.2                h11d7215_1
libiconv                  1.17                 h8ffe710_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libnetcdf                 4.8.1                h6685c40_2
libpng                    1.6.39               h8cc25b3_0
libpq                     12.9                 hb652d5d_3
libspatialite             4.3.0a              h6ec8781_23
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.5.0                h6c2663c_2
libwebp-base              1.2.4                h2bbff1b_1
libxml2                   2.10.3               h0ad7f3c_0
libzip                    1.8.0                h49b8836_0
lz4-c                     1.9.4                h2bbff1b_0
markdown                  3.4.3                    pypi_0    pypi
markupsafe                2.1.2                    pypi_0    pypi
mkl                       2020.4             hb70f87d_311    conda-forge
ml-dtypes                 0.1.0                    pypi_0    pypi
numpy                     1.22.3          py310hed7ac4c_2    conda-forge
oauthlib                  3.2.2                    pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0
openssl                   1.1.1t               h2bbff1b_0
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 23.1                     pypi_0    pypi
pcre                      8.45                 h0e60522_0    conda-forge
pcre2                     10.37                h0ff8eda_1
pip                       23.0.1          py310haa95532_0
pixman                    0.38.0            hfa6e2cd_1003    conda-forge
poppler                   22.12.0              h268424c_0
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                12.9                 hb652d5d_3
proj                      6.2.1                h3758d61_0
protobuf                  4.22.3                   pypi_0    pypi
pyasn1                    0.5.0                    pypi_0    pypi
pyasn1-modules            0.3.0                    pypi_0    pypi
python                    3.10.11              h966fe2a_2
python_abi                3.10                    2_cp310    conda-forge
qhull                     2020.2               h70d2c02_2    conda-forge
requests                  2.29.0                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                66.0.0          py310haa95532_0
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h2bbff1b_0
tensorboard               2.12.2                   pypi_0    pypi
tensorboard-data-server   0.7.0                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.12.0                   pypi_0    pypi
tensorflow-estimator      2.12.0                   pypi_0    pypi
tensorflow-intel          2.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi
termcolor                 2.3.0                    pypi_0    pypi
tiledb                    2.3.3                h3649cd2_2
tk                        8.6.12               h2bbff1b_0
typing-extensions         4.5.0                    pypi_0    pypi
tzdata                    2023c                h04d1e81_0
urllib3                   1.26.15                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
werkzeug                  2.3.3                    pypi_0    pypi
wheel                     0.38.4          py310haa95532_0
wrapt                     1.14.1                   pypi_0    pypi
xerces-c                  3.2.4                hd77b12b_0
xz                        5.2.10               h8cc25b3_1
zlib                      1.2.13               h8cc25b3_0
zstd                      1.5.5                hd43e919_0
```

**Comment by rouault** [comment]
I strongly doubt your issue is related to the GDAL_ENABLE_HDF5_GLOBAL_LOCK change, which only influences the runtime behaviour of the GDAL HDF5 driver and ask him to take mutex around calls to the HDF5 native library.
Your sample code doesn't use GDAL at all, beyond loading it.
What I suspect is that you have 2 copies of HDF5 native library, one loaded with GDAL coming from the hdf5 conda-forge package and another one bundled with the h5py pypi package as a silent implementation detail. The fact that it worked with GDAL 3.6.3 was probably just a lucky accident.
You should try to install h5py and/or tensorflow from conda-forge rather than pypi, so that all packages use the same HDF5 native library.

**Comment by 2320sharon** [comment]
@rouault Thank you for suggesting I look into h5py more. You were correct that the version of h5py installed from pypi was messing with version installed by conda-forge's  gdal version. I performed a pip uninstall of h5py then installed it with conda-forge and it worked. Thank you again for your help!

For anyone experiencing a similar issue here is what fixed the issue:
```
conda create -n mock_env python=3.10 
conda activate mock_env
conda install -c conda-forge gdal==3.6.4 (this was the latest version at the time of writing this)
pip install tensorflow
pip uninstall h5py
conda install -c conda-forge h5py

```
