### ISSUE TITLE
gdal2tiles.py, unknown/invalid value for --s_crs should give an error

### ISSUE THREAD

**Issue by velle** [OSGeo/gdal#8331]
## Steps to reproduce the problem.

I have a geotiff in epsg:25832, called input_25832.tif. 

**Reads input as epsg:25832:**

1. `$ gdal2tiles.py input_25832.tif tiles`
2. `$ gdal2tiles.py input_25832.tif tiles --s_srs=epsg:25832`

**Reads input as epsg:3857 (aka pseudo-mercator):**

3. `$ gdal2tiles.py input_25832.tif tiles --s_srs=epsg25832`
4. `$ gdal2tiles.py input_25832.tif tiles --s_srs=foobar`
5. `$ gdal2tiles.py input_25832.tif tiles --s_srs=epsg:3857`

If mistyping a CRS, there is no indication, error or warning, it just defaults to epsg:3857. The appropriate / expected behavior would be to display an error and quit, IMO. 

## System details:

GDAL 3.4.1
Ubuntu 22.04.3 LTS

I have both 3.4.1 (default version for Ubuntu install via APT) and 3.7.0 (home compiled) installed. I tried calling 3.7.0, but after looking closer the Python script actually does use 3.4.1.

**Comment by velle** [comment]
I managed (after hours of work) to install 3.7.0 properly, by compiling from source. It behaves differently and if supplying an unknown crs, it gives:

```
Traceback (most recent call last):
  File "/home/jdoe/gdal-3.7.0/swig/python/gdal-utils/scripts/gdal2tiles.py", line 17, in <module>
    sys.exit(main(sys.argv, called_from_main=True))
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4518, in main
    return submain(argv, called_from_main=called_from_main)
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4537, in submain
    single_threaded_tiling(input_file, output_folder, options)
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4374, in single_threaded_tiling
    conf, tile_details = worker_tile_details(input_file, output_folder, options)
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 4292, in worker_tile_details
    gdal2tiles.open_input()
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 2185, in open_input
    self.in_srs, self.in_srs_wkt = setup_input_srs(input_dataset, self.options)
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo_utils/gdal2tiles.py", line 1019, in setup_input_srs
    input_srs.SetFromUserInput(options.s_srs)
  File "/home/jdoe/.local/lib/python3.10/site-packages/osgeo/osr.py", line 832, in SetFromUserInput
    return _osr.SpatialReference_SetFromUserInput(self, *args)
RuntimeError: OGR Error: Corrupt data
```
Not exactly the best feedback for the user, but at least its better than no error :)

**Comment by velle** [comment]
@rouault Thanks :)
