### ISSUE TITLE
python bindings fail to compile version 3.8.0 or 3.8.1 if prior version (e.g. 3.7.4) installed on system

### ISSUE THREAD

**Issue by ArTourter** [OSGeo/gdal#8882]
I maintain the slackware gdal slackbuild script on the slackbuilds.org project and since version 3.8.0, building gdal fails if the previous version in installed as it seems to prioritise the system `libgdal.so` rather than the one just compiled.

If one removes the installed version of gdal and recompile, it detects and uses the built version of `libgdal.so` and builds the python bindings.

## Expected behavior and actual behavior.

The build system should used the newly compiled version of `libgdal.so` rather than any already installed version on the system.

## Steps to reproduce the problem.

build and install gdal 3.7.4
Try to build gdal 3.8.x with python buildings

`./configure` will work but `make` with eventually fail with:

```
Traceback (most recent call last):
  File "/tmp/sbopkg.goi0J3/gdal-3.8.1/build/swig/python/setup.py", line 360, in <module>
    setup(
  File "/usr/lib64/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.9/site-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib64/python3.9/distutils/command/install.py", line 546, in run
    self.run_command('build')
  File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.9/distutils/dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "/usr/lib64/python3.9/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "/tmp/sbopkg.goi0J3/gdal-3.8.1/build/swig/python/setup.py", line 235, in finalize_options
    raise Exception(f"Python bindings of GDAL {version} require at least libgdal {version}, but {library_version} was found")
Exception: Python bindings of GDAL 3.8.1 require at least libgdal 3.8.1, but 3.7.3 was found
CMake Error at swig/python/install_python.cmake:28 (message):
  Installation of python bindings failed
Call Stack (most recent call first):
  swig/python/cmake_install.cmake:46 (include)
  swig/cmake_install.cmake:47 (include)
  cmake_install.cmake:116 (include)
```

## Operating system

Slackware Linux 15.0 (and -current)

## GDAL version and provenance

version 3.8.x from github

**Comment by GuiAlDuS** [comment]
I'm having the same issue on Arch, using [this PKGBUILD ](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gdal-hdf4)updated to github's gdal 3.8.1 file and md5

**Comment by rouault** [comment]
Proposed fix in https://github.com/OSGeo/gdal/pull/8883 (wait for CI tests to have passed...)

Otherwise a workaround is to set the PATH to "${BUILD_DIR}/apps;%PATH%" before running make, so that the generated gdal-config is used

**Comment by GuiAlDuS** [comment]
I'm trying to compile over this commit but end up having this other error at 95%:

```
[ 95%] Linking CXX executable test_ogrsf
[ 95%] Built target test_ogrsf
[ 95%] Built target gdal_plugins
[ 95%] Building CXX object autotest/cpp/CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o
cc1plus: error: too many filenames given; type ‘cc1plus --help’ for usage

```

**Comment by rouault** [comment]
> I'm trying to compile over this commit but end up having this other error at 95%:

weird, can you "make VERBOSE=1" ?

**Comment by GuiAlDuS** [comment]
Yes, here is the output of the last two stages:

```
[ 95%] Linking CXX executable test_ogrsf
cd /home/gds506/AUR_packages/gdal-hdf4/src/build/apps && /usr/bin/cmake -E cmake_link_script CMakeFiles/test_ogrsf.dir/link.txt --verbose=1
/usr/bin/c++ -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fvisibility=hidden -flto=auto -fno-fat-lto-objects -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now CMakeFiles/test_ogrsf.dir/test_ogrsf.cpp.o -o test_ogrsf  -Wl,-rpath,/home/gds506/AUR_packages/gdal-hdf4/src/build ../libgdal.so.34.3.9.0 
make[2]: Leaving directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
[ 95%] Built target test_ogrsf
make  -f CMakeFiles/gdal_plugins.dir/build.make CMakeFiles/gdal_plugins.dir/depend
make[2]: Entering directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
cd /home/gds506/AUR_packages/gdal-hdf4/src/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/gds506/AUR_packages/gdal-hdf4/src/gdal /home/gds506/AUR_packages/gdal-hdf4/src/gdal /home/gds506/AUR_packages/gdal-hdf4/src/build /home/gds506/AUR_packages/gdal-hdf4/src/build /home/gds506/AUR_packages/gdal-hdf4/src/build/CMakeFiles/gdal_plugins.dir/DependInfo.cmake "--color="
make[2]: Leaving directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
make  -f CMakeFiles/gdal_plugins.dir/build.make CMakeFiles/gdal_plugins.dir/build
make[2]: Entering directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
make[2]: Nothing to be done for 'CMakeFiles/gdal_plugins.dir/build'.
make[2]: Leaving directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
[ 95%] Built target gdal_plugins
make  -f autotest/cpp/CMakeFiles/gdal_unit_test.dir/build.make autotest/cpp/CMakeFiles/gdal_unit_test.dir/depend
make[2]: Entering directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
cd /home/gds506/AUR_packages/gdal-hdf4/src/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/gds506/AUR_packages/gdal-hdf4/src/gdal /home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp /home/gds506/AUR_packages/gdal-hdf4/src/build /home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp /home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp/CMakeFiles/gdal_unit_test.dir/DependInfo.cmake "--color="
make[2]: Leaving directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
make  -f autotest/cpp/CMakeFiles/gdal_unit_test.dir/build.make autotest/cpp/CMakeFiles/gdal_unit_test.dir/build
make[2]: Entering directory '/home/gds506/AUR_packages/gdal-hdf4/src/build'
[ 95%] Building CXX object autotest/cpp/CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o
cd /home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp && /usr/bin/c++ -DDONT_DEPRECATE_SPRINTF -DGDAL_COMPILATION -DGDAL_TEST_ROOT_DIR=\"/home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest\" -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_CURL -DHAVE_GEOS=1 -DHAVE_SQLITE3 -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DPROJ_DB_TMPDIR=\"/home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp/proj_db_tmpdir\" -DPROJ_GRIDS_PATH=\"/home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp/../proj_grids\" -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/apps -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/alg -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/gcore -I/home/gds506/AUR_packages/gdal-hdf4/src/build/gcore -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/port -I/home/gds506/AUR_packages/gdal-hdf4/src/build/port -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/ogr -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/ogr/ogrsf_frmts -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/frmts -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/frmts/vrt -I/home/gds506/AUR_packages/gdal-hdf4/src/build/gcore/gdal_version_full -isystem /usr/include/geos -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,  -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fvisibility=hidden  -std=gnu++17 -flto=auto -fno-fat-lto-objects -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wextra-semi -Wfloat-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wsuggest-override -fno-operator-names -Wzero-as-null-pointer-constant -O0 -MD -MT autotest/cpp/CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -MF CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o.d -o CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -c /home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp/gdal_unit_test.cpp
cc1plus: error: too many filenames given; type ‘cc1plus --help’ for usage

```

**Comment by rouault** [comment]
do you also get the same error is you manually run the last line:
```
cd /home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp && /usr/bin/c++ -DDONT_DEPRECATE_SPRINTF -DGDAL_COMPILATION -DGDAL_TEST_ROOT_DIR=\"/home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest\" -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_CURL -DHAVE_GEOS=1 -DHAVE_SQLITE3 -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DPROJ_DB_TMPDIR=\"/home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp/proj_db_tmpdir\" -DPROJ_GRIDS_PATH=\"/home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp/../proj_grids\" -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/apps -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/alg -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/gcore -I/home/gds506/AUR_packages/gdal-hdf4/src/build/gcore -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/port -I/home/gds506/AUR_packages/gdal-hdf4/src/build/port -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/ogr -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/ogr/ogrsf_frmts -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/frmts -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/frmts/vrt -I/home/gds506/AUR_packages/gdal-hdf4/src/build/gcore/gdal_version_full -isystem /usr/include/geos -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,  -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fvisibility=hidden  -std=gnu++17 -flto=auto -fno-fat-lto-objects -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wextra-semi -Wfloat-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wsuggest-override -fno-operator-names -Wzero-as-null-pointer-constant -O0 -MD -MT autotest/cpp/CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -MF CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o.d -o CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -c /home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp/gdal_unit_test.cpp
```

**Comment by GuiAlDuS** [comment]
Yes I do: 

```
[gds506@linuxbox gdal-hdf4]$ cd /home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp && /usr/bin/c++ -DDONT_DEPRECATE_SPRINTF -DGDAL_COMPILATION -DGDAL_TEST_ROOT_DIR=\"/home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest\" -DGTEST_LINKED_AS_SHARED_LIBRARY=1 -DHAVE_AVX_AT_COMPILE_TIME -DHAVE_CURL -DHAVE_GEOS=1 -DHAVE_SQLITE3 -DHAVE_SSE_AT_COMPILE_TIME -DHAVE_SSSE3_AT_COMPILE_TIME -DPROJ_DB_TMPDIR=\"/home/gds506/AUR_packages/gdal-hdf4/src/build/autotest/cpp/proj_db_tmpdir\" -DPROJ_GRIDS_PATH=\"/home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp/../proj_grids\" -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/apps -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/alg -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/gcore -I/home/gds506/AUR_packages/gdal-hdf4/src/build/gcore -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/port -I/home/gds506/AUR_packages/gdal-hdf4/src/build/port -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/ogr -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/ogr/ogrsf_frmts -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/frmts -I/home/gds506/AUR_packages/gdal-hdf4/src/gdal/frmts/vrt -I/home/gds506/AUR_packages/gdal-hdf4/src/build/gcore/gdal_version_full -isystem /usr/include/geos -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,  -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -Wp,-D_GLIBCXX_ASSERTIONS -fvisibility=hidden  -std=gnu++17 -flto=auto -fno-fat-lto-objects -Wall -Wextra -Winit-self -Wunused-parameter -Wmissing-declarations -Wlogical-op -Wshadow -Wmissing-include-dirs -Wformat -Werror=format-security -Wno-format-nonliteral -Werror=vla -Wno-clobbered -Wdate-time -Wnull-dereference -Wextra-semi -Wfloat-conversion -Wnon-virtual-dtor -Woverloaded-virtual -Wsuggest-override -fno-operator-names -Wzero-as-null-pointer-constant -O0 -MD -MT autotest/cpp/CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -MF CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o.d -o CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -c /home/gds506/AUR_packages/gdal-hdf4/src/gdal/autotest/cpp/gdal_unit_test.cpp
cc1plus: error: too many filenames given; type ‘cc1plus --help’ for usage
^C
[gds506@linuxbox cpp]$ 

```

**Comment by rouault** [comment]
what if you try to remove `` -MD -MT autotest/cpp/CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o -MF CMakeFiles/gdal_unit_test.dir/gdal_unit_test.cpp.o.d`` from that line ?

**Comment by rouault** [comment]
maybe try to remove some of the -Wxxxxx flags ... ? That's really mysterious

**Comment by GuiAlDuS** [comment]
I guess if these spaces (and coma on -Wp) might bring the issue: 
![image](https://github.com/OSGeo/gdal/assets/6601878/39c659ff-f2c1-4f12-9f61-6cd149c15ee6)
