### ISSUE TITLE
Tracebacks not always appropriate

### ISSUE THREAD

**Issue by jidanni** [OSGeo/gdal#9534]
### Feature description

It seems
```
$ gdal_calc.py -A CLH.tif -B c6627.tif --outfile=aa.tif --calc="A & B"
RuntimeError: CLH.tif: No such file or directory
```
would be much clearer to the user than the current
```
$ gdal_calc.py -A CLH.tif -B c6627.tif --outfile=aa.tif --calc="A & B"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/osgeo_utils/auxiliary/gdal_argparse.py", line 226, in main
    self.doit(**kwargs)
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_calc.py", line 887, in doit
    return Calc(**kwargs)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osgeo_utils/gdal_calc.py", line 240, in Calc
    myFile = open_ds(filename)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osgeo_utils/auxiliary/util.py", line 125, in open_ds
    return ods.__enter__()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osgeo_utils/auxiliary/util.py", line 244, in __enter__
    self.ds = self._open_ds(self.filename, *self.args, **self.kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osgeo_utils/auxiliary/util.py", line 303, in _open_ds
    return gdal.OpenEx(str(filename), access_mode, open_options=open_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/osgeo/gdal.py", line 5998, in OpenEx
    return _gdal.OpenEx(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CLH.tif: No such file or directory
```
Therefore perhaps there are times when not showing full tracebacks is more appropriate.

**Comment by rouault** [comment]
Showing the traceback is also what other Python based packages, such as rasterio do:
``` 
$ rio info foo
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 302, in rasterio._base.DatasetBase.__init__
    # former, we put it into a list.
  File "rasterio/_base.pyx", line 213, in rasterio._base.open_dataset
    "Sibling files are not implemented")
  File "rasterio/_err.pyx", line 217, in rasterio._err.exc_wrap_pointer
    return retval
rasterio._err.CPLE_OpenFailedError: foo: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/even/.local/bin/rio", line 8, in <module>
    sys.exit(main_group())
  File "/home/even/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/even/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/even/.local/lib/python3.8/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/even/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/even/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/even/.local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/even/.local/lib/python3.8/site-packages/rasterio/rio/info.py", line 67, in info
    with ctx.obj['env'], rasterio.open(input) as src:
  File "/home/even/.local/lib/python3.8/site-packages/rasterio/env.py", line 442, in wrapper
    return f(*args, **kwds)
  File "/home/even/.local/lib/python3.8/site-packages/rasterio/__init__.py", line 277, in open
    dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
  File "rasterio/_base.pyx", line 304, in rasterio._base.DatasetBase.__init__
    driver = [driver]
rasterio.errors.RasterioIOError: foo: No such file or directory
```

**Comment by sgillies** [comment]
@rouault `rio info` in that case isn't doing what I prefer that Rasterio's CLI do. A "file not found" error is an ordinary kind of error and a one-line error message would be best.
