### ISSUE TITLE
Python: FieldDomain.GetEnumeration throws even with ogr.DontUseExceptions

### ISSUE THREAD

**Issue by dbaston** [OSGeo/gdal#9578]
### What is the bug?

An exception is thrown in addition to printing an error. I don't think that's the end of the world for this particular method but wanted to log the issue in case something more broad is going on.

### Steps to reproduce the issue

```
>>> ogr.DontUseExceptions()
>>> d = ogr.CreateRangeFieldDomain('my_range', None, ogr.OFTInteger, ogr.OFSTNone, 0, True, 3, True)
>>> d.GetEnumeration()
ERROR 1: This function should be called with a coded field domain object
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dan/dev/build-gdal-Desktop-Debug/swig/python/osgeo/ogr.py", line 7327, in GetEnumeration
    
RuntimeError: This function should be called with a coded field domain object
```

### Versions and provenance

master

**Comment by rouault** [comment]
I'd be keen to close this a wontfix as we don't encourage the DontUseExceptions() mode. While most of the time, exceptions are not emitted in that mode, there are circumstances where they are...
