### ISSUE TITLE
PMTiles: RuntimeError: Cannot decompress. Uncompressed buffer size should be at least 0

### ISSUE THREAD

**Issue by youngpm** [OSGeo/gdal#9646]
### What is the bug?

I'm encountering a `RuntimeError: Cannot decompress. Uncompressed buffer size should be at least 0` exception when trying to read of a very large pmtile file.  I'm working on trying to get a smaller pmtile file to reproduce the issue, but haven't succeeded yet; it seems when I do a `pmtiles extract`, things are happy in the extract.  I will add one once I succeed.

The area I am trying to read from has no tiles in it (XYZ coords = `(2048, 28672, 15)` in Antartica) and I'm reading it at a high zoom level (open option of `ZOOM_LEVEL=15`). Interestingly enough, it succeeds at `ZOOM_LEVEL=13`, so I am wondering if its somehow related to traversing the directory hierarchy.  

The `pmtile tile` command reports `Tile not found in archive.` as expected, and `pmtiles show` reports
```
pmtiles spec version: 3
tile type: Vector Protobuf (MVT)
bounds: (long: -180.000000, lat: -85.000000) (long: 180.000000, lat: 85.000000)
min zoom: 0
max zoom: 16
center: (long: 0.000000, lat: 0.000000)
center zoom: 0
addressed tiles count: 2092265146
tile entries count: 1284228501
tile contents count: 662255439
clustered: true
internal compression: 2
tile compression: 2
name mvts
scheme tms
minzoom 0
type overlay
vector_layers <object...>
version 2
description mvts for landcover layer
format pbf
maxzoom 16
```

Similarly, `ogrinfo` reports
```
INFO: Open of `<path to file>'
      using driver `PMTiles' successful.
Metadata:
  description=mvts for landcover layer
  format=pbf
  maxzoom=16
  minzoom=0
  name=mvts
  scheme=tms
  type=overlay
  version=2
  ZOOM_LEVEL=16
1: landcover
```

### Steps to reproduce the issue

Here's the script:
```
from osgeo import gdal, ogr
gdal.UseExceptions()

if __name__ == "__main__":
    pmtile_f = '<path to landcover pm tile file>'

    bounds_wkt = 'POLYGON ((-17531596.807488028 -15029354.2495445, -17531596.807488028 -15028131.257091936, -17532819.79994059 -15028131.257091936, -17532819.79994059 -15029354.2495445, -17531596.807488028 -15029354.2495445))'
    with gdal.OpenEx(pmtile_f, gdal.OF_VECTOR | gdal.OF_READONLY, open_options=[f'ZOOM_LEVEL=15']) as ds:
        spatial_filter = ogr.CreateGeometryFromWkt(bounds_wkt)
        with ds.ExecuteSQL('SELECT * FROM landcover', spatialFilter=spatial_filter) as lyr:
            for feat in lyr:
                break # no error!
```

### Versions and provenance

Reproducible in the `ghcr.io/osgeo/gdal:ubuntu-full-3.8.5` docker container.  Locally, I have a build of a recent version of `main` that also reproduces the error.

**Comment by rouault** [comment]
> so I am wondering if its somehow related to traversing the directory hierarchy.

The "Cannot decompress. Uncompressed buffer size should be at least" error indeed seems to confirm that. This error would tend to indicate that it tries to decompress tile data, whereas it shouldn't if there is no corresponding tile. You could probably reproduce the error by truncating the file to the end of the directory area (first megabytes or tens of megabytes)

**Comment by youngpm** [comment]
Alright truncation worked, file attached!  I did have to fill most of the truncated file with zeros so it would zip small and let me upload, unzipped it is about 244M!

Running `pmtiles tile tileset.pmtiles 15 2048 28672`, I get a `Tile not found in archive.` and it reads the following byte offset/size combos to get there after reading the header:
```
READ 127 13919
READ 255252802 254327
```

When I run that test script against this file, I see
```
RuntimeError: Cannot decompress. Uncompressed buffer size should be at least 0, offset and size 255252802 254327
```
where I added that little extra offset and size which matches what the `pmtiles` command reports, so I suppose it is trying to decompress the directory entry as a tile!

[tileset.pmtiles.zip](https://github.com/OSGeo/gdal/files/14895878/tileset.pmtiles.zip)

**Comment by rouault** [comment]
I believe there's an issue with this truncated dataset. The driver indeed tries to decode a directory starting at byte 255252802 and of of size 254327 at line 306 of ogrpmtilestilesiterator.cpp. It fails silently in decompressing it since the data there is only at 0. That failure likely causes downstream issues. So while there might be an issue with the nominal dataset, this truncated one probably exhibits an earlier issue.

**Comment by youngpm** [comment]
I did a little debugging of the original pmtile directly.

For a search of tile `ZXY = 15/2048/28672`, that converts to a hilbert `tileid = 725614591`. 

The root directory only contains entries that correspond to leaf directories for this file, and the leaf directory that could hold tile id`725614591` is `724762564` (here's the two adjacent entries from the root directory):

| tile id | offset (relative to leaf dir section) | length | run length |
| ---: | ---: | ---: | ---: |
|724762564 | 255238587 | 254327 | 0 |
|726819727 |255492914| 224858 |0|

Decoding the entries of that directory, the two entries before and after `725614591` are

| tile id | offset (relative to tile data section) | length | run length |
| ---: | ---: | ---: | ---: |
|725569338 |95993690310| 190 |1|
|725662687 |95993690500| 101 |1|

at which point we know the tile isn't in the dataset since its not explicitly in there nor does the run length of `725569338` cover it.

I ran the the script above against a debug build with the wkt set to just the tile centroid `POINT (-17532208.30371431 -15028742.753318219)` to try to make sure it only attempts to read `ZXY = 15/2048/28672` and see
```
S3: Using assumed role ...
S3: Downloading 0-16383 (...)...
S3: Got response_code=206
PMTiles: internal_compression = gzip
PMTiles: tile_compression = gzip
PMTiles: Metadata = {"description":"mvts for landcover layer","format":"pbf","maxzoom":"16","minzoom":"0","name":"mvts","scheme":"tms","type":"overlay","vector_layers":[{"fields":{"kind":"String"},"id":"landcover"}],"version":"2"}
PMTiles: minx=-1 miny=-1 maxx=-1 maxy=-1
S3: Downloading 148914176-149946367 (...)...
S3: Got response_code=206
S3: Downloading 74949836800-74949853183 (...)...
S3: Got response_code=206
GDAL: GDALOpen(/vsis3/.../tileset.pmtiles, this=0x117f941f0) succeeds as PMTiles.
PMTiles: minx=2048 miny=28672 maxx=2048 maxy=28672
S3: Downloading 255246336-255508479 (...)...
S3: Got response_code=206
GDAL: GDALClose(/vsis3/...tileset.pmtiles, this=0x117f941f0)
Traceback (most recent call last):
  File "pmtile_debug.py", line 18, in <module>
    for feat in lyr:
  File "/.../python3.12/site-packages/osgeo/ogr.py", line 2549, in __iter__
    feature = self.GetNextFeature()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/.../python3.12/site-packages/osgeo/ogr.py", line 1658, in GetNextFeature
    return _ogr.Layer_GetNextFeature(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Cannot decompress. Uncompressed buffer size should be at least 0, offset and size 255252802 254327
```

I don't fully understand the range requests it is making, below the first read is is the header and root directory:
```
S3: Downloading 0-16383 (...)...
PMTiles: minx=-1 miny=-1 maxx=-1 maxy=-1
```

Then we see these two reads that I don't understand:
```
S3: Downloading 148914176-149946367 (...)...
S3: Downloading 74949836800-74949853183 (...)...
```
In the root directory, that first range seems to cover this entry (the leaf directory offset is `14215` bytes from the start of the file, so the relative range read is `148899961 - 149932152` although I don't know why it isn't aligned):
```
| tile id | (relative to leaf dir section) | length | run length |
|351348566 |148914062| 1012510| 0|
```
and second read is in the region where the tiles are found so seems like its snagging a tile.  In the test file, this range did get zero'd out, but I don't know why GDAL is trying to read this region at all, that entry is `14/15248/3665` so not a parent tile or some such).

Finally, there's another read right before we fail in the vicinity of the directory we are interested in:
```
GDAL: GDALOpen(/vsis3/.../tileset.pmtiles, this=0x117f941f0) succeeds as PMTiles.
PMTiles: minx=2048 miny=28672 maxx=2048 maxy=28672
S3: Downloading 255246336-255508479 (...)...
```
which also covers the range for the leaf directory where the tile we seek should be, but it tries to decode that directory as a tile.

**Comment by youngpm** [comment]
I've attached another attempt at a truncated file, but made sure to not zero out that `148914176-149946367` section as well.  When I run it, I get the same result
[tileset2.pmtiles.zip](https://github.com/OSGeo/gdal/files/14910568/tileset2.pmtiles.zip)
 although now with a bunch of
```
...
S3: Request at offset 74970742892, after end of file
S3: Request at offset 74970743375, after end of file
S3: Request at offset 74970743596, after end of file
S3: Request at offset 74970743987, after end of file
S3: Request at offset 74970744670, after end of file
S3: Request at offset 74970744959, after end of file
...
```
in the result from whatever that read after `S3: Downloading 148914176-149946367` is trying to do!

**Comment by rouault** [comment]
@youngpm I believe this should be fixed with https://github.com/OSGeo/gdal/pull/9662. Can you give it a try?

**Comment by youngpm** [comment]
Looks good, commented over in the branch: https://github.com/OSGeo/gdal/pull/9662#issuecomment-2057161548
